### ISSUE TITLE
error when providing a bed file for targeted samples

### ISSUE THREAD

**Issue by albcarrasco** [nf-core/sarek#1004]
### Description of the bug

Hi! 
My input to sarek is fastq files from targeted gene panels, so I use `--wes` and a bed file after `--intervals`.
I get an error at the base recalibrator step which uses gatk:
```
Error executing process > 'NFCORE_SAREK:SAREK:BAM_BASERECALIBRATOR:GATK4_BASERECALIBRATOR (SampleB)'

Caused by:
  Essential container in task exited

Command executed:

  gatk --java-options "-Xmx4g" BaseRecalibrator  \
      --input SampleB.md.cram \
      --output SampleB_chr3_9166297-9166676.recal.table \
      --reference human_g1k_v37_decoy.fasta \
      --intervals chr3_9166297-9166676.bed \
      --known-sites dbsnp_138.b37.vcf.gz --known-sites 1000G_phase1.indels.b37.vcf.gz --known-sites Mills_and_1000G_gold_standard.indels.b37.vcf.gz \
      --tmp-dir . \
  
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SAREK:SAREK:BAM_BASERECALIBRATOR:GATK4_BASERECALIBRATOR":
      gatk4: $(echo $(gatk --version 2>&1) | sed 's/^.*(GATK) v//; s/ .*$//')
  END_VERSIONS

Command exit status:
  2

Command output:
  (empty)


A USER ERROR has occurred: Badly formed genome unclippedLoc: Contig chr3 given as location, but this contig isn't present in the Fasta sequence dictionary
```
In ran the pipeline several times and got a different 'chr' every time, so it does not look like a problem with the format of a specific chromosome.

The reference genome I am using is hg19 and the bed file is formatted accordingly (using chr).
I attach the command and the bed file I used. 

Thank you so much!

### Command used and terminal output

```console
nextflow run nf-core/sarek --input pancancer_spreadsheet.csv --outdir sarek_pancancer --genome GATK.GRCh37 --wes --intervals BED/AGL_hg19.bed -profile docker --tools strelka,freebayes,manta,tiddit,mpileup,haplotypecaller,merge
```

### Relevant files

[BED.zip](https://github.com/nf-core/sarek/files/11285271/BED.zip)

### System information

Nexflow 22.10.7.5853
nf-core/sarek 3.1.2
Docker
awsbatch
Linux Mint

**Comment by FriederikeHanssen** [comment]
Hey! Was this resolved?

**Comment by albcarrasco** [comment]
Hi! I am so sorry, I delayed this because other dataset samples took priority. 
I changed the format of the bed file as you suggested after checking the format of the fasta fai for the reference genome used (removing "chr" and leaving just the chromosome number). This actually worked perfectly for other datasets, thanks! 

However, I still get an error for the data that started this issue. This time the error shows up at a different step of the pipeline:

```
-[nf-core/sarek] Pipeline completed with errors-
Error executing process > 'NFCORE_SAREK:SAREK:FASTQ_ALIGN_BWAMEM_MEM2_DRAGMAP:BWAMEM1_MEM (SampleB-L1)'

Caused by:
  Essential container in task exited

Command executed:

  INDEX=`find -L ./ -name "*.amb" | sed 's/.amb//'`
  
  bwa mem \
      -K 100000000 -Y -R "@RG\tID:HF32VDMXX.SampleB.L1\tPU:L1\tSM:patient1_SampleB\tLB:SampleB\tDS:s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Sequence/WholeGenomeFasta/human_g1k_v37_decoy.fasta\tPL:ILLUMINA" \
      -t 16 \
      $INDEX \
      0003.SampleB-L1_1.fastp.fastq.gz 0003.SampleB-L1_2.fastp.fastq.gz \
      | samtools sort  --threads 16 -o SampleB-L1.0003.bam -
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SAREK:SAREK:FASTQ_ALIGN_BWAMEM_MEM2_DRAGMAP:BWAMEM1_MEM":
      bwa: $(echo $(bwa 2>&1) | sed 's/^.*Version: //; s/Contact:.*$//')
      samtools: $(echo $(samtools --version 2>&1) | sed 's/^.*samtools //; s/Using.*$//')
  END_VERSIONS

Command exit status:
  -

Command output:
  (empty)

Command error:
  bash: /home/ec2-user/miniconda/bin/aws: No such file or directory
  bash: line 1: /home/ec2-user/miniconda/bin/aws: No such file or directory

Work dir:
  s3://flomics-scratch/nextflow-workdir/9e/e84efe64d69ecda3c8a1c9e0312d27

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

```

The command used for launching this run is the same as the one in the original post.  I tried to check `.command.out` but this file was not generated in the work directory (none of the .command. files were for some reason).

**Comment by asp8200** [comment]
It seems to me that you need to install the aws-cli in your conda environment, but I could be wrong. Did you take a look at the docs concerning aws and nextflow?

https://www.nextflow.io/docs/latest/awscloud.html#aws-cli

**Comment by albcarrasco** [comment]
Hi! I am sorry again because this attempt was delayed again because other datasets took higher priority.

I consulted my lab partners and the error concercing aws-cli happens sometimes in our server, so I just re-ran the pipeline and it worked fine. Adjusting the format of the bed file made the trick in my case as suggested initially by the developers.

Thank you so much for your patience and your help! The issue can be closed.
