### ISSUE TITLE
Error running VQSR in joint VC: nextflow.exception.MissingProcessException: Missing process or function mix

### ISSUE THREAD

**Issue by amizeranschi** [nf-core/sarek#1016]
### Description of the bug

Hello,

I'm getting the error in the title when attempting to run a joint variant calling pipeline. The error appears almost as soon as the pipeline starts running and the stack trace contains the following:

```
[...]
	at nextflow.cli.CmdRun.run(CmdRun.groovy:368)
	at nextflow.cli.Launcher.run(Launcher.groovy:494)
	at nextflow.cli.Launcher.main(Launcher.groovy:653)
Caused by: groovy.lang.MissingMethodException: No signature of method: java.lang.String.mix() is applicable for argument types: (String) values: [--resource:ensemblvcf,known=false,training=true,truth=true,prior=10.0 Saccharomyces_cerevisiae.vcf.gz]
Possible solutions: md5(), is(java.lang.Object), wait(), trim(), next(), find()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
[...]
```

The error seems to refer to the way I've configured `--dbsnp_vqsr`, so I can't rule out a configuration error.

I'm attaching a script that reproduces the error using some yeast data. It should take less than 5 minutes to run.

### Relevant files

[sarek-error.sh.txt](https://github.com/nf-core/sarek/files/11414161/sarek-error.sh.txt)

### System information

Nextflow 23.04.0 or 23.04.1
nf-core/sarek dev -latest

**Comment by FriederikeHanssen** [comment]
Do you also have the full log file?

**Comment by amizeranschi** [comment]
Sure, here's the full log. Were you able to reproduce the error using the script I provided?

[error.nextflow.log.txt](https://github.com/nf-core/sarek/files/11414262/error.nextflow.log.txt)

**Comment by amizeranschi** [comment]
My guess is that the error is generated from here: https://github.com/nf-core/sarek/blob/dev/subworkflows/local/bam_variant_calling_germline_all/main.nf#L150

**Comment by asp8200** [comment]
I think I got the same or at least a very similar error. As far as I could tell, it is these lines with the mix-operator

https://github.com/nf-core/sarek/blob/a36f952b3d26a3b03dcff3c158dd77c1c16a176f/subworkflows/local/bam_joint_calling_germline_gatk/main.nf#L59-L60

which cause an error msg like

`Missing process or function mix([--resource:dbsnp,known=false,training=true,truth=false,prior=2.0 dbsnp_146.hg38.vcf.gz])`

**Comment by amizeranschi** [comment]
@asp8200 Which command are you running? Could you also try running the commands [from here](https://github.com/nf-core/sarek/files/11414161/sarek-error.sh.txt)? Does this also reproduce the error for you?

**Comment by amizeranschi** [comment]
This was solved in https://github.com/nf-core/sarek/pull/1022
