### ISSUE TITLE
Error when running nextflow: ERROR ~ No signature of method: java.util.LinkedList.withInputStream()

### ISSUE THREAD

**Issue by Chrisdoan9** [nf-core/sarek#1017]
### Description of the bug

Hi all,

After fixing some errors, I got another error. Would you please have a look? Let me know if you need the log file and sample sheet. Thanks in advance 😃.

### Command used and terminal output

```console
nextflow run nf-core/sarek --input sample_sheet_sarek.csv --outdir /labs/ --genome GATK.GRCh38 -profile singularity

WARN: There’s no process matching config selector: NFCORE_SAREK:sarek:CRAM_QC_NO_MD:SAMTOOLS_STATS -- Did you mean: NFCORE_SAREK:sarek:CRAM_QC_RECAL:SAMTOOLS
_STATS?
ERROR ~ No signature of method: java.util.LinkedList.withInputStream() is applicable for argument types: (Script_662cb5ec$_flowcellLaneFromFastq_closure6) va
lues: [Script_662cb5ec$_flowcellLaneFromFastq_closure6@6ad1c7a5]
```

### Relevant files
[nextflow_error.log](https://github.com/nf-core/sarek/files/11456385/nextflow_error.log)

### System information
Nextflow version 23.04.0

**Comment by FriederikeHanssen** [comment]
Hi! Was this fixed after the various discussions on slack? :)

**Comment by Chrisdoan9** [comment]
Yes, it was fixed 😄.
