### ISSUE TITLE
Passing `--wes true` intervals to mosdepth?

### ISSUE THREAD

**Issue by mschubert** [nf-core/sarek#1021]
Sequencing depth calculation on exomes (_i.e._ with `--wes true`) currently reports the genome coverage in `mosdepth`, not the exome coverage.

I believe this is because the `--by` parameter is empty in this case. Shouldn't this pass the intervals bed file here? (either the default intervals or the user-specified)

https://github.com/nf-core/sarek/blob/c87f4eb694a7183e4f99c70fca0f1d4e91750b33/conf/modules/modules.config#L64

**Comment by FriederikeHanssen** [comment]
Yep that looks about right. I guess we lost by somewhere

**Comment by FriederikeHanssen** [comment]
Hi! Because the bed file is a file it is set directly in the module here: https://github.com/nf-core/sarek/blob/c87f4eb694a7183e4f99c70fca0f1d4e91750b33/modules/nf-core/mosdepth/main.nf#L37 

can you send the report that you are unhappy with so we can look into the issue?

**Comment by mschubert** [comment]
_(Correction: this is concerning providing the intervals file, not the parameter passing)_

Thanks Friederike! I'm running _sarek_ `3.2.1` on the same tumor/normal exome sample, once with `--wes true` and once without. In the _multiqc_ report, I get:

For the `--wes true` run, in _Main options_:

* _wes_ true
* _intervals_ igenomes/Homo_sapiens/GATK/GRCh38/Annotation/intervals/wgs_calling_regions_noseconds.hg38.bed

For the other run:

* _intervals_ igenomes/Homo_sapiens/GATK/GRCh38/Annotation/intervals/wgs_calling_regions_noseconds.hg38.bed

So it looks like both use the same intervals file, which is not restricted to (some definition) of the exome, but the _wgs_ regions. The [documentation](https://nf-co.re/sarek/3.1.2/parameters) states:

> _wes_ Enable when exome or panel data is provided.
> _intervals_ Path to target bed file in case of whole exome or targeted sequencing or intervals file.

So I know I can provide a custom exome target file using the `--intervals` parameter, but I seem to recall that _sarek_ would provide a default intervals file for exomes. Looking at the above report, that is not the case. And downstream of this behavior, I get the genome read coverage reported instead of the exome coverage.

Is this by design?

**Comment by FriederikeHanssen** [comment]
Hey! No that indeed looks like a bug. I will take a look at the channel definition.

**Comment by FriederikeHanssen** [comment]
Hey! Actually re-reading it again, it seems correct.  Somehow I assumed you provided a bed file for your sequencing kit.  Sarek doesn't have a default intervals files for exomes. It is highly recommended you provide one though.

**Comment by mschubert** [comment]
Ok, thanks a lot @FriederikeHanssen! Then I misunderstood how the intervals work for exomes and that this file should always be provided.

Sorry for the confusion.
