### ISSUE TITLE
warning while running sarek 3.1.2 --step variant_calling 

### ISSUE THREAD

**Issue by FrancisNietzsche** [nf-core/sarek#1026]
### Description of the bug

First I tried to run the whole sarek workflow from the mapping step, yet it automatically stopped after finishing preprocessing steps, the remaining variant_calling and annotation steps weren't executed.
So I tried another way: step by step, and start by variant_calling step, however, no results regarding variant_calling were generated even though it showed that the pipeline was finished.

### Command used and terminal output

```console
nextflow run /dssg/home/acct-medlhp/medlhp-wzc/software/sarek --step variant_calling --tools Strelka --input /dssg/home/acct-medlhp/medlhp-wzc/project/sarek_jobs/results/0517/csv/recalibrated.csv --igenomes_base /dssg/home/acct-medlhp/medlhp-wzc/references  --outdir /dssg/home/acct-medlhp/medlhp-wzc/project/sarek_jobs/results/0517-2 --genome GATK.GRCh38 -profile singularity
```

### Relevant files

[25080362.zip](https://github.com/nf-core/sarek/files/11505103/25080362.zip)

### System information

Hardware (HPC)
Executor (slurm)
Container engine: (Singularity)
OS (CentOS Linux)

**Comment by asp8200** [comment]
@FriederikeHanssen and @maxulysse : How about we just convert whatever toolname the user provides to lower case?

**Comment by maxulysse** [comment]
We used to do that, but that's no taken care of with the json schema, error should give it clues about what to do
