### ISSUE TITLE
FilterMutect2Calls complains about '.' when expecting a numeric value in MPOS fields

### ISSUE THREAD

**Issue by DrJCampbell** [nf-core/sarek#103]
Mutect2 complains about '.' when it expects a numeric value during the FilterMutect2Calls process. This appears to be caused by large negative values assigned to the MPOS Info field being converted to '.' by bcftools. We have verified that replacing these '.' with numeric values (we arbitrarily used 5) fixes the problem but this is obviously not an ideal solution.

**Comment by adrlar** [comment]
This is a bug in mutect2 (https://github.com/broadinstitute/gatk/issues/6342) which, according to the GATK team, should be fixed with this PR https://github.com/broadinstitute/gatk/pull/6485

**Comment by adrlar** [comment]
New GATK release has implemented this bugfix. I tried the PR they submitted earlier and it does fix this issue.
https://github.com/broadinstitute/gatk/releases/tag/4.1.6.0

**Comment by MaxUlysse** [comment]
OK, good to know, I'll add the 4.1.6.0 to the new container for the coming 2.6 release then.

**Comment by DrJCampbell** [comment]
We're using the v2.6 release of sarek and this seems to be fixed now - thanks
