### ISSUE TITLE
 Inquiry Regarding Somatic Analysis and Normal Sample Requirement

### ISSUE THREAD

**Issue by Sadiki-Noureddine** [nf-core/sarek#1033]
### Description of the bug

Dear All,

I have two questions:

1.    I plan to perform somatic analysis on 10 different tumor BAM files to determine the SNPs, indels, and CNVs. Is it necessary to have 10 distinct normal files corresponding to each tumor BAM file, or can I use a single normal file for all 10 BAM files?

2.    If I don't have a normal file and still want to perform somatic analysis, is there a solution to do it without requiring a normal sample?

Best regards,

**Comment by FriederikeHanssen** [comment]
Hi! Sorry this got missed. For such questions, slack might give you a faster turn around time: nf-co.re/join :) 
To answer your question:

1. The pipeline can handle multiple tumor to one normal sample matches. 
2. Yes tumor-only variant calling is supported. You can check here: https://nf-co.re/sarek/3.2.1/usage#which-variant-calling-tool-is-implemented-for-which-data-type
