### ISSUE TITLE
onComplete-Mailing fails when running awsbatch-s3 and attaching multiQC report

### ISSUE THREAD

**Issue by lassefolkersen** [nf-core/sarek#1034]
### Description of the bug

When running Sarek in `--profile awsbatch` using s3 as work and results folder, the Sarek-oncomplete mail-out [activated here](https://github.com/nf-core/sarek/blob/c87f4eb694a7183e4f99c70fca0f1d4e91750b33/workflows/sarek.nf#LL1105C81-L1105C95) fails. When inserting `multiqc_report.view()` in the code directly above it prints:
```
/bucket/work/eb/fe52c40d4185bd22d6078b45ec32d7/multiqc_report.html
```
This would be a correct path to a multiqc-report when running e.g. local docker, but it seems to not resolve correctly when given to the sendmail command [here](https://github.com/nf-core/sarek/blob/c87f4eb694a7183e4f99c70fca0f1d4e91750b33/lib/NfcoreTemplate.groovy#L76-L92). Then the mail-out fails silently, [logging](https://github.com/nf-core/sarek/blob/c87f4eb694a7183e4f99c70fca0f1d4e91750b33/lib/NfcoreTemplate.groovy#L125) `Sent summary e-mail to $email_address (sendmail)-"`, but not sending any email.

I've made the following tests to establish this is the cause:
1. adding `-N myemail@gmail.com` to the nextflow command, for 'notify', does produce a generic _nextflow_-notification email, so sendmail system is configured correctly and ports are open
2. Setting `plaintext_email = true` in nextflow.config does produce an additional _nfcore/sarek_-notification email, without multiqc report as expected.
3. Setting `max_multiqc_email_size = 0` does produce the same additional _nfcore/sarek_-notification email, without multiqc report as expected.

This [github issue](https://github.com/Arcadia-Science/seqqc/pull/41) seems related, but still not exactly the same.

### Command used and terminal output

```console
nextflow run /home/ubuntu/Nucleus-sarek/main.nf -profile awsbatch --input 'samples.csv' --step annotate  --tools 'snpeff' --email 'myemail@gmail.com' -N 'myemail@gmail.com'
#no email

nextflow run /home/ubuntu/Nucleus-sarek/main.nf -profile awsbatch --input 'samples.csv' --step annotate  --tools 'snpeff' --email 'myemail@gmail.com' -N 'myemail@gmail.com' --max_multiqc_email_size 0
#yes email
```

### System information

- nextflow version 22.10.3.5834
- sarek version 3.0.1 (ok I'm slow, but the relevant code is unchanged up until the 3.1.2)
- Ubuntu 22.04 LTS
- AWS instance

**Comment by FriederikeHanssen** [comment]
Hey! Is this persisting? I keep getting emails when running on aws regularly now

**Comment by lassefolkersen** [comment]
Let me check, back then the problem was that multiQC was saved on S3, and the sendmail functionality didn't really have functionality to read from that. It's on my to-do now to see if I can reproduce in latest  version.

**Comment by lassefolkersen** [comment]
Yeah I think this can be closed, thanks for keeping track!
