### ISSUE TITLE
Investigate failing concatenate_vcfs singularity tests

### ISSUE THREAD

**Issue by maxulysse** [nf-core/sarek#1037]
cf https://github.com/nf-core/sarek/issues/1032

**Comment by asp8200** [comment]
This error is now on the `dev`-branch, right?  I'll see if I can reproduce it when running pytest (or corresponding nf-cmd) locally.

**Comment by maxulysse** [comment]
Can you check if deepvariant itself is working properly?

**Comment by asp8200** [comment]
> Can you check if deepvariant itself is working properly?

I was just about to do that :-)

**Comment by asp8200** [comment]
FYI: The concatenate_vcfs-test works if I remove deepvariant, that is, this works:
```
TMPDIR=/home/aspe/nf_tmp PROFILE=singularity nextflow run main.nf -profile test --input ./tests/csv/3.0/mapped_joint_bam.csv --concatenate_vcfs --tools freebayes,haplotypecaller,manta,mpileup,strelka,tiddit --step variant_calling --outdir results
```

Something fishy with deepvariant

**Comment by maxulysse** [comment]
But tests were good for deepvariant: https://github.com/nf-core/sarek/actions/runs/5070041358/jobs/9111022814

**Comment by asp8200** [comment]
Hmmm 🤔  I also get the above-mentioned when trying to run the basic deepvariant test:

```
TMPDIR=/home/aspe/nf_tmp PROFILE=singularity nextflow run main.nf -profile test,tools_germline --tools deepvariant --outdir results
```
