### ISSUE TITLE
Deepvariant support

### ISSUE THREAD

**Issue by kokyriakidis** [nf-core/sarek#105]
Hi! It would be amazing if you added deepvariant support :)

**Comment by MaxUlysse** [comment]
Hi @kokyriakidis, it is something that we considered (cf #95).
There is currently a [nf-core/deepvariant](https://github.com/nf-core/deepvariant) pipeline within nf-core.
My plan is to incorporate that as a module into sarek when we'll switch to Nextflow DSL2.
