### ISSUE TITLE
results folder not seen in sarek output

### ISSUE THREAD

**Issue by olu2016** [nf-core/sarek#1054]
### Description of the bug

Hi,

I'm running Sarek on N-T pair samples and would like to have access to recalibrated bam/bai files. Surprisingly, I have not been able find the results folder for me to locate the bam files as indicated in the documentation as follows:

`results/Preprocessing/[SAMPLE]/Recalibrated`

`[SAMPLE].recal.bam and [SAMPLE].recal.bai`

How can I find the bam files?

Thanks

**Comment by maxulysse** [comment]
Can you give more information?
What was the sarek version?
What was the command line?
Do you have any log to share?

**Comment by olu2016** [comment]
cmd:

`nextflow run -resume /AnalysisFolder/WES/SAREK2/sarek/main.nf \
        -profile vm03 \
        --input /AnalysisFolder/WES/SAREK2/sarek/samplesheet.csv \
        --outdir /AnalysisFolder/WES/SAREK2/sarek_out \
        --tools freebayes,mutect2,strelka,cnvkit,tiddit,merge \
        -with-conda true`

Sarek version:
`nf-core/sarek v3.1.2`

**Comment by FriederikeHanssen** [comment]
sarek 3.1.2 by default produces cram files. If you would like to have bam files, see: https://nf-co.re/sarek/3.1.2/parameters#save_output_as_bam However, based on the file path ou provided, it looks it might be an older version. I would recommend adding `-r 3.1.2` to your command to be sure you are running the right version

**Comment by olu2016** [comment]
Adding --save_output_as_bam worked. Thanks
