### ISSUE TITLE
amplicon mode

### ISSUE THREAD

**Issue by egenomics** [nf-core/sarek#108]
Hi,
It would be a cool enhancement to have an "amplicon mode" for targeted sequencing (i.e. illumina cancer panels, etc).
Probably the big differences with what there is the inclusion of a manifest (bed file with targeted regions). 

QC [fastqc+multiqc]
alignment [bwa-mem]
[deduplication?]<-probably not needed
variant calling [gatk,strelka]

Quality control for target capture experiments:
https://bioconductor.org/packages/release/bioc/html/TEQC.html

CNV:
Currently using CoNVaDING. I am sure there are better alternatives out there.
https://github.com/molgenis/CoNVaDING 
Probably a good alternative is CNVkit: https://cnvkit.readthedocs.io/en/stable/

Calculation of coverages in the targeted regions, gene level and exon level.

**Comment by egenomics** [comment]
A very good package for the calculation of coverages would be 
https://github.com/brentp/mosdepth

It looks like it can be integrated into multiQC as well.

**Comment by MaxUlysse** [comment]
@szilvajuhos Do you think [mosdepth](https://github.com/brentp/mosdepth) could be a solution for #70?

**Comment by szilvajuhos** [comment]
Short answer is yes, the long answer is that we also have to integrate into MultiQC ;)

**Comment by MaxUlysse** [comment]
I think what @egenomics meant it that it was in MultiQC already: https://multiqc.info/docs/#mosdepth

**Comment by MaxUlysse** [comment]
Hi @egenomics, we just released 2.6, and we now include CNVkit, and the new parameter `--skip_markduplicates` allow to skip the MarkDuplicates process.
So I think I can finally close this issue.
Thanks a lot for all your suggestions
