### ISSUE TITLE
Ensembl VEP is skipped when using custom a custom genome (--igenomes_ignore --genome null)

### ISSUE THREAD

**Issue by amizeranschi** [nf-core/sarek#1084]
### Description of the bug

Using Nextflow v. 23.04.1 and sarek v. 3.2.0, Ensembl VEP is being executed fine with a built-in genome, but it ends up getting silently skipped (with no error or warning in the logs) with a custom genome for the same species. I tested this in yeast, as follows:

With a custom genome, the command below skips VEP:

```
nextflow run nf-core/sarek -r 3.2.0 \
--skip_tools haplotypecaller_filter,baserecalibrator,markduplicates \
-profile docker \
--input sample-sheet.csv \
--outdir sarek-test-jointVC \
--max_time '336.h' \
--max_cpus '64' \
--max_memory '256.GB' \
--fasta ${main_dir}/reproducible-sarek-error/Saccharomyces_cerevisiae.R64-1-1-chr.fa \
--fasta_fai ${main_dir}/reproducible-sarek-error/Saccharomyces_cerevisiae.R64-1-1-chr.fa.fai \
--dict ${main_dir}/reproducible-sarek-error/Saccharomyces_cerevisiae.R64-1-1-chr.dict \
--save_mapped \
--vep_cache ${main_dir}/reproducible-sarek-error/Saccharomyces_cerevisiae \
--bwa ${main_dir}/reproducible-sarek-error/bwa-index \
--igenomes_ignore \
--genome null \
--tools haplotypecaller,vep \
--vep_out_format tab \
--vep_include_fasta
```

With the built-in genome, VEP is being executed:

```
nextflow run nf-core/sarek -r 3.2.0 \
--skip_tools haplotypecaller_filter,baserecalibrator,markduplicates \
-profile docker \
--input sample-sheet.csv \
--outdir sarek-test-jointVC \
--max_time '336.h' \
--max_cpus '64' \
--max_memory '256.GB' \
--save_mapped \
--genome R64-1-1 \
--tools haplotypecaller,vep \
--vep_out_format tab \
--vep_include_fasta
```

I am including two log files below, one for a test in which VEP was skipped and one where VEP was executed.

### Relevant files

[this-skipped-vep.log.txt](https://github.com/nf-core/sarek/files/11687597/this-skipped-vep.log.txt)

[this-ran-vep.log.txt](https://github.com/nf-core/sarek/files/11687592/this-ran-vep.log.txt)

**Comment by Adrian-Zet** [comment]
Hello amizeranschi,

I am writing this pull request to get some feedback regarding the amizeranschi/bcbio-full (https://hub.docker.com/r/amizeranschi/bcbio-full/tags)
We know that bcbio-vm docker image has been discontinued. 
Thus in the absence of any documentation we want to know if amizeranschi/bcbio-full docker image is a functional image and can be installed to run bcbio in a containerized version. Also, in this case, how are the databases installed, must they be installed outside of the docker image?

Many thanks,
Adrian

**Comment by amizeranschi** [comment]
Hi @Adrian-Zet 

Sadly, no, that Docker image turned out not to function well via bcbio-vm. It was an unsuccessful attempt at cramming the latest bcbio stable release (1.2.9) into one image. Thanks for reminding me about it as I'm going to go ahead and delete it now, since it's far too big at 9GB for a Docker image and it's just wasting space at Docker Hub.

I have since started checking out the nf-core pipelines: https://nf-co.re/pipelines

There's nf-core/sarek vor variant calling, nf-core/rnaseq for RNA-seq (up to generating read counts), nf-core/differentialabundance for differential gene expression etc. There's even a dedicated pipeline for download raw NGS reads from NCBI SRA or EBI ENA: [nf-core/fetchngs](https://nf-co.re/fetchngs).

**Comment by amizeranschi** [comment]
As it turns out, this was no bug, but just a configuration error. The custom genome setup required some additional VEP parameters (hidden by default in the documentation) which were set up automatically for the built-in genome. 

For example: https://nf-co.re/sarek/3.2.1/parameters#vep_genome.
