### ISSUE TITLE
Error with BAM_MERGE_INDEX when using bwa-mem2: Unsorted positions on sequence #4: 1260047 followed by 1259502

### ISSUE THREAD

**Issue by amizeranschi** [nf-core/sarek#1097]
### Description of the bug

I'm getting an error about unsorted reads at the `BAM_MERGE_INDEX` stage, when using BWA-mem2. As far as I could tell, it only happens with bwa-mem2, and not with regular bwa-mem.

I am attaching the full log and a script that consistently reproduces the error on my machine.

```
ERROR ~ Error executing process > 'NFCORE_SAREK:SAREK:BAM_MERGE_INDEX_SAMTOOLS:INDEX_MERGE_BAM (SRR9041541)'

Caused by:
  Process `NFCORE_SAREK:SAREK:BAM_MERGE_INDEX_SAMTOOLS:INDEX_MERGE_BAM (SRR9041541)` terminated with an error exit status (1)

Command executed:

  samtools \
      index \
      -@ 0 \
       \
      SRR9041541.sorted.bam
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SAREK:SAREK:BAM_MERGE_INDEX_SAMTOOLS:INDEX_MERGE_BAM":
      samtools: $(echo $(samtools --version 2>&1) | sed 's/^.*samtools //; s/Using.*$//')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  [E::hts_idx_push] Unsorted positions on sequence #4: 1260047 followed by 1259502
  [E::sam_index] Read 'SRR9041541.9001' with ref_name='IV', ref_length=1531933, flags=163, pos=1259502 cannot be indexed
  samtools index: failed to create index for "SRR9041541.sorted.bam"
```

### Relevant files

[sarek-joint-VC.sh.txt](https://github.com/nf-core/sarek/files/11721210/sarek-joint-VC.sh.txt)

[nextflow-error.log.txt](https://github.com/nf-core/sarek/files/11721218/nextflow-error.log.txt)

**Comment by amizeranschi** [comment]
Based on the log, the pipeline expects to find a CRAM file in the work directory, but instead, there seems to be a BAM file there.

```
Jun-12 13:08:58.993 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process `NFCORE_SAREK:SAREK:BAM_MERGE_INDEX_SAMTOOLS:MERGE_BAM (SRR9041541)` is unable to find [UnixPath]: `/home/ubuntu/reproducible-sarek-error/work/1a/a55ef3797c07a277f7944e23636d1a/SRR9041541.sorted.cram` (pattern: `SRR9041541.sorted.cram`)
```

```
~/reproducible-sarek-error/work/1a/a55ef3797c07a277f7944e23636d1a$ ls SRR*
SRR9041541.sorted.bam
```

**Comment by maxulysse** [comment]
But I can see the same with bwamem.

**Comment by amizeranschi** [comment]
I could reproduce it as well with the small test data. In my tests it worked for me with bwamem and GATK, but failed with bwamem2 and GATK spark (I enabled both changes simultaneously). 

Perhaps the problem is somehow related to `--use_gatk_spark`.

**Comment by FriederikeHanssen** [comment]
Hey! Yes this is a known issue when combining with spark, because spark needs query sorted reads, but merge would like to have coordinate sorted ones. @maxulysse at some point we discussed, that the computational overhead would likely be a little too big... But anyways spark has been causing many headaches and the speed savings are not so impressive, so unsure how to proceed. at the least we can validate and tell users that this combination doesn't work

**Comment by maxulysse** [comment]
Then let's just add docs about that, or shall we add tests to prevent that from happening?

**Comment by FriederikeHanssen** [comment]
Tracking in #778
