### ISSUE TITLE
Fix bcftools mpileup

### ISSUE THREAD

**Issue by amnghn** [nf-core/sarek#1099]
### Description of feature

Some versions of samtools and bcftools are not compatible so the pileup file generated by `samtools mpileup` cannot be read by `bcftools call`. Also, it seems `bcftools call` accepts **only a piped input** from `bcftools mpileup`. So the pileup files generated by `samtools mpileup` cannot finally be used for variant calling! I know there might be some ways to figure it out without adding a new feature to the pipeline but I have two suggestions to make Sarek even better: 

1. Replace `samtools mpileup` with `bcftools mpileup`. 
2. Add bcftool call for actual variant calling and generate the final vcf file.

**Comment by FriederikeHanssen** [comment]
Hey as discussed bcftools is already included. actually so is call and the final vcf files should be outputted: https://github.com/nf-core/sarek/blob/6c0d335e17fb4406f527540631da7b26a5fe1464/modules/nf-core/bcftools/mpileup/main.nf#LL36C5-L36C5
