### ISSUE TITLE
Don't run samtools mpileup when only tools mpileup is selected

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#1104]
### Description of the bug

currently samtools mielup and bcftools mpileup are both run when `tools mpileup ` is selected, however only run bcftools then + fix the output docs if this is done

**Comment by asp8200** [comment]
This whole things seems very delicate, and we should probably be very careful when changing the current setup.

The rather puzzling usage of both `samtools mpileup` and `bcftools mpileup` seems to be due to problems with getting the mpileup-subworkflow to play nicely with controllfreec :

https://github.com/nf-core/sarek/pull/832#issuecomment-1315510624

**Comment by FriederikeHanssen** [comment]
so basically samtolls mpileup should be run for controlfreec. But when people select mpileup in tools, bcftools should be used

**Comment by asp8200** [comment]
> so basically samtolls mpileup should be run for controlfreec. But when people select mpileup in tools, bcftools should be used

That sounds like one way (and probably the right way) of fixing this.

However, 'i'd say that Amin's immediate problem is that when Sarek runs with intervals no vcf-file (just mpileup-file) is published, and that happens even though `BAM_VARIANT_CALLING_MPILEUP:GATK4_MERGEVCFS` is called :
```

[bb/93ce90] process > NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_MPILEUP:BCFTOOLS_MPILEUP (testT)            [100%] 4 of 4 ✔
[ab/e1ab50] process > NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_MPILEUP:SAMTOOLS_MPILEUP (testT)            [100%] 4 of 4 ✔
[b7/18fc91] process > NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_MPILEUP:CAT_MPILEUP (testT)                 [100%] 2 of 2 ✔
[11/a1d7aa] process > NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_MPILEUP:GATK4_MERGEVCFS (testT)             [100%] 2 of 2 ✔
```

A quick-fix for Amin might be to add a config for publishing from `BAM_VARIANT_CALLING_MPILEUP:GATK4_MERGEVCFS`.

**Comment by FriederikeHanssen** [comment]
yep that sounds very reasonable. Do you have time to guide him through it?

**Comment by asp8200** [comment]
> yep that sounds very reasonable. Do you have time to guide him through it?

I'll try as best I can

**Comment by asp8200** [comment]
So in `conf/modules/mpileup.config`, I added

    withName: 'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_MPILEUP:GATK4_MERGEVCFS' {
        ext.when   = { (meta.num_intervals > 1) && params.tools && params.tools.split(',').contains('mpileup') }
        publishDir = [
            mode: params.publish_dir_mode,
            path: { "${params.outdir}/variant_calling/mpileup/${meta.id}/" },
            pattern: "*{vcf.gz,vcf.gz.tbi}"
        ]
    }
And, with that, I get `testN.normal.mpileup.gz`,  `testN.vcf.gz` and `testN.vcf.gz.tbi` in `results/variant_calling/mpileup/testN/` when running
```
nextflow run main.nf -profile test,targeted,docker --input ./tests/csv/3.0/mapped_joint_bam.csv --tools mpileup --step variant_calling --outdir results
```
Disclaimer: This quick-fix hasn't been tested with controllfreec. 

@ Amin : Let me know if that works for you.
