### ISSUE TITLE
Pipeline doesn't properly use resource setting from custom.config, when starting analysis from --step variant_calling

### ISSUE THREAD

**Issue by amizeranschi** [nf-core/sarek#1117]
### Description of the bug

As the title says, the resource limits from `custom.config` appear to be ignored and I am seeing messages such as the ones below, during the pipeline's runtime. I am attaching a stand-alone script that reproduces this issue for me. The `custom.config` is embedded within it and I have used this config in previous runs without issues.

These are some of the messages that appear:

```
   ### ERROR ###   Max cpus '[:]' is not valid! Using default value: 2
[GATK HaplotypeCaller] Available memory not known - defaulting to 3GB. Specify process memory requirements to change this.
[GATK MergeVcfs] Available memory not known - defaulting to 3GB. Specify process memory requirements to change this.
etc.
```

### Relevant files

[test-small.sh.txt](https://github.com/nf-core/sarek/files/11785346/test-small.sh.txt)

### System information

Tested with `nf-core/sarek -r 3.2.2` and Nextflow v. `23.04.1`.

**Comment by asp8200** [comment]
@amizeranschi : Could you try and add 
```
params {
    max_memory                 = '128.GB'
    max_cpus                   = 16
    max_time                   = '240.h'
}
```
at the top of your `custom.config` and rerun?  (Just set the max-values to whatever is sensible on your HPC/cluster.)

**Comment by amizeranschi** [comment]
Yup, that did it, thank you. I never realized that I forgot to set those parameters in some of my recent tests. I was previously setting them manually from the `nextflow run` command.

**Comment by asp8200** [comment]
@maxulysse : Is what we are seeing here expected and desired behaviour?  The max-values are set in `nextflow.config` but apparently also need to be set in the `custom.config`?  If so, then I guess this issue can be closed.

**Comment by maxulysse** [comment]
I'm afraid that due to the way we deal with profiles in nf-core, they might still be overwritten whatever you do.
Can you try putting them in a yaml file:
```
max_memory: '128.GB'
max_cpus:16
max_time: '240.h'
```
And feed that to nextflow with the `-params-file` option cf https://www.nextflow.io/docs/latest/config.html#configuration-file

**Comment by FriederikeHanssen** [comment]
yep never ever put parameters in config files. exception might be cluster specific configs in nf-core/configs

**Comment by amizeranschi** [comment]
@FriederikeHanssen what is the difference between parameters and configs? Or, more specifically, what kind of things go into parameter files, and what kind of things go into config files?

The link that @maxulysse included above doesn't seem to explain this very well, or maybe I'm just missing the point somehow.

**Comment by asp8200** [comment]
@amizeranschi : You are not the first to be puzzled about where to set the parameters :

https://github.com/nextflow-io/nextflow/pull/3589/files

I just thought that PR highlighted the info pretty clearly, but you can also find it in the docs:

https://www.nextflow.io/docs/latest/cli.html#pipeline-parameters

**Comment by FriederikeHanssen** [comment]
Anything like ressource request per process or overwritting modules.config can go into a config. Anything you would pass in as a parameter on the cli (e.g. anything with `--` ) into the params-file.{json|yml}

**Comment by amizeranschi** [comment]
I see, this makes sense. Thanks!
