### ISSUE TITLE
Missing Variant depths in MulitQC Report - Bcftools

### ISSUE THREAD

**Issue by skrakau** [nf-core/sarek#114]
With Sarek v2.5.2 on WES data (`--genome 'GRCh38' --input sample_all.tsv --tools HaplotypeCaller,Strelka,Manta --targetBED exome_capture.bed`) the Bcftools 'Variant depths' plot  in the MulitQC report is empty. This would be nice to have in the future.

**Comment by MaxUlysse** [comment]
I'll add this one to my urgent pile :-)

**Comment by FriederikeHanssen** [comment]
They are now appearing in the mqc report with WES data after tool updates and i can't reproduce this issue. Will close for now. Let's reopen in case it comes p again.
