### ISSUE TITLE
Filtering reads by mapping to multiple reference genome

### ISSUE THREAD

**Issue by pmoris** [nf-core/sarek#1144]
### Description of feature

I would like to extend sarek to be able to perform multiple mapping steps in order to filter out reads from contaminating organisms.

Specifically, in my case, my research group would like to filter out human reads from malaria parasites (taken from human blood samples). The method that our lab has used in the past is the same one as described in [this publication by MalariaGEN](https://doi.org/10.12688%2Fwellcomeopenres.16168.2) (one of the most recent and largest studies on malaria genome variation by a big consortium) and boils down to the following:

1) map reads to human reference genome, e.g. via `bwa mem`.
2) filter out proper paired reads / keep non-mapped reads, e.g. via `samtools --exclude-flags 2` =  read mapped in proper pair).
3) extract fastq files from the filtered bam file, e.g. via `samtools fastq`.
4) map reads to the actual reference genome of interest.

One question that immediately comes up is whether this should be coded as a two step approach (assuming most people will want to filter out only a single organism), or whether it should be flexible to as many additional reference genomes as the user desires. The latter is probably more useful to a wider audience, but might be a bit more challenging to code (cleanly)?

Another question could be whether the flag to filter on in samtools should be fixed or customizable.

---

I'm happy to start working on this myself and to start a PR, since my lab already has some existing scripts that perform this step (not Nextflow though unfortunately). 

---

For the sake of completion, we've had some internal discussions on whether or not a "competitive mapping" approach might be a better approach than this filtering one. In a nutshell, this would entail mapping a single time to the concatenated reference genome and only retaining reads that map to the part of the reference corresponding to the genome of interest. An example can be found [here](https://doi.org/10.1186/s12864-020-07229-y). I'm just mentioning it because we might want to add this feature as well at some point in the future and they serve the same purpose.

**Comment by FriederikeHanssen** [comment]
Hi! We recently dicussed this and at the moment think it will be out of scope and extend the pipeline too much, making it harder to maintain. However, it may be very useful as it's own pipeline. Several people have inquired for this feature for different genomics pipelines on slack.
