### ISSUE TITLE
Sarek stops at MULTIQC step.

### ISSUE THREAD

**Issue by portbo** [nf-core/sarek#1167]
### Description of the bug

Sarek abrubtly stops at MULTIQC stage, 

Jul-27 19:22:28.557 [Actor Thread 398] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_SAREK:SAREK:MULTIQC'

Caused by:
  cannot spread the type java.lang.Integer with value 1

### Command used and terminal output

```console
Command:
nextflow run nf-core/sarek -r 3.2.3     -c fullpath/sarek_config_alma.config    -with-tower  --input fullpath/sarek/newsample.csv   --outdir fullpath/sarek/  --genome GATK.GRCh38 -resume

output:
Jul-27 19:22:28.610 [Actor Thread 398] DEBUG nextflow.Session - The following nodes are still active:
[process] NFCORE_SAREK:SAREK:MULTIQC
  status=ACTIVE
  port 0: (value) bound ; channel: multiqc_files
  port 1: (value) bound ; channel: multiqc_config
  port 2: (value) bound ; channel: extra_multiqc_config
  port 3: (value) bound ; channel: multiqc_logo
  port 4: (cntrl) -     ; channel: $

Jul-27 19:22:28.612 [Task submitter] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_SAREK:SAREK:MULTIQC; work-dir=/data/scratch/DGE/DUDGE/MOPOPGEN/jayaramv/Project_K78/sarek/work/9f/970e83940be3d51f6e59c1e26fbe99
  error [nextflow.exception.ProcessFailedException]: Error submitting process 'NFCORE_SAREK:SAREK:MULTIQC' for execution
```

### Relevant files

[nextflow_log.txt](https://github.com/nf-core/sarek/files/12215888/nextflow_log.txt)

**Comment by FriederikeHanssen** [comment]
Everything else went fine? If yes can you try to resume, in the log it says something about `com.amazonaws.SdkClientException: Failed to connect to service endpoint: ` so just wondering if it is a temporary network issue

**Comment by itszhengan** [comment]
Same thing happens here. I'm wondering if it's related to this v3.3.2. I'm trying to change it back to the older version and test it out.
