### ISSUE TITLE
Start pipeline from intermediate cram files

### ISSUE THREAD

**Issue by sxv** [nf-core/sarek#1194]
### Description of the bug

I ran the pipeline with a batch of paired fastq but the server failed after the markduplicate stage and before the recalibration stage. So now I have the md cram files and would like to complete the processing on another server. I tried an input file with the following format:

```
patient,sample,lane,cram,crai
sample,sample,L0,/path/to/preprocessing/markduplicates/sample/sample.md.cram,/path/to/preprocessing/markduplicates/sample/sample.md.cram.crai
```

And used the `--step recalibrate` parameter, but this doesn't seem to work as I expected. What would be the proper way to resume from this intermediate step, on a different server?

Thanks.

### Command used and terminal output

```console
NXF_VER="23.04.1" nextflow run nf-core/sarek -r 3.0.1 -profile docker -params-file X202SC23012617_md_n120.yaml -config sxv.config --step recalibrate

ERROR ~ Invalid method invocation `call` with arguments: [[patient:sample, sample:sample, sex:NA, status:0, id:sample, data_type:cram], /path/to/preprocessing/markduplicates/sample/sample.md.cram, /path/to/preprocessing/markduplicates/sample/sample.md.cram.crai, /path/batch/work/5e/0eb3f688eb245e1587859d7a2ff723/chr1_143184588-223558935.bed, 133] (java.util.LinkedList) on _closure3 type

 -- Check '.nextflow.log' file for details
```

**Comment by FriederikeHanssen** [comment]
Can you try by removing the `lane` column? In fact you should have the csv files available already in your results/csv folder. and if you don't specify any input and add `--step recalibrate` it should automatically pick up that csv file

**Comment by sxv** [comment]
Thanks, that makes sense -- trying it now. Another question -- I was hoping to have the recal results in bam format, but neither the `--generateBam` nor `save_bam_mapped` seem to create bam for this step in the pipeline. Is there a way to specify this rather than having to convert from cram to bam after completion? Thanks again.

**Comment by FriederikeHanssen** [comment]
can you try with this parameter: https://nf-co.re/sarek/3.2.3/parameters/#save_output_as_bam

`generateBam` does not exist, `save_bam_mapped` allows to save the output from the mapping step which is normally not added to the results files

**Comment by sxv** [comment]
Perfect, thanks!

**Comment by sxv** [comment]
@FriederikeHanssen The pipeline has completed successfully using parameter `--save_output_as_bam` but I'm not sure where I'd find these resulting bam files? Is this explained in the documentation? It seems they aren't in `preprocessing` directory where I've previously discovered the cram outputs. Thanks.

$ du -sh *
64K     csv
2.0M    multiqc
38M     pipeline_info
1.9T    preprocessing
11G     reports
1.5M    tabix

---

./preprocessing$ du -sh *
1.2T    mapped
436G    markduplicates
315G    recalibrated
13M     recal_table
