### ISSUE TITLE
Access Denied (Service: Amazon S3; ...)

### ISSUE THREAD

**Issue by davetang** [nf-core/sarek#1195]
### Description of the bug

Unable to download resource files from AWS S3. 

### Command used and terminal output

```console
nextflow run nf-core/sarek \
   -profile docker \
   --genome GATK.GRCh38 \
   --input samplesheet.csv \
   --outdir results
```

### Relevant files

```
Aug-30 11:31:32.578 [main] DEBUG com.upplication.s3fs.AmazonS3Client - Setting S3 glacierRetrievalTier=null
Aug-30 11:31:35.192 [main] DEBUG nextflow.Session - Session aborted -- Cause: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9P1JTF6P1XWPW1CG; S3 Extended Request ID: KDG+NqrqOy52cKq3QKFICh6DqqUUaDPpyxiWJ0
irtK5XYw5yWnu5KY6QjcV5F8p3dEFKztGCDgk=; Proxy: null)
Aug-30 11:31:35.208 [main] ERROR nextflow.cli.Launcher - @unknown
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9P1JTF6P1XWPW1CG; S3 Extended Request ID: KDG+NqrqOy52cKq3QKFICh6DqqUUaDPpyxiWJ0irtK5XYw5yWnu5KY6QjcV5F8p3d
EFKztGCDgk=; Proxy: null)
```

### System information

Nextflow version: nextflow version 23.04.1.5866
Hardware: HPC
Executor: local
Container engine: Docker
OS: CentOS 7
sarek version: nf-core/sarek v3.2.3-ged1cc84

**Comment by maxulysse** [comment]
Hi @davetang, using `--genome GATK.GRCh38` without any other settings will try to get the reference files from iGenomes.
Which I guess is what is causing the issue on your side.
I'd recommend to download the files from this bucket `s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38`, and point to it with `--igenomes_base`

**Comment by davetang** [comment]
Hi @maxulysse, thanks for the reply. The bucket you suggested is different from iGenomes? It doesn't look like I can download from that either.

```console
aws s3 cp s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38 .
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by davetang** [comment]
Just to make the problem and solution more clear to others, the issue was caused by me having saved my AWS credentials in `$HOME/.aws/credentials` for use with AWS CLI. When I ran `nextflow` it was trying to use those credentials to download the reference data from the S3 buckets, which resulted in the 403 error. Confusing error because no credentials are actually needed.

I don't know how to force `nextflow` to use `--no-sign-request` when trying to download from the S3 buckets. If I find out, I'll update this issue. One easy solution (but not a long term one) is to simply move/rename `$HOME/.aws/credentials` file so that it won't be used when `nextflow` is trying to download the reference files.

**Comment by davetang** [comment]
Thanks for the link. Looks like we should set `anonymous` according to the [config documentation](https://www.nextflow.io/docs/latest/config.html#config-aws); but I'm not sure what value to provide. Perhaps true?

```
aws {
    client {
        anonymous = true
    }
}
```

**Comment by maxulysse** [comment]
Yeah that's what I would do.

**Comment by maxulysse** [comment]
But I usually do recommend not to use Nextflow to download the reference files (except in certain cases).
As you are most likely to run any pipeline more than one time.
My recommendation is to download before running the pipeline using the AWS cli, and then point to the correct location with the `--igenomes_base` params.

**Comment by davetang** [comment]
OK! I got it! I was too keen and wanted to jump right into it.

**Comment by maxulysse** [comment]
Don't hesitate to come and join us on Slack

**Comment by FriederikeHanssen** [comment]
@maxulysse we have quite a few users run into this issue. How about we add the configuration to the nextflow.config or actually the template?

**Comment by maxulysse** [comment]
I'd say no, we might want people to use it on the cloud. But what about adding it in a profile in nf-configs?

**Comment by FriederikeHanssen** [comment]
ah yes, good point. Sure, like `-profile igenomes,singularity? or maybe we can add it least to the docs.

**Comment by maxulysse** [comment]
cf https://github.com/nf-core/configs/pull/549

**Comment by mxw010** [comment]
Adding to say that downloading the reference genome manually from aws, and then setting `--genome` and `--igenomes_base` does not solve the issue because somehow building index for tabix also requires downloading from s3. If you already have an .aws/config it might be easier to modify your .nextflow/config to include 

        aws {
            client {
                anonymous = true
            }
        }


as @davetang pointed out and just pull your data manually.
