### ISSUE TITLE
`snpeff_cache` folder is empty

### ISSUE THREAD

**Issue by bounlu** [nf-core/sarek#1207]
### Description of the bug

The default location for SnpEff cache on AWS S3 is empty:

s3://annotation-cache/snpeff_cache/

Hence, the pipeline results in error:

```
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/sarek] Pipeline completed with errors-
WARN: Input tuple does not match input set cardinality declared by process `NFCORE_SAREK:SAREK:VCF_ANNOTATE_ALL:VCF_ANNOTATE_SNPEFF:SNPEFF_SNPEFF` -- offending value: [/annotation-cache/snpeff_cache]
WARN: Killing running tasks (87)
ERROR ~ Error executing process > 'NFCORE_SAREK:SAREK:VCF_ANNOTATE_ALL:VCF_ANNOTATE_SNPEFF:SNPEFF_SNPEFF (1)'

Caused by:
  Not a valid path value type: org.codehaus.groovy.runtime.NullObject (null)


Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
Join mismatch for the following entries: key=[id:LC_AC35_vs_LC_AC00, normal_id:LC_AC00, patient:LC_AC, sex:XX, tumor_id:LC_AC35] values=


Staging foreign file: s3://annotation-cache/vep_cache
ERROR ~ Stream Closed

 -- Check '.nextflow.log' file for details
```

### Command used and terminal output

```console
nextflow run nf-core/sarek \
-latest \
-profile docker \
--step mapping \
--tools freebayes,mpileup,mutect2,strelka,manta,tiddit,ascat,cnvkit,controlfreec,msisensorpro,snpeff,vep,merge \
--input 'samplesheet_sarek.csv' \
--outdir '/data/nextflow/sarek/results/' \
-work-dir '/data/nextflow/sarek/work/' \
-c 'custom.config' \
-r dev \
-resume
```

### System information

N E X T F L O W ~ version 23.08.1-edge
local
Docker
Linux
nf-core/sarek dev

**Comment by maxulysse** [comment]
I'm actually more worried about the:
`WARN: Input tuple does not match input set cardinality declared by process `NFCORE_SAREK:SAREK:VCF_ANNOTATE_ALL:VCF_ANNOTATE_SNPEFF:SNPEFF_SNPEFF` -- offending value: [/annotation-cache/snpeff_cache]`
I'll have a look into it, and try to whip up some better documentation.
Can you try and see if adding `--use_annotation_cache_keys` works?
cf https://nf-co.re/sarek/dev#use_annotation_cache_keys

**Comment by bounlu** [comment]
The link takes me nowhere. It seems that parameter is removed from the docs.

**Comment by maxulysse** [comment]
It's in dev

**Comment by bounlu** [comment]
I also checked dev

**Comment by maxulysse** [comment]
hidden params?

**Comment by bounlu** [comment]
got it!

**Comment by maxulysse** [comment]
Did it fixed the issue?

**Comment by bounlu** [comment]
I couldn't test it yet.

**Comment by bounlu** [comment]
I tested it but it didn't help. I got the same error for `SNPEFF_SNPEFF` step even with `--use_annotation_cache_keys` parameter. I tested it with the latest master release.

**Comment by maxulysse** [comment]
Can you test if https://github.com/nf-core/sarek/pull/1236 is fixing this for you?

**Comment by FriederikeHanssen** [comment]
Is this still an issue?

**Comment by bounlu** [comment]
Not sure as I use local cache now.

**Comment by maxulysse** [comment]
ok, let's close it for now, please re-open if it's still an issue
