### ISSUE TITLE
Sarek documentation: `gender` should be `sex`

### ISSUE THREAD

**Issue by winni2k** [nf-core/sarek#123]
The `samples.tsv` has a second column titled "gender" (https://nf-co.re/sarek/docs/input#information-about-the-tsv-files), but the column actually refers to the sex chromosomes (XX, XY, and perhaps in the future even sex chromosome aneuploidies such as X, XXY, XXXY, etc.?). The gender of the patient is irrelevant. Also, this pipeline runs on mice, and mice don't have gender.

**Comment by ewels** [comment]
Transferred to the sarek repo, as pipeline docs are contained within pipeline repos. Markdown file here: https://github.com/nf-core/sarek/blob/master/docs/input.md#information-about-the-tsv-files

**Comment by MaxUlysse** [comment]
Good point, I'll update the docs regarding that.
