### ISSUE TITLE
Sarek documentation: broken link

### ISSUE THREAD

**Issue by winni2k** [nf-core/sarek#124]
I get a 404 error

```
Sorry, that page could not be found.

It looks like https://nf-co.re/sarek/docs/use_cases/docs/input doesn't exist. 
```

When clicking on the link named "input files and documentation" here: https://nf-co.re/sarek/docs/use_cases#starting-from-raw-fastq-pair-of-fastq-files

**Comment by ewels** [comment]
Markdown with broken link is here: https://github.com/nf-core/sarek/blob/master/docs/use_cases.md#starting-from-raw-fastq---pair-of-fastq-files

**Comment by MaxUlysse** [comment]
Good catch, I'm fixing it right away.

**Comment by MaxUlysse** [comment]
It was actually already fixed in `dev`, I'll try to do a release soon so that I'll go in `master` as well.
Sorry about all that.
