### ISSUE TITLE
ASCAT executing R files

### ISSUE THREAD

**Issue by ggabernet** [nf-core/sarek#125]
Hi, when running Sarek with multiple variant callers, it seems like the first one is picked and the rest are ignored. I run it indicating Strelka and ASCAT, and ASCAT was just ignored. 

```#!/bin/bash

nextflow run ggabernet/nf-core-sarek -r v2.5.2-branch \
--outdir 's3://qbic-bucket-virginia/resultsdirsarekicgc1' \
-w 's3://qbic-bucket-virginia/workdirsarekicgc1' \
--tracedir 's3://qbic-bucket-virginia/tracesarekicgc1' \
--input 's3://qbic-bucket-virginia/icgc-sarek/input-icgc-1.tsv' \
--genome 'GRCh38' \
--tools 'Strelka,ASCAT,snpEff' \
-c awsbatch.config \
--awsregion 'us-east-1' \
--igenomes_base 's3://qbic-bucket-virginia/references' \
--awscli '/home/ec2-user/miniconda/bin/aws' -resume
```

**Comment by MaxUlysse** [comment]
I'll look at it right away.

**Comment by ggabernet** [comment]
Hi Maxime, sorry my bad. The `convertAlleleCounts` process failed and that is why ASCAT was not triggered

**Comment by ggabernet** [comment]
so that's not the issue

**Comment by MaxUlysse** [comment]
OK, good to know, any idea what the problem was?

**Comment by ggabernet** [comment]
Fatal error: cannot open file '/home/ec2-user/.nextflow/assets/ggabernet/nf-core-sarek/bin/convertAlleleCounts.r': No such file or directory

**Comment by ggabernet** [comment]
I had to make a fork to fix the SamToFastq issue, but all the rest of the code is the same as the `2.5.2` release

**Comment by MaxUlysse** [comment]
Did it worked before? Or do you think that it was already an issue?
Maybe we shouldn't use that to call the R script:
```
Rscript ${workflow.projectDir}/bin/convertAlleleCounts.r ...
```

**Comment by ggabernet** [comment]
yes that could be the issue, shouldn't it work directly with `convertAlleleCounts.r` as the bin is added to the path?

**Comment by ggabernet** [comment]
I can test it out and let you know

**Comment by MaxUlysse** [comment]
I'll try it out on our cluster as well.

**Comment by MaxUlysse** [comment]
By the way, if you're using ASCAT, the current `dev` has some good improvement.
You can now specify purity an ploidy

**Comment by ggabernet** [comment]
I've tried `Rscript convertAlleleCounts.r` and directly `convertAlleleCounts.r` (as you have the shebang Rscript line. Nothing works:
```.command.sh: //nextflow-bin/convertAlleleCounts.r: /bin/env: bad interpreter: No such file or directory
```
It's a bit weird as it worked for me in Bcellmagic like the last option

**Comment by ggabernet** [comment]
Ah I just saw the shebang line was missing `/usr/`, I try with this now

**Comment by MaxUlysse** [comment]
it also seems that there's a typo in the shebang for run_ascat.R as well

**Comment by ggabernet** [comment]
yes, I fixed both now, let's see

**Comment by MaxUlysse** [comment]
You're trying on AWS?

**Comment by ggabernet** [comment]
yes, I have to set it up there so we can run ASCAT on ICGC data

**Comment by ggabernet** [comment]
looks good now, the job was immediately killed before. But to make sure I'll post it when it runs through

**Comment by MaxUlysse** [comment]
Good, I made the same changes, and I'm trying it out on our server.
You can make a PR, and if it works for everyone we can merge

**Comment by ggabernet** [comment]
perfect, will do!

**Comment by ggabernet** [comment]
This is solved now, but I am having another issue with `ASCAT`, this time I switched already to the `dev` branch as suggested:

```Loading required package: RColorBrewer
[1] Reading Tumor LogR data...
[1] Reading Tumor BAF data...
[1] Reading Germline LogR data...
[1] Reading Germline BAF data...
[1] Registering SNP locations...
[1] Splitting genome in distinct chunks...
Error in names(x) <- value : 
  'names' attribute [2] must be the same length as the vector [1]
Calls: ascat.GCcorrect -> colnames<-
In addition: Warning message:
In read.table(file = GCcontentfile, header = TRUE, as.is = TRUE) :
  incomplete final line found by readTableHeader on 'input.5'
Execution halted
```

**Comment by ggabernet** [comment]
skipping `ascat.GCcorrect` works, there must be a problem in the GCcontentfile, but it's super hard to debug on AWS, will try on the cluster tomorrow

**Comment by MaxUlysse** [comment]
No problem executing R as we planned.
But I had an issue with the GC file that wasn't recognized.
I'll try to fix that.

**Comment by MaxUlysse** [comment]
OK, I found why you're having currently this bug with #127
I made a mistake with #107 and forgot to snake case fully the params for the ascat gc file in `conf/igenomes.config`.
Since you already have a PR open open, I'll let you correct `ac_lociGC` to `ac_loci_gc`.

**Comment by ggabernet** [comment]
great, let's hope this solves the issues
