### ISSUE TITLE
SNPEFF annotation process interrupted when no cache available

### ISSUE THREAD

**Issue by ducminhnguyenle** [nf-core/sarek#1257]
### Description of the bug

I am using the sarek pipeline latest version (**3.3.1**) with the utilization of `sentieon` workflow in order to perform **joint variant calling** using `sentieon_gvcftyper` for 20 WES samples. However the annotation process with `SNPEFF` is not working with the following errors:

```
-[nf-core/sarek] Pipeline completed with errors-
WARN: Input tuple does not match input set cardinality declared by process `NFCORE_SAREK:SAREK:VCF_ANNOTATE_ALL:VCF_ANNOTATE_SNPEFF:SNPEFF_SNPEFF` -- offending value: []
ERROR ~ Error executing process > 'NFCORE_SAREK:SAREK:VCF_ANNOTATE_ALL:VCF_ANNOTATE_SNPEFF:SNPEFF_SNPEFF (1)'

Caused by:
  Not a valid path value type: org.codehaus.groovy.runtime.NullObject (null)
``` 
I have included the `nextflow.log` file and also the `WES_sentieon_jointcalling_headnode.log` run log file.

### Command used and terminal output

```console
nextflow run main.nf \
    --input /mnt/rdisk/hieule/sarek_sentieon/input/samplesheet.csv \
    --outdir /mnt/rdisk/hieule/sarek_sentieon/output_3.3.1/ \
    -w /mnt/rdisk/hieule/sarek_sentieon/work_dir/ \
    --igenomes_base /mnt/rdisk/hieule/sarek_sentieon/input/references/ \
    --wes \
    --intervals /mnt/rdisk/hieule/sarek_sentieon/input/hg38_Exome_2.0_Plus_Panel_chr.bed \
    -profile docker \
    --aligner sentieon-bwamem \
    --tools sentieon_dedup,sentieon_haplotyper,merge \
    --joint_germline \
    --sentieon_haplotyper_emit_mode gvcf
```

### Relevant files

[WES_sentieon_jointcalling_headnode.log](https://github.com/nf-core/sarek/files/12734166/WES_sentieon_jointcalling_headnode.log)
[nextflow.log](https://github.com/nf-core/sarek/files/12734168/nextflow.log)

### System information

- Nextflow version 23.04.2
- Hardware: HPC
- Container engine: Docker
- OS: Linux Ubuntu 22.04
- Version of nf-core/sarek: 3.3.1

**Comment by asp8200** [comment]
Seems related to the tool-option `merge`  and `snpeff`
```
nextflow run main.nf -profile test_cache,singularity --input ./tests/csv/3.0/mapped_joint_bam.csv --tools haplotypecaller,merge --step variant_calling --joint_germline --outdir results
```
gives
```
ERROR ~ Error executing process > 'NFCORE_SAREK:sarek:VCF_ANNOTATE_ALL:VCF_ANNOTATE_SNPEFF:SNPEFF_SNPEFF (1)'

Caused by:
  Not a valid path value type: org.codehaus.groovy.runtime.NullObject (null)
 ```
on both `master` and `dev`.

@maxulysse is on it.

**Comment by maxulysse** [comment]
Yes, this issue is not related to either sention nor variant calling, but actually just caused by a missing cache for the annotation tool.
I think we'd rather fail early with a proper error than not running the tool, so I have a PR open to fix this issue: https://github.com/nf-core/sarek/pull/1248

**Comment by ducminhnguyenle** [comment]
Thank you for your clear explanation. I will have a look to double check again.
