### ISSUE TITLE
EnsemblVEP output only contains HTML report

### ISSUE THREAD

**Issue by slives-lab** [nf-core/sarek#1268]
### Description of the bug

I am wondering where the output files for EnsemblVEP are located. The output folder only contains HTML reports: /reports/EnsemblVEP/haplotypecaller/test
test.filtered_snpEff_VEP.ann.summary.html
test.filtered_VEP.ann.summary.html

### Command used and terminal output

```console
nextflow run nf-core/sarek -r 3.2.3 -profile singularity --input samplesheet_test.csv --outdir output/ sarek_output_test_haplotypecaller_annotate --genome GATK.GRCh38 --tools haplotypecaller,merge,snpeff,vep
```

**Comment by maxulysse** [comment]
Can you check https://nf-co.re/sarek/docs/output#vep

It should be in annotation/

**Comment by slives-lab** [comment]
I do see the output files in annotation/
