### ISSUE TITLE
Sarek --download_cache does not work properly

### ISSUE THREAD

**Issue by Hadi90Eidgah** [nf-core/sarek#1297]
### Description of the bug

I've repeatedly attempted to download the vep_cache and snpeff_cache files to bypass the need for staging these files every time the pipeline processes samples. However, I consistently encounter similar error messages, whether I follow the guidelines from [Sarek's documentation on customizing snpEff and VEP annotation](https://nf-co.re/sarek/3.3.2/docs/usage#how-to-customise-snpeff-and-vep-annotation) or the instructions provided on Slack. Interestingly, when executing the pipeline on samples using the --use_annotation_cache_keys option, the pipeline stages the required annotation files without any issues.

### Command used and terminal output

```console
nextflow run nf-core/sarek -r 3.3.2 --outdir results --outdir_cache /data/home/hadi.eidgah/small_germline/cache/ --tools vep,snpeff --download_cache --build_only_index --input false

or 

nextflow run /data/home/hadi.eidgah/pipelines/nf-core-sarek_3.3.2/3_3_2 --wes true --intervals /data/home/hadi.eidgah/refrences/Annotation/intervals/SureSelectXT_HS_Human_All_Exon_V8_S33266340_hs_hg38/S33266340_Padded.bed --input /data/home/hadi.eidgah/raw_data/SampleSheets/luisa_small.csv --outdir /data/home/hadi.eidgah/small_germline -profile singularity --tools haplotypecaller,snpeff,vep --use_annotation_cache_keys --download_cache

both raise error:

Files within --vep_cache invalid. Make sure there is a directory named homo_sapiens/110_GRCh38 in s3://annotation-cache/vep_cache/.
https://nf-co.re/sarek/usage#how-to-customise-snpeff-and-vep-annotation
```

**Comment by maxulysse** [comment]
I'd say this is now fixed in dev

**Comment by asp8200** [comment]
> Hello, I'm experiencing the same issue on the dev branch. The cached files failed to download.
> 
> Command used:
> 
> ```nextflow
> nextflow run nf-core/sarek -r dev --outdir results --outdir_cache data --tools vep,snpeff --download_cache --build_only_index --input false
> ```
> 
> Terminal output:
> 
> ```
> Caused by:
>   Process `NFCORE_SAREK:SAREK:DOWNLOAD_CACHE_SNPEFF_VEP:SNPEFF_DOWNLOAD (GRCh38.105)` terminated with an error exit status (127)
> 
> Command error:
>   .command.sh: line 3: snpEff: command not found
> ```
> 
> Thanks

could it be that you need to add `-profile docker` or `-profile singularity`? (There are currently some issues with conda-support on the dev-branch, so avoid using conda - if possible.)

**Comment by FriederikeHanssen** [comment]
If adding `-profile docker` doesn't work can you please provide the .nexflow.log file

**Comment by eolaniru** [comment]
`-profile docker` worked 👍 . Thank you
