### ISSUE TITLE
Config setting `prov.formats`

### ISSUE THREAD

**Issue by LuciaNhuNguyen** [nf-core/sarek#1299]
### Description of the bug

Hello everyone,

I installed nf-core/sarek -r 3.3.2 three weeks ago, and it was running smoothly until today. However, when I ran it again today, I encountered an error related to "prov.formats." I attempted to reinstall both Nextflow and Sarek version 3.3.2, but the error persisted. As a temporary solution, I downgraded to version 3.3.1, and it worked without any issues.

Could you please advise on how I can resolve this error and continue using Sarek 3.3.2?

Thank you, and I wish you all a great weekend.

### Command used and terminal output

```console
nextflow run nf-core/sarek -r 3.3.2 -profile test --outdir .
N E X T F L O W  ~  version 23.10.0
Pulling nf-core/sarek ...
 downloaded from https://github.com/nf-core/sarek.git
Launching `https://github.com/nf-core/sarek` [chaotic_bassi] DSL2 - revision: f034b73763 [3.3.2]
Downloading plugin nf-validation@1.1.1
Downloading plugin nf-prov@1.2.0
Config setting `prov.formats` is required to specify provenance output formats
```

**Comment by asp8200** [comment]
Hadi and I can confirm that it is a problem on v3.3.2 and not a problem on v3.3.1.

**Comment by LuciaNhuNguyen** [comment]
I was really looking forward to updating to the new version, but I'm not sure why it suddenly encountered an error. Interestingly, in version 3.3.1, it felt slower compared to 3.3.2 and 3.3.0. (My feelings is just subjective. )

**Comment by asp8200** [comment]
This problem with Sarek v3.3.2 just popped up today out of the blue. Sarek v3.3.2 didn't have this problem before. It must be some change in "infrastructure" surrounding Sarek that is causing the sudden failure. Perhaps a plugin for nextflow has been updated 🤔 I'm not sure the versions of the plugins have been "fixed" in Sarek.  I see version 1.2.0 was just released today!

**Comment by LuciaNhuNguyen** [comment]
It's so boring. I'm planning on letting the machine run a few samples over the weekend, but now I'll probably have to wait for the results at the beginning of the week to see what the results are. Maybe the machine wants to take a break from Halloween.

**Comment by asp8200** [comment]
Ben intends to patch nf-plow right away. Stay tuned.

**Comment by asp8200** [comment]
The issue has been solved with the release of nf-plov v1.2.1

**Comment by LuciaNhuNguyen** [comment]
Thank you for fixing it very quickly. I'm really surprised by the speed of your team's work; I thought everything would have to wait until next week to be resolved. I tried running Sarek version 3.3.2, and everything is perfect. 
I was even planning to shut down my computer and go home, but now I have to stay to run some tests. Happy Halloween!

**Comment by asp8200** [comment]
If you haven't already joined the Slack-channel for Sarek, then I suggest that you do that. There support tend to be faster, than over gitHub-issues.  Cheers

**Comment by LuciaNhuNguyen** [comment]
Thank you for the recommendation. I'll definitely consider joining the Slack channel for Sarek for faster support. It's good to know that they are responsive there. I appreciate the suggestion. Cheers!

**Comment by LuciaNhuNguyen** [comment]
I ran it on the actual sample and saw it appear like this.
`N E X T F L O W  ~  version 23.10.0
Launching `https://github.com/nf-core/sarek` [tumors_HG38] DSL2 - revision: f034b73763 [3.3.2]
WARN: Config setting `prov.formats` is not defined, no provenance reports will be produced`
 I checked the output files and didn't find any errors, so I think it's just a warning.

**Comment by asp8200** [comment]
Yes, I also noticed the warning and let Ben know about it. I guess it it doesn't matter for the execution of Sarek.

**Comment by LuciaNhuNguyen** [comment]
Thank you for zour quick response.
