### ISSUE TITLE
No more task to compute but following nodes are still active

### ISSUE THREAD

**Issue by winni2k** [nf-core/sarek#130]
I tried resuming a Sarek call on my server at 3pm today, and now it's 9:30pm, and nothing seems to be happening. This is the output of the pipeline on my screen: 
![image](https://user-images.githubusercontent.com/304958/75385161-8b863080-58df-11ea-9901-ae7787c4258d.png)

This is my nextflow log:
[nextflow.log](https://github.com/nf-core/sarek/files/4258049/nextflow.log)

Nothing seems to be running when I look at htop. Any ideas what might be going on?

**Comment by MaxUlysse** [comment]
From the log I can clearly see a couple of things:
First: `No more task to compute`, so I would say that the pipeline is done and all your files are processed.
But then I see also: `The following nodes are still active:` and it's then listing all processes.
So I would say that there's definitively an issue here, but more a Nextflow issue unfortunately.
I'll ping @nf-core/core to see if anyone has an idea, but I'll suggest going to the nextflow gitter or opening an issue on the nextflow github.

**Comment by ggabernet** [comment]
Is this what you were also experiencing, @skrakau ?

**Comment by skrakau** [comment]
Yes, I had the same issue. I used a custom config file with the `-c` parameter to change `max_memory`, and for some reason the igenomes folder (which was specified correctly) was not used anymore, but instead the data was downloaded and staged in a local cache. I don't know why, however, when I specified `--max_memory` as a command line parameter (and used no custom config file anymore), the igenomes folder was used correctly and the problem magically did not occur anymore. 

I saw in your `nextflow.log` file that the genomes data was also downloaded, maybe its related.

**Comment by winni2k** [comment]
Cheers for the feedback. I didn't need all the functionality of Sarek, so i just rolled my own pipeline with snakemake. Perhaps I'll have proper use for sarek in the future, and then it might be worth the hassle of debugging this issue.

**Comment by skrakau** [comment]
The problem also occurred for me again now after I changed one parameter. No idea what I could do to solve it.

**Comment by yocra3** [comment]
I am experiencing a similar problem. For now, I am just testing the workflow with the test dataset. If I run the pipeline using the test profile:

```
nextflow run nf-core/sarek -profile test,docker  --tools 'merge,HaplotypeCaller,Manta,Strelka' --species 'homo_sapiens'
```

The pipeline runs without any problem. However, if I modify the code to use igenomes:

```
nextflow run nf-core/sarek -profile docker  --tools 'merge,HaplotypeCaller,Manta,Strelka' --genome GRCh37 --igenomes_ignore False --species 'homo_sapiens' --input https://raw.githubusercontent.com/nf-core/test-datasets/sarek/testdata/tsv/tiny-manta-https.tsv
``` 

The pipeline gets stuck and I get the same message in the log (No more task to compute but following nodes are still active). I guess that the problem might be the igenomes parameter. Do you have any idea of how I can overcome this issue?

Thanks,
```

**Comment by MaxUlysse** [comment]
@yocra3 Have you tried downloading the GRCh37 iGenomes separately, and using `--igenomes_base` to specify the location?

**Comment by yocra3** [comment]
That worked! Now the pipeline has run without any problem. Thanks.

**Comment by gbinux** [comment]
> Have you tried downloading the GRCh37 iGenomes separately, and using `--igenomes_base` to specify the location?

This is very helpful and fixed my issue similar to what was described above! 
igenomes resources can be downloaded via a command generated from https://ewels.github.io/AWS-iGenomes/ :
`aws s3 --no-sign-request --region eu-west-1 sync s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/ ./references/Homo_sapiens/GATK/GRCh38/`

(`awscli` can be installed via conda)
