### ISSUE TITLE
Switch sarek to DSL 2

### ISSUE THREAD

**Issue by maxulysse** [nf-core/sarek#132]

**Comment by grst** [comment]
List of modules being ported for the chipseq pipeline: 
https://github.com/nf-core/chipseq/issues/167

**Comment by MaxUlysse** [comment]
we opened a new branch to work on dsl2: https://github.com/nf-core/sarek/tree/dsl2

**Comment by FriederikeHanssen** [comment]
- [ ]   conda-forge::markdown=3.1.1
- [ ]   conda-forge::pymdown-extensions=6.0
- [ ]   conda-forge::pygments=2.5.2
- [ ]   bioconda::ascat=2.5.2
- [ ]   bioconda::bcftools=1.9
- [ ]   bioconda::bwa=0.7.17
- [ ]   bioconda::cancerit-allelecount=4.0.2
- [ ]   bioconda::cnvkit=0.9.6
- [ ]   bioconda::control-freec=11.5
- [ ]   bioconda::ensembl-vep=99.2
- [ ]   bioconda::fastqc=0.11.9
- [ ]   bioconda::freebayes=1.3.2
- [ ]   bioconda::gatk4-spark=4.1.7.0
- [ ]   bioconda::genesplicer=1.0
- [ ]   bioconda::htslib=1.9
- [ ]   bioconda::manta=1.6.0
- [ ]   bioconda::msisensor=0.5
- [ ]   bioconda::multiqc=1.8
- [ ]   bioconda::qualimap=2.2.2d
- [ ]   bioconda::samtools=1.9
- [ ]   bioconda::snpeff=4.3.1t
- [ ]   bioconda::strelka=2.9.10
- [ ]   bioconda::tiddit=2.7.1
- [ ]   bioconda::trim-galore=0.6.5
- [ ]   bioconda::vcfanno=0.3.2
- [ ]   bioconda::vcftools=0.1.16
- [ ]   conda-forge::pigz=2.3.4 
- [ ]   conda-forge::r-ggplot2=3.3.0

**Comment by FriederikeHanssen** [comment]
Just added all the tools from the environment yaml of release 2.6.1 with their versions, so we can now port as is.

**Comment by MaxUlysse** [comment]
Or you can already port https://github.com/nf-core/sarek/issues/228

**Comment by FriederikeHanssen** [comment]
Ticked the modules that are already in modules repo and have the same version.

modules that are in repo, but different version
- [ ] FastQC - 0.11.8
- [ ] Trim Galore - 0.6.4

**Comment by FriederikeHanssen** [comment]
- [ ] Add subworkflow for indices (Friederike)
- [ ]

**Comment by FriederikeHanssen** [comment]
Here some more moments to address:

https://github.com/nf-core/modules/pull/50

**Comment by FriederikeHanssen** [comment]
We should probably double check at some point that all the tmp directories are set properly, so that they work, when the users changes it i.e. to `scratch=/my-favorite-dir` , e.g. here: https://github.com/nf-core/sarek/blob/a7679b9b5c178351b1e96a3ffe7ee81ddf9aad06/conf/modules.config#L48
