### ISSUE TITLE
sarek on Kubernetes documentation

### ISSUE THREAD

**Issue by radaniba** [nf-core/sarek#1341]
### Sarek on Kubernetes

I am sorry, this might not be a feature request, rather a general question but I couldn't find where to ask it except here.
I am wondering if there is any documentation on how to run Sarek on a Kubernetes cluster, I am especially concerned about the best configuration to adopt for permanent storage when the pipeline runs, if there is any guidance already published online I would be very grateful.
Cheers,
Rad

**Comment by maxulysse** [comment]
I'm afraid we don't have such documentation, but I opened a feature request on the website as I think it should be more general.
