### ISSUE TITLE
Ascat computes all possible N-T combinations

### ISSUE THREAD

**Issue by ggabernet** [nf-core/sarek#136]
Hi, I was wondering why 25 ascat processes were started when I had just 5 Tumor-Normal pairs, and it turns out that ascat computes all possible N-T combinations. Eg:

Ascat_CHC2113T_vs_CHC2113N
Ascat_CHC2113T_vs_CHC2115N
Ascat_CHC2113T_vs_CHC912N

I can also help with fixing that, just wanted to document it in an issue :)

**Comment by lconde-ucl** [comment]
We fixed it in our local copy of sarek by adding "by: 0" in _alleleCountNormal.combine_. Please note that _alleleCountOutput.map_ needs to be modified accordingly: 

```
alleleCountOutput
  .choice(alleleCountTumor, alleleCountNormal) {it[1] == 0 ? 1 : 0}

alleleCountOutput = alleleCountNormal.combine(alleleCountTumor, by: 0)

alleleCountOutput = alleleCountOutput.map {
  idPatientNormal, statusNormal, idSampleNormal, alleleCountNormal,
  statusTumor,  idSampleTumor,  alleleCountTumor ->
  [idPatientNormal, idSampleNormal, idSampleTumor, alleleCountNormal, alleleCountTumor]
}
```

Hope this helps
Lucia
