### ISSUE TITLE
Adapting nf-core/sarek for Ion Torrent Single-End Data Analysis

### ISSUE THREAD

**Issue by Sadiki-Noureddine** [nf-core/sarek#1370]
### Description of the bug

Hello nf-core/sarek team!

I'm attempting to utilize the Sarek pipeline for analyzing **Ion Torrent data**, but I'm facing challenges with configuring **single-end files**. Unlike Illumina, the Ion Torrent data I have comes in the form of a single FASTQ file per sample.

My issue lies in adapting the sample sheet to accommodate these single-end data. According to the documentation, the sample sheet structure is designed for paired-end data, whereas in my case, I only have one FASTQ file per sample.

Here's an example of my data structure:

patient,sample,lane,fastq_1
patient1,test_sample,lane_1,test.fastq.gz

I've created this simplified configuration for my single FASTQ file, but I'm wondering if there's a specific method to correctly adapt the sample sheet for Ion Torrent single-end data.

Additionally, are there specific parameters or configurations within the Sarek pipeline that need adjustment to support this single-end data type from Ion Torrent?

Any help or guidance in correctly adapting the nf-core/sarek configuration for Ion Torrent single-end data would be greatly appreciated!

Thank you very much for your assistance!

Best regards,

Nour-Eddine

**Comment by Sadiki-Noureddine** [comment]
@robsyme @tucano @ypriverol @robnewman Could I kindly request your assistance, please?

**Comment by FriederikeHanssen** [comment]
I am linking the biostars post here: https://www.biostars.org/p/9570657/

**Comment by maxulysse** [comment]
> I am linking the biostars post here: https://www.biostars.org/p/9570657/

Is this the correct link?

**Comment by FriederikeHanssen** [comment]
ups, corrected above
