### ISSUE TITLE
plugin/nf-validation error on HPC

### ISSUE THREAD

**Issue by jbague** [nf-core/sarek#1384]
### Description of the bug

Hi,
when I try to use the pipeline on HPC environment, different errors
about nextflow plugin appeared. This errors is caused because the HPC
environment cannot connect to internet to download these plugins.

I try to modify the file called nextflow.config changing:
    validationFailUnrecognisedParams = false
    validationLenientMode            = false
    validationSchemaIgnoreParams     = 'cf_ploidy,genomes,igenomes_base'
    validationShowHiddenParams       = false
    validate_params                  = false

but the error continue.

My idea was trying to skip this validation step previous to begin the pipeline because
I validated in local previously (I run completely with 1 sample in Linux). 

### Command used and terminal output

```console
The terminal output is:
N E X T F L O W  ~  version 21.10.6
Launching `./3_4_0/main.nf` [happy_yalow] - revision: 48ed053221
Cannot find latest version of nf-validation plugin
```

### System information

    Nextflow version (eg. 21.10.6)
    Hardware (HPC)
    Executor (slurm)
    Container engine: (Singularity)
    Version of nf-core/sarek (3.4.0)

**Comment by FriederikeHanssen** [comment]
The validation is pretty backed in and used to parse the samplesheet. Did you check the docs for how to use plugins in an offline setting? https://www.nextflow.io/docs/latest/plugins.html#offline-usage

**Comment by FriederikeHanssen** [comment]
hm no, this would be a good question to take to:  https://community.seqera.io/  it's a Nextflow issue not a sarek specific one

**Comment by asp8200** [comment]
@jbague : I also had that error when trying to run Sarek on our offline HPC. The error is a consequence of the version of the plugins not being fixed. One way of avoiding the error is to add the option `-plugins nf-validation@1.1.3` in the nf-command or add
```
plugins {
    id 'nf-validation@1.1.3'
}
```
in `nextflow.config` (if you have that option) or in a custom-config which you then add in the nf-command like `-c my.config`. 

As mentioned above, you'll have to have downloaded and transferred the plugins to your offline HPC, and put in some dedicated plugins-folder:
```
export NXF_PLUGINS_DIR=/path/to/my/nextflow/plugins 
```

https://www.nextflow.io/docs/latest/plugins.html#using-plugins
