### ISSUE TITLE
Figure out if Sarek-dev works with Spark

### ISSUE THREAD

**Issue by asp8200** [nf-core/sarek#1406]
### Description of the bug

Spark may have stopped working after docker.userEmulation was removed in https://github.com/nf-core/sarek/pull/1405.

**Comment by FriederikeHanssen** [comment]
Didn't you test it on your side and it worked fine?

**Comment by asp8200** [comment]
I just ran `nextflow run main.nf -profile test_cache,use_gatk_spark,docker --outdir foo`

**Comment by asp8200** [comment]
I think this was solved. Otherwise reopen.
