### ISSUE TITLE
ERROR - failed to load the meta schema 

### ISSUE THREAD

**Issue by AndyBlake** [nf-core/sarek#1415]
### Description of the bug

All of a sudden sarek stops launching with the error concerning meta schema. Tried updating nextflow, sarek and re pulling sarek to a fresh user

### Command used and terminal output

```console
nextflow run nf-core/sarek -r 3.4.0 -profile test

N E X T F L O W  ~  version 23.10.1
Launching `https://github.com/nf-core/sarek` [drunk_jennings] DSL2 - revision: 6aeac929c9 [3.4.0]
Downloading plugin nf-validation@2.0.0
Downloading plugin nf-prov@1.2.1
WARN: The following invalid input values have been detected:

* --input: /home/webadm/.nextflow/assets/nf-core/sarek/tests/csv/3.0/fastq_single.csv
* --step: mapping
* --genome: null
* --igenomes_base: s3://ngi-igenomes/igenomes/
* --snpeff_cache: null
* --vep_cache: null
* --igenomes_ignore: true
* --save_reference: false
* --build_only_index: false
* --download_cache: false
* --no_intervals: false
* --nucleotides_per_second: 200000
* --tools: strelka
* --skip_tools: null
* --split_fastq: 0
* --trim_fastq: false
* --clip_r1: 0
* --clip_r2: 0
* --three_prime_clip_r1: 0
* --three_prime_clip_r2: 0
* --trim_nextseq: 0
* --save_trimmed: false
* --save_split_fastqs: false
* --umi_read_structure: null
* --group_by_umi_strategy: Adjacency
* --aligner: bwa-mem
* --use_gatk_spark: null
* --save_mapped: false
* --save_output_as_bam: false
* --seq_center: null
* --seq_platform: ILLUMINA
* --ascat_ploidy: null
* --ascat_min_base_qual: 20
* --ascat_min_counts: 10
* --ascat_min_map_qual: 35
* --ascat_purity: null
* --cf_ploidy: 2
* --cf_coeff: 0.05
* --cf_contamination: 0
* --cf_contamination_adjustment: false
* --cf_mincov: 0
* --cf_minqual: 0
* --cf_window: null
* --cnvkit_reference: null
* --concatenate_vcfs: false
* --ignore_soft_clipped_bases: false
* --joint_germline: false
* --joint_mutect2: false
* --only_paired_variant_calling: false
* --sentieon_dnascope_emit_mode: variant
* --sentieon_dnascope_pcr_indel_model: CONSERVATIVE
* --sentieon_haplotyper_emit_mode: variant
* --wes: false
* --bcftools_annotations: https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/sarscov2/illumina/vcf/test2.vcf.gz
* --bcftools_annotations_index: https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/sarscov2/illumina/vcf/test2.vcf.gz.tbi
* --bcftools_header_lines: /home/webadm/.nextflow/assets/nf-core/sarek/tests/config/bcfann_test_header.txt
* --dbnsfp: null
* --dbnsfp_consequence: null
* --dbnsfp_fields: rs_dbSNP,HGVSc_VEP,HGVSp_VEP,1000Gp3_EAS_AF,1000Gp3_AMR_AF,LRT_score,GERP++_RS,gnomAD_exomes_AF
* --dbnsfp_tbi: null
* --outdir_cache: null
* --spliceai_indel: null
* --spliceai_indel_tbi: null
* --spliceai_snv: null
* --spliceai_snv_tbi: null
* --vep_custom_args: --everything --filter_common --per_gene --total_length --offline --format vcf
* --vep_dbnsfp: null
* --vep_include_fasta: false
* --vep_loftee: null
* --vep_out_format: vcf
* --vep_spliceai: null
* --vep_spliceregion: null
* --vep_version: 110.0-0
* --multiqc_config: null
* --multiqc_title: null
* --multiqc_logo: null
* --max_multiqc_email_size: 25.MB
* --multiqc_methods_description: null
* --outdir: null
* --publish_dir_mode: copy
* --email: null
* --email_on_fail: null
* --plaintext_email: false
* --hook_url: null
* --version: false
* --config_profile_name: Test profile
* --config_profile_description: Minimal test dataset to check pipeline function
* --custom_config_version: master
* --custom_config_base: https://raw.githubusercontent.com/nf-core/configs/master
* --config_profile_contact: null
* --config_profile_url: null
* --test_data_base: https://raw.githubusercontent.com/nf-core/test-datasets/sarek3
* --max_memory: 6.5GB
* --max_cpus: 2
* --max_time: 8.h
* --validate_params: true
* --dbsnp: https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/genome/vcf/dbsnp_146.hg38.vcf.gz
* --fasta: https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/genome/genome.fasta
* --germline_resource: https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/genome/vcf/gnomAD.r2.1.1.vcf.gz
* --intervals: https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/genome/genome.interval_list
* --known_indels: https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/genome/vcf/mills_and_1000G.indels.vcf.gz
* --ngscheckmate_bed: https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/genome/chr21/germlineresources/SNP_GRCh38_hg38_wChr.bed
* --snpeff_db: 105
* --snpeff_genome: WBcel235
* --vep_cache_version: 110
* --vep_genome: WBcel235
* --vep_species: caenorhabditis_elegans
* --sentieon_dnascope_model: s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/Sentieon/SentieonDNAscopeModel1.1.model
* --ascat_alleles: null
* --ascat_genome: null
* --ascat_loci: null
* --ascat_loci_gc: null
* --ascat_loci_rt: null
* --bwa: null
* --bwamem2: null
* --cf_chrom_len: null
* --chr_dir: null
* --dbsnp_tbi: null
* --dbsnp_vqsr: null
* --dict: null
* --dragmap: null
* --fasta_fai: null
* --germline_resource_tbi: null
* --known_indels_tbi: null
* --known_indels_vqsr: null
* --known_snps: null
* --known_snps_tbi: null
* --known_snps_vqsr: null
* --mappability: null
* --pon: null
* --pon_tbi: null
* --input_restart: null


ERROR ~ Failed to load the meta schema:
The used schema draft (http://json-schema.org/draft-07/schema) is not correct, please use "https://json-schema.org/draft/2020-12/schema" instead.
See here for more information: https://json-schema.org/specification#migrating-from-older-drafts


 -- Check '.nextflow.log' file for details
```

### Relevant files

Feb-20 16:04:04.226 [main] ERROR n.validation.JsonSchemaValidator - Failed to load the meta schema:
The used schema draft (http://json-schema.org/draft-07/schema) is not correct, please use "https://json-schema.org/draft/2020-12/schema" instead.
See here for more information: https://json-schema.org/specification#migrating-from-older-drafts

Feb-20 16:04:04.229 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
  Script_3b23d717def1bedf: /home/webadm/.nextflow/assets/nf-core/sarek/main.nf
Feb-20 16:04:04.229 [main] DEBUG nextflow.Session - Session aborted -- Cause: nextflow.validation.SchemaValidationException: 
Feb-20 16:04:04.241 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.validation.SchemaValidationException: 
	at nextflow.validation.JsonSchemaValidator.validateObject(JsonSchemaValidator.groovy:43)
	at nextflow.validation.JsonSchemaValidator.validate(JsonSchemaValidator.groovy:109)
	at nextflow.validation.SchemaValidator.validateParameters(SchemaValidator.groovy:344)
	at nextflow.validation.SchemaValidator.validateParameters(SchemaValidator.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at nextflow.script.FunctionDef.invoke_a(FunctionDef.groovy:64)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
	at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:102)
	at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at nextflow.script.BaseScript.invokeMethod(BaseScript.groovy:140)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at Script_3b23d717def1bedf.runScript(Script_3b23d717def1bedf:92)
	at nextflow.script.BaseScript.run0(BaseScript.groovy:144)
	at nextflow.script.BaseScript.run(BaseScript.groovy:192)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:236)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:242)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:137)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:372)
	at nextflow.cli.Launcher.run(Launcher.groovy:500)
	at nextflow.cli.Launcher.main(Launcher.groovy:672)

### System information

latest, ubuntu 22, local

**Comment by FriederikeHanssen** [comment]
Hey! Can you try pinning the nf-validation version with adding this to a config and then add the file with  `-c` to your command:

```
plugins {
    id 'nf-validation@1.1.3'
}
```

**Comment by ewels** [comment]
We just reverted the plugin release, this problem should now resolve itself.

We will release another day, but try to ensure that all pipelines are properly prepared before doing so.

Shout if anyone is still hitting this after I post this message.

**Comment by ewels** [comment]
x-ref: https://github.com/nextflow-io/plugins/pull/66
