### ISSUE TITLE
SPRING format support

### ISSUE THREAD

**Issue by kunstner** [nf-core/sarek#1418]
### Description of feature

Hi,
we are storing our sequencing data in spring-format to reduce disc space. Do you plan to support spring-format besides fastq for sequencing reads in the near future?
Best,
 Axel

**Comment by kunstner** [comment]
Yes, basically it should just perform the conversion to fastq (gzip-ed) and next sarek starts as usual.

Here my outline:

The basic idea would be to use spring compressed files (see below for references) in the sample sheet.

The sarek workflow would take the spring files, performs the decompression and runs the sarek pipeline as usual. 

./spring -d -i file.spring -o file_1.fastq.gz file_2.fastq.gz -g

Publication
https://academic.oup.com/bioinformatics/article/35/15/2674/5232998

github
https://github.com/shubhamchandak94/Spring

**Comment by FriederikeHanssen** [comment]
This has been merged in. Let us know if you run into any problems.
