### ISSUE TITLE
vep_cache versions should probably not be integers

### ISSUE THREAD

**Issue by leipzig** [nf-core/sarek#1454]
### Description of the bug

Hello,
I am still seeing the `vep_cache_version` as naked integers in this config
https://github.com/nf-core/sarek/blob/master/conf/igenomes.config

This has caused [problems in the past](https://github.com/nf-core/sarek/issues/518), not to mention there are often point releases in vep e.g. [110.1](https://github.com/Ensembl/ensembl-vep/releases/tag/release%2F110.1)

### Relevant files

https://github.com/nf-core/sarek/blob/master/conf/igenomes.config

**Comment by FriederikeHanssen** [comment]
This was fixed in #1471 . Let's re-open if the issue persists
