### ISSUE TITLE
bwa index

### ISSUE THREAD

**Issue by fan040** [nf-core/sarek#1476]
### Description of feature

My reference genome is very large and it will take a long time for bwa to set up the index. I hope you can consider adding a parameter to specify the index file.

**Comment by maxulysse** [comment]
https://nf-co.re/sarek/3.4.0/parameters#bwa

Check in the [Reference genome options](https://nf-co.re/sarek/3.4.0/parameters#reference-genome-options).
You might have to check the `Show hidden` button on the right hand sign to show all params properly

**Comment by fan040** [comment]
I have seen the parameters, thank you for your reply
