### ISSUE TITLE
Create Tests for Mutect2

### ISSUE THREAD

**Issue by lescai** [nf-core/sarek#148]
As agreed with @MaxUlysse @cgpu opening this issue to discuss how to perform larger scale testing for Mutect2, and make sure it runs as expected.
We can discuss here what datasets to use, where to place the data and how to run the tests.

**Comment by cgpu** [comment]
Some questions that we will might to answer:

- Will Mutect2 run with the current small reference without complaining?
- Are we testing only one part of one chromosome?
- Are we subsampling with something like [`seqtk`](https://github.com/lh3/seqtk) to keep very few reads from all chromosomes?
- Can we subsample with something like [`gatk SelectVariants`](https://gatkforums.broadinstitute.org/gatk/discussion/2441/can-selectvariants-be-used-to-limit-vcf-files-by-interval-list) + test specific intervals list the resource vcf files needed?

**Comment by MaxUlysse** [comment]
@chelauk this issue might be interesting for you as well

**Comment by chelauk** [comment]
Mutect2 doesn't work at the moment with the tiny test dataset.  It needs a compatible germline resource. I am trying to create  one

**Comment by chelauk** [comment]
I am trying to get sarek to work with the test dataset:
I edited the gnomAD.r2.1.1.GRCh38.PASS.AC.AF.only.vcf.gz resource to contain only those variants in the small.intervals  file.
This meant that gatk Mutect2 runs successfully
gatk GatherPileupSummaries also runs
but with the test dataset it generates an empty table
This breaks the CalculateContamination step with an i/o problem.  I was wondering how to get round this.  We could add a test and ignore the filtration steps but that means that we don't test the filtration steps.

**Comment by maxulysse** [comment]
Done by: https://github.com/nf-core/test-datasets/pull/340
