### ISSUE TITLE
Add script for the CreateSomaticPanelOfNormals workflow

### ISSUE THREAD

**Issue by cgpu** [nf-core/sarek#149]
This will enable users to create their own PON that is specific to their samples processing workflow. Quoting the relevant GATK article:

>  _their main purpose [of PON resources] is to capture recurrent technical artifacts in order to improve the results of the variant calling analysis._

- [ ] Discuss how to make available the **AF-only gnomAD** resource (it's not quite the same as [`genomes.genome.germlineResource`](https://github.com/nf-core/sarek/blob/b952fe2b3fcd3541237c9f4a9f27e1852f537967/conf/igenomes.config#L23), I'll have to check this further)
- [ ] Replace [`bam.simpleName`](https://github.com/nf-core/sarek/blob/b7a1a4d9b27e0bc92c345de5a363f6399f5fe95b/create_pon.nf#L188) with a variable that holds the extracted sample name from the respective normal bam
- [ ] Replace clunky old bash with groovy [here](https://github.com/nf-core/sarek/blob/b7a1a4d9b27e0bc92c345de5a363f6399f5fe95b/create_pon.nf#L214-L223) probably remove collect from input declaration and implement the multi vcf definition like:

```groovy
 ${inputVcfCreateGenomicsDB.collect {"-V $it "}.sort().join()}
```

- [ ] Add input parameter docs

- [ ] Make/Find tiny adequate bam files for testing

**Comment by DrJCampbell** [comment]
Having just created a PON vcfmanually - this would be a really useful feature for the future.

**Comment by cgpu** [comment]
@DrJCampbell (cc' @MaxUlysse) noted. I started this during a previous nf-core hackathon but never got to finalise. I will allocate some time during my August vacation from my day job to make this available to everyone. Thanks for mentioning it, you reminded me that this might prove useful to others.

**Comment by maxulysse** [comment]
closed by https://github.com/nf-core/modules/pull/1044
