### ISSUE TITLE
Sarek 3.4.1 GATK4_HAPLOTYPECALLER will only run first intervals. Join mismatch error when run the second

### ISSUE THREAD

**Issue by bnjvrjnke** [nf-core/sarek#1495]
### Description of the bug

If run GATK4_HAPLOTYPECALLER in 3.4.1, you will get only first one intervals GVCF. Error will occur when process the second intervals GVCF when run GATK4_HAPLOTYPECALLER:
```
Join mismatch for the following entries: 
- key=[patient:sample01, sample: sample01, sex:XX, status:0, n_fastq:24, data_type:cram, id:sample01, interval_name:chrX_37285838-49348394, num_intervals:21, variantcaller:haplotypecaller] values=[/work/7f/fd03e6705a9ffa0f345db370a3ba8b/sample01.recal.cram, /work/a9/f29835a7281a84dded8bec1f5dedcf/sample01.recal.cram.crai, /work/da/bd30415f8dc9e4cde745fd7ca13282/chrX_37285838-49348394.bed, []] 
- key=[patient:sample02, sample: sample02, sex:XY, status:0, n_fastq:12, data_type:cram, id:sample02, interval_name:chr18_47019913-54536574, num_intervals:21, variantcaller:haplotypecaller] values=[/work/76/5a715b39c519cb83d8c3349d8b8fa2/sample02.recal.cram, //work/6b/f73a30e3bbf9f8a824ae1c59c9022d/sample02.recal.cram.crai, /work/da/bd30415f8dc9e4cde745fd7ca13282/chr18_47019913-54536574.bed, []] 
(more omitted)
```
This error don't occur in 3.4.0, I think it related to the change of GATK4_HAPLOTYPECALLER parameter structure.
3.4.1:
https://github.com/nf-core/sarek/blob/ea88402912c329b4fd234ad07294ce05bbd2590c/subworkflows/local/bam_variant_calling_haplotypecaller/main.nf#L33-L39
https://github.com/nf-core/sarek/blob/ea88402912c329b4fd234ad07294ce05bbd2590c/modules/nf-core/gatk4/haplotypecaller/main.nf#L10-L16
3.4.0
https://github.com/nf-core/sarek/blob/9d15b23ae4ed3cba6eeb95244df016391965b005/modules/nf-core/gatk4/haplotypecaller/main.nf#L10-L16
I change 3.4.1 code to the below, solving the join mismatch error and process all intervals GVCF
```
GATK4_HAPLOTYPECALLER(
        cram_intervals,
        fasta.first(),
        fasta_fai.first(),
        dict.first(),
        dbsnp.first(),
        dbsnp_tbi.first())
```

**Comment by asp8200** [comment]
thanks for reporting. The issue should be fixed by this [PR](https://github.com/nf-core/sarek/pull/1488) which has been merged to `dev`-branch.

Can you confirm that your nf-command runs successfully on the `dev`-branch?

**Comment by ollieeknight** [comment]
I've also run into similar problems, I'm getting identical error messages, but also in markduplicates. I've run it on dev with `nextflow run nf-core/sarek -r dev` and have the exact same problem :(

**Comment by asp8200** [comment]
> I've also run into similar problems, I'm getting identical error messages, but also in markduplicates. I've run it on dev with `nextflow run nf-core/sarek -r dev` and have the exact same problem :(

Are you sure you're running the latest commit on the `dev`-branch?

**Comment by maxulysse** [comment]
Can you try again with -r dev -latest ?

**Comment by ollieeknight** [comment]
that works for me, @maxulysse! thanks

**Comment by maxulysse** [comment]
we just release [3.4.2](https://github.com/nf-core/sarek/releases/tag/3.4.2) that is fixing all that
