### ISSUE TITLE
primer trimming

### ISSUE THREAD

**Issue by aihualin** [nf-core/sarek#1511]
### Description of feature

Hi, should i do the primer trimming before i run Sarek?
for example, 
cutadapt -a <primer_sequence> -o <output_file.fastq> <input_file.fastq>

Thank you,
All the best
Lin

**Comment by maxulysse** [comment]
Checkout the https://nf-co.re/sarek/latest/parameters#fastq-preprocessing section.
I would recommend to click on the show hidden on the right hand side.
Sarek should be able to handle this for you using Fastp

**Comment by FriederikeHanssen** [comment]
I will close this as answered by Maxime. IF you have further questions on trimming adapters with fastP, feel free to reopen
