### ISSUE TITLE
Missing file in iGenomes

### ISSUE THREAD

**Issue by ekushele** [nf-core/sarek#1515]
### Description of the bug

Hi,

I'm trying to run sarek, and I'm getting the following error:

```

ERROR ~ Error executing process > 'NFCORE_SAREK:SAREK:CRAM_SAMPLEQC:BAM_NGSCHECKMATE:BCFTOOLS_MPILEUP (1)'

Caused by:
  Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: DWAFHYDZD0HB3HXB; S3 Extended Request ID: 9UnG6G4ZvIrq/mijFQxFBq5uJUwvZXWga5ogNegCaF2yXEQ4UgMlcuMwhj8udwpksh2uh3JsTg0=; Proxy: null)


 -- Check '.nextflow.log' file for details
-[nf-core/sarek] Sent summary e-mail to mazaltov@hadassah.org.il (mail)-
-[nf-core/sarek] Pipeline completed with errors-
WARN: Killing running tasks (2)

```

### Command used and terminal output

```console
$ nextflow run -resume -params-file OV3_params.yaml  -profile singularity nf-core/sarek

where params file is: 

input: OV3_sample_sheet.csv
outdir: output
step: variant_calling
wes: true
tools: 'mutect2,vep'
genome: GATK.GRCh37
save_reference: true
download_cache: true
```
```


### Relevant files

_No response_

### System information

nextflow version:  23.04.4
nf-core/sarek: 3.4.1

**Comment by logust79** [comment]
I'm hitting the same error in mpileup.

**Comment by maxulysse** [comment]
That sounds like some credentials issue with AWS,
Can you try to unset your AWS credentials prior running the analysis and it should be fine.
Otherwise, adding this to a `custom.config` file, and supplying it with `-c custom.config` should do the trick:
```
aws {
    client {
        anonymous = true
    }
}
```

**Comment by logust79** [comment]
I had the anonymous setting at the time of the error. I am going to try with GRCh38 and see what happens.Sent from my iPhoneOn 8 May 2024, at 13:45, Maxime U Garcia ***@***.***> wrote:﻿
That sounds like some credentials issue with AWS,
Can you try to unset your AWS credentials prior running the analysis and it should be fine.
Otherwise, adding this to a custom.config file, and supplying it with -c custom.config should do the trick:
aws {
    client {
        anonymous = true
    }
}

**Comment by logust79** [comment]
I just finished a run on 'GRCh38' and it went through without this issue.

**Comment by ekushele** [comment]
@maxulysse thank you, but it didn't work..
Do you have another solution?

**Comment by logust79** [comment]
I ran it with and without AWS credentials, running into the same issue whatsoever. `env | grep AWS` confirmed nothing is set. I think some S3 files specific to GRCh37 are out of reach.

**Comment by maxulysse** [comment]
Can you try again?

**Comment by logust79** [comment]
> Can you try again?

Tried and worked without aws credentials for GRCh37. Thanks for fixing the S3 file access :)
