### ISSUE TITLE
don't use fastp and fastqc

### ISSUE THREAD

**Issue by fan040** [nf-core/sarek#1531]
### Description of feature

I would like to ask whether it is possible to directly talk about bwa comparison of fastq files without going through quality control steps

**Comment by maxulysse** [comment]
Adding `--skip_tools fastp,fastqc` to your command should do the trick

**Comment by fan040** [comment]
I used these two parameters and this error occurred

ERROR ~ Cannot invoke method getName() on null object

 -- Check script '/cluster/home/fanrong/biosofts/nextflow/nf-core/nf-core-sarek/3_4_0/./workflows/../subworkflows/local/channel_variant_calling_create_csv/main.nf' at line: 15 or see '.nextflow.log' file for more details

1 //
      2 // CHANNEL_VARIANT_CALLING_CREATE_CSV
      3 //
      4 
      5 workflow CHANNEL_VARIANT_CALLING_CREATE_CSV {
      6     take:
      7         vcf_to_annotate // channel: [mandatory] meta, vcf
      8 
      9     main:
     10         // Creating csv files to restart from this step
     11         vcf_to_annotate.collectFile(keepHeader: true, skip: 1,sort: true, storeDir: "${params.outdir}/csv"){ meta, vcf ->
     12             patient       = meta.patient
     13             sample        = meta.id
     14             variantcaller = meta.variantcaller
     15             vcf = "${params.outdir}/variant_calling/${variantcaller}/${meta.id}/${vcf.getName()}"
     16             ["variantcalled.csv", "patient,sample,variantcaller,vcf\n${patient},${sample},${variantcaller},${vcf}\n"]
     17         }
     18 }

**Comment by fan040** [comment]
And I found that the addition of these two parameters did not cause the fastp software to not run, do I need to modify the configuration file? Looking forward to your reply

**Comment by maxulysse** [comment]
Sorry, was on my phone, it should be `--skip_tools fastqc --split_fastq 0`.
Can you share your config file and your samplesheet?

**Comment by fan040** [comment]
process {
  executor = 'slurm'
  queue = 'cpu'
  clusterOptions = '--exclude=node10'
  // queue = { task.time <= 2.h ? 'nodeall' : task.time <= 24.h ? 'fat': 'cpu2' }
  // queue = { task.time <= 2.h ? 'cpu2' : task.time <= 24.h ? 'cpu2': 'cpu2' }
  maxRetries = 2
  beforeScript = 'export PATH=/usr/bin:${PATH}'
  // beforeScript = 'module load software/apptainer/v1.1.5'
  // beforeScript = 'mkdir -p ./tmp/ && export TMPDIR=./tmp/'
  withName: 'BWAMEM1_MEM|BWAMEM2_MEM' {
      cpus = 16
      memory = 100.GB
      errorStrategy = { task.exitStatus in 137..140 ? 'retry' : 'terminate' }
      maxRetries = 2
  }
  withName: 'FASTP' {
      ext.when = {false}
  }
  withName: 'FASTQC' {
      ext.when = {false}
  }
}

**Comment by fan040** [comment]
patient,sex,sample,lane,fastq_1,fastq_2
D,XX,D900002,D900002_L1,/public/home/fanrong/projects/AK58/test/00_raw_data/D900002_1.fastq.gz,/public/home/fanrong/projects/AK58/test/00_raw_data/D900002_2.fastq.gz
D,XX,D900005,D900005_L1,/public/home/fanrong/projects/AK58/test/00_raw_data/D900005_1.fastq.gz,/public/home/fanrong/projects/AK58/test/00_raw_data/D900005_2.fastq.gz
D,XX,D900006,D900006_L1,/public/home/fanrong/projects/AK58/test/00_raw_data/D900006_1.fastq.gz,/public/home/fanrong/projects/AK58/test/00_raw_data/D900006_2.fastq.gz
D,XX,D900035,D900035_L1,/public/home/fanrong/projects/AK58/test/00_raw_data/D900035_1.fastq.gz,/public/home/fanrong/projects/AK58/test/00_raw_data/D900035_2.fastq.gz
D,XX,D900036,D900036_L1,/public/home/fanrong/projects/AK58/test/00_raw_data/D900036_1.fastq.gz,/public/home/fanrong/projects/AK58/test/00_raw_data/D900036_2.fastq.gz

**Comment by fan040** [comment]
--skip_tools fastqc --split_fastq 0 Hi, I used these two parameters, but fastp is still running.
![image](https://github.com/nf-core/sarek/assets/166574153/c3aa0769-4df2-4881-9937-d3605ba4d44b)
This is my command :
nextflow run /cluster/home/fanrong/biosofts/nextflow/nf-core/nf-core-sarek/3_4_0 -profile zwnj_2022 -offline --input /public/home/fanrong/projects/AK58/test/00_raw_data/samplesheet.csv --outdir ./result --step mapping --fasta /public/home/fanrong/projects/AK58/fasta/wheat_AK58v4MP.genome_part.fa --fasta_fai /public/home/fanrong/projects/AK58/fasta/wheat_AK58v4MP.genome_part.fa.fai --dict /public/home/fanrong/projects/AK58/fasta/wheat_AK58v4MP.genome_part.dict --trim_fastq --aligner bwa-mem2 --max_cpus 16 --max_memory 100.GB --max_time 720.h --tools haplotypecaller --save_mapped --bwamem2 /cluster/home/fanrong/work_lei/BSA/01_ZG/02_mapping_3/work/33/706371da5349b7b033e07f32ae9d58/bwamem2 --igenomes_ignore --genome null --skip_tools baserecalibrator haplotypecaller_filter fastqc --joint_germline --split_fastq 0
