### ISSUE TITLE
Nextflow docker: Error response from daemon

### ISSUE THREAD

**Issue by C2i-PeterChung** [nf-core/sarek#1532]
### Description of the bug

hello I have an error when I ran the nextflow sarek pipeline:

`nextflow -bg run nf-core/sarek -r 3.4.0 -params-file params_samplesheet_F52_3.json -profile docker &

Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 125.

The full error message was:

Error executing process > 'NFCORE_SAREK:SAREK:BAM_BASERECALIBRATOR:GATK4_BASERECALIBRATOR (120236)'

Caused by:
  Process `NFCORE_SAREK:SAREK:BAM_BASERECALIBRATOR:GATK4_BASERECALIBRATOR (120236)` terminated with an error exit status 
(125)

Command executed:

  gatk --java-options "-Xmx3276M -XX:-UsePerfData" \
      BaseRecalibrator  \
      --input 120236.converted.cram \
      --output 120236_chr1_122026460-124977944.recal.table \
      --reference Homo_sapiens_assembly38.fasta \
      --intervals chr1_122026460-124977944.bed \
      --known-sites dbsnp_146.hg38.vcf.gz --known-sites Mills_and_1000G_gold_standard.indels.hg38.vcf.gz --known-sites 
Homo_sapiens_assembly38.known_indels.vcf.gz \
      --tmp-dir . \

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SAREK:SAREK:BAM_BASERECALIBRATOR:GATK4_BASERECALIBRATOR":
      gatk4: $(echo $(gatk --version 2>&1) | sed 's/^.*(GATK) v//; s/ .*$//')
  END_VERSIONS

Command exit status:
  125

Command output:
  (empty)

Command error:
  docker: Error response from daemon: failed to create endpoint nxf-02MAUnCuusW7YHwLnsBbzWSA on network bridge: failed to add the host 
(vethe58dde8) <=> sandbox (veth83d3dac) pair interfaces: cannot allocate memory.
  time="2024-05-21T11:53:49+08:00" level=error msg="error waiting for container: context canceled"

Work dir:
  /data/hhgphk/runF52/work/00/8748af7adb7ffb4cbacc79d0fedbca

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh``

I  tried to add the memory limit to docker file:

```
sudo nano /etc/default/docker
DOCKER_OPTS="--default-memory-limit=32768m --default-memory-swap=65536m"
```
My docker and nextflow version: 

But it still does not work. I am new to nextflow, can anyone give me advice. Thanks.

### System information

Docker version 20.10.24, build 297e128
  
N E X T F L O W
  version 23.10.0 build 5889
  created 15-10-2023 15:07 UTC (23:07 HKST)
  cite doi:10.1038/nbt.3820
  http://nextflow.io

**Comment by asp8200** [comment]
Hi @C2i-PeterChung. I would suggest that you come on over on Slack and discuss this problem with us.

Did you manage to get the profiles `test` and `test_full` running on your setup? 

The memory-requirements for the process `GATK4_BASERECALIBRATOR` can be set in a config, but as a first step you might just try adding the option `--max_memory '123.GB'` to your nf-command. (Obviously, just replace `123` with whatever memory you have available.)

**Comment by FriederikeHanssen** [comment]
Is this still an issue?

**Comment by FriederikeHanssen** [comment]
This looks like it is a similar issue reported in #1519 . I will close this one and it can be tracked further in the other issue
