### ISSUE TITLE
memory limit 

### ISSUE THREAD

**Issue by fan040** [nf-core/sarek#1543]
### Description of the bug

I would like to ask whether this configuration can dynamically adjust resources. I have many files and a large reference genome, which consumes more resources, but my initial setting resources can not be too large, so I want to set a dynamic adjustment resource configuration for all software

This is my settting:
![image](https://github.com/nf-core/sarek/assets/166574153/3b4835c0-344b-4ea7-b88b-87ed7fffe7f6)
This is my error：
INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
slurmstepd: error: Job 518023 exceeded memory limit (4339056 > 4194304), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 518023 ON node1 CANCELLED AT 2024-05-27T09:01:58 ***

**Comment by maxulysse** [comment]
I'm guessing issue is with `4339056 > 4194304`
I'd make sure `max_memory` correspond to 4194304

**Comment by fan040** [comment]
Hello, I know this problem, so I want to set dynamic adjustment resources, but it seems that my Settings above can not be dynamically adjusted, I would like to ask you to help me check. Because I can't set up a large resource at the beginning, my service period is not supported.
