### ISSUE TITLE
single sample haplotypecaller with no dbsnp causes error because of missing dbsnp_tbi

### ISSUE THREAD

**Issue by cmatKhan** [nf-core/sarek#1550]
### Description of the bug

Using haplotypecaller without passing a `--dbsnp`, the following error is raised:

```
ERROR ~ Cannot get property 'baseName' on null object

 -- Check script '/scratch/mblab/chasem/nextflow/assets/nf-core/sarek/./workflows/sarek/../../subworkflows/local/bam_variant_calling_germline_all/main.nf' at line: 132 or see '.nextflow.log' file for more details
ERROR ~ Cannot get property 'baseName' on null object

 -- Check script '/scratch/mblab/chasem/nextflow/assets/nf-core/sarek/./workflows/sarek/../../subworkflows/local/bam_variant_calling_germline_all/main.nf' at line: 133 or see '.nextflow.log' file for more details
-[nf-core/sarek] Pipeline completed with errors-
```
If I replace this line:

https://github.com/nf-core/sarek/blob/b5b766d3b4ac89864f2fa07441cdc8844e70a79e/subworkflows/local/bam_variant_calling_germline_all/main.nf#L133

with

```
[[:], []]
```
the subworkflow completes without error.

Sorry for the lack of a reproducible example for the time being -- will try to make one early next week.

### Command used and terminal output

```console
nextflow run nf-core/sarek -profile singularity -params-file bam_input_params.json -c /scratch/mblab/chasem/bsa/wustl_htcf.config -c kn99.config --input samplesheets/run_6991.csv --outdir run_6991_results
```

### Relevant files

I tried this with `haplotypecaller_filter` in "skip_tools", also, with the same result.

```json
{
    "tools": "haplotypecaller,manta,cnvkit,snpeff",
    "skip_tools": "baserecalibrator",
    "joint_germline": false,
    "genome": "",
    "dbsnp_vqsr": false,
    "fasta": "\/ref\/mblab\/data\/KN99\/KN99_genome_fungidb.fasta",
    "fasta_fai": "\/ref\/mblab\/data\/KN99\/KN99_genome_fungidb.fasta.fai",
    "known_indels_vqsr": false,
    "known_snps": false,
    "known_snps_tbi": false,
    "known_snps_vqsr": false,
    "ngscheckmate_bed": false,
    "snpeff_db": "1",
    "snpeff_genome": "ASM221672v1",
    "igenomes_ignore": true,
    "vep_cache": "",
    "snpeff_cache": "\/ref\/mblab\/data\/KN99\/snpeff_db",
    "split_fastq": 1000000,
    "nucleotides_per_second": 10000,
    "save_output_as_bam": true,
    "step": "prepare_recalibration"
}

```

### System information

Nextflow: 24.04.2
Hardware: HPC
Executor: SLURM
Container engine: Singularityce
OS: Rocky linux v8.9
nf-core/sarek: 3.4.2

**Comment by FriederikeHanssen** [comment]
Thanks for finding this. Added it to the 3.5 milestones

**Comment by drowsygoat** [comment]
I can confirm the same problem while using a "non-standard" genome with no known reference variants.
 nf-core/sarek v3.4.3-ge92242e
engine: singularity
nf version 24.04.4

**Comment by cmatKhan** [comment]
you have to edit the code on your local version for the moment until it gets corrected and released, but the correction i described in the original post works. Depending on what options you have set, there are a couple other spots that the same correction needs to be made.
