### ISSUE TITLE
SarekGUI: Interface Graphique Intuitive pour l'Exécution des Pipelines nf-core Sarek

### ISSUE THREAD

**Issue by Sadiki-Noureddine** [nf-core/sarek#1565]
### Description of feature

 I'm interested in developing an web application with a graphical user interface (GUI) to streamline the use of nf-core pipelines(sarek) for biologists. The goal is to create a user-friendly tool that would allow users to easily specify analysis parameters, manage input and output data, and track the progress of analyses, all without needing to use the command line or master technical aspects of computing. If you have ideas on how to design and develop such an application, or if you have practical advice for approaching this project, I would greatly appreciate hearing them. Thanks in advance for your help!

**Comment by asp8200** [comment]
Sounds like what your looking for is the Seqera Platform or LifeBit.

**Comment by maxulysse** [comment]
As @asp8200 mentioned already, I would personally check the [Seqera platform](https://cloud.seqera.io/).
The [nf-core launch](https://nf-co.re/docs/nf-core-tools/pipelines/launch) command is also worth mentioning.
Another approach would be [nf-shard](https://github.com/AugustDev/nf-shard).

All the params for all nf-core pipelines are set up using the nextflow_schema.json, and all these tools, and other make great use of that.
I hope this could be of help to you.

**Comment by Sadiki-Noureddine** [comment]
@maxulysse @asp8200
 Thank you for the information. I appreciate the suggestion
