### ISSUE TITLE
snpeff capitalization in tower.yml

### ISSUE THREAD

**Issue by cmatKhan** [nf-core/sarek#1569]
The snpEff reports were not present in the 'reports' section of platform until I changed the capitalization of `snpEff` to all lower case to match the subdir name

https://github.com/nf-core/sarek/blob/b5b766d3b4ac89864f2fa07441cdc8844e70a79e/tower.yml#L56

https://github.com/nf-core/sarek/blob/b5b766d3b4ac89864f2fa07441cdc8844e70a79e/tower.yml#L54

**Comment by maxulysse** [comment]
good cath
