### ISSUE TITLE
ERROR ~ Error executing process > 'NFCORE_SAREK:PREPARE_GENOME:BWAMEM1_INDEX'

### ISSUE THREAD

**Issue by YasirKusay** [nf-core/sarek#1601]
### Description of the bug

I have got the following error:
```
ERROR ~ Error executing process > 'NFCORE_SAREK:PREPARE_GENOME:BWAMEM1_INDEX'

Caused by:
  The target server failed to respond
```

In the log file, I saw this error: 

```S3 download directory: s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/BWAIndex/version0.6.0 interrupted```

I can see from the staging file that there are version0.6.0 files therre but I am not sure what is causing the issue. 

### Command used and terminal output

```console
nextflow run nf-core/sarek -r 3.4.2 -profile docker --input samplesheet.csv --outdir results --genome NCBI.GRCh38 --skip_tools baserecalibrator
```

**Comment by FriederikeHanssen** [comment]
Sounds like there was a network issue with the index download. Generally it is easier and faster to pre-download the indices that you need from here: https://ewels.github.io/AWS-iGenomes/ selecting the genome version that you want and supplying the path to [`--igenomes_path` ](https://nf-co.re/sarek/3.4.2/parameters/#igenomes_base). This is also typically faster as the workflow doesn't repeatedly download the same data. 

Just as a warning the NCBI one doesn't have a lot of the reference files and some steps may not work.

**Comment by YasirKusay** [comment]
Is there a command to save the downloaded items as well so I can re-use them in the future, (I couldn't find a command like that).

**Comment by FriederikeHanssen** [comment]
Hey! For aws igenomes there is a `aws sync` command generated for you at the bottom of the homepage and you can point to the rot path then here: https://nf-co.re/sarek/3.4.2/parameters/#igenomes_base (sorry I misspelled the parameter above).
<img width="1283" alt="Screenshot 2024-07-24 at 13 35 34" src="https://github.com/user-attachments/assets/57a0c264-e707-4837-9b56-d25f7d72284a">
