### ISSUE TITLE
Mutect2 - PON - GRCh38 - Question

### ISSUE THREAD

**Issue by jbague** [nf-core/sarek#1603]
### Description of the bug

Hi,
I'm writing to ask about the PON panel when executing Mutect2 in tumor-only mode. If I’m using the GATK.GRCh38 genome, do I need to create a PON, or will the pipeline download it? I ask because I don’t have enough samples to create one. I've seen messages stating that I need to create one before using the pipeline, while others suggest this genome provides one (though the best way is to create one with your own normal samples).
Thanks for your support!

**Comment by FriederikeHanssen** [comment]
Hey! By default it will use a PON that comes from the GATK Reference bundle. As you stated best to create your own but you can use that one in the meantime :)
