### ISSUE TITLE
Allow specifying `--fasta` for VEP

### ISSUE THREAD

**Issue by lbeltrame** [nf-core/sarek#1607]
### Description of feature

This is required to allow generation of HGVSc and HGVSp nomenclature when running offline (which is the default for sarek).

From the VEP docs:

> To generate HGVS identifiers when using [--cache](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_cache) or [--offline](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_offline) you must use a FASTA file and [--fasta](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fasta).

**Comment by lbeltrame** [comment]
The option is already there, just not very visible.

**Comment by FriederikeHanssen** [comment]
maybe instead remove it form the hidden options?
