### ISSUE TITLE
Misleading info on Documentation

### ISSUE THREAD

**Issue by bounlu** [nf-core/sarek#1621]
The [doc](https://nf-co.re/sarek/docs/usage/#specify-the-cache-location) says the cache location for VEP should be:
`${vep_species}/${vep_genome}_${vep_cache_version}`

But the given example shows it in a different way:
```
/data/
├─ vep_cache/
│  ├─ homo_sapiens/
│  │  ├─ 110_GRCh38/
```

Which one is correct?

**Comment by asp8200** [comment]
Perhaps somewhat related to [this](https://github.com/nf-core/sarek/issues/1260#issuecomment-2288411285)?

**Comment by bounlu** [comment]
@asp8200 Yes, it still needs to be resolved.
