### ISSUE TITLE
Challenge with VEP Annotation in Offline Mode - --hgvs Disabled Due to Missing FASTA File

### ISSUE THREAD

**Issue by chumawinnie** [nf-core/sarek#1626]

**Comment by maxulysse** [comment]
Have you checked the https://nf-co.re/sarek/dev/parameters/#vep_include_fasta params?

**Comment by chumawinnie** [comment]
> Have you checked the https://nf-co.re/sarek/dev/parameters/#vep_include_fasta params?


Hello,

I tried running the pipeline, but it didn’t resolve the issue. In fact, it crashes the program immediately. Below is the complete command I used:

```bash
nextflow run nf-core/sarek -profile docker \
  --input samplesheet.csv \
  --outdir /home/obiorach/test-work-sarek/WES-test-result \
  --genome hg19 \
  --dbsnp /path/to/dbsnp_138.hg19.vcf.gz \
  --known_indels /path/to/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz \
  --max_cpus 20 \
  --max_memory '30 GB' \
  --wes \
  --intervals /path/to/HyperExomeV2_primary_targets.hg19.bed \
  --tools mutect2,strelka,vep \
  --pon /path/to/Mutect2-exome-panel_vcf.vcf.gz \
  --germline_resource /path/to/renamed_gnomad.vcf.gz \
  --vep_cache /home/obiorach/datasets/auxiliary_files_and_databases/VEP_cache \
  --vep_species homo_sapiens \
  --vep_genome GRCh37 \
  --vep_cache_version 106 \
  --vep_include_fasta \
  -c custom.config \
  -resume
```

Is there anything I might be missing or doing incorrectly?

---

**Comment by FriederikeHanssen** [comment]
What is the error message?

**Comment by chumawinnie** [comment]
> What is the error message?
![Screenshot from 2024-08-19 16-32-05](https://github.com/user-attachments/assets/6f11998e-e1ad-4220-ac2d-74c69ef6853c)

After adding the line above, I encountered an error. However, if I remove the line, the pipeline continues to run but might eventually crash, potentially due to the issue shown in the picture above. How can I resolve this? My pipeline appears to be well-structured, and there is sufficient space on my server.

**Comment by chumawinnie** [comment]
![359060234-3ce74cef-d742-4193-bb35-b3b47b96eed3](https://github.com/user-attachments/assets/d0951d41-a171-4ba9-9093-f9f3b9a5cf62)
here is the first error message

**Comment by chumawinnie** [comment]
I’m trying to understand the root cause of the issue with the program. The pipeline is well-structured and has successfully produced output in the past. However, I’ve noticed that certain processes, like Mutect2 variant calling and VEP annotation, take a considerable amount of time to complete, and eventually, the program seems to get stuck. When I checked the performance using the htop command, I observed that the CPU usage had dropped to 0.0.

To give you some background, the dataset I’m working with has been sequenced multiple times and then merged, so it’s quite large. Please review the pipeline to see if there’s any parameter I might be missing, although I’m not sure if there is. I suspect that Mutect2 and VEP annotation might be the bottlenecks. Do you have any suggestions for resolving this issue?

**Comment by maxulysse** [comment]
I think this is OK to close.
Can you reopen if you still have issues?
