### ISSUE TITLE
Can BAM files be set as the input for the analysis?

### ISSUE THREAD

**Issue by martinyanglyu** [nf-core/sarek#1632]
### Description of feature

I have handreds of BAM files for WGS data. I love your pipeline. So can you please add the option to set BAM files as input  also?
Thanks

**Comment by asp8200** [comment]
The pipeline can take BAM-files as input:

https://nf-co.re/sarek/3.4.3/docs/usage/#overview-samplesheet-columns

I guess if you're using BAM-files as input for the pipeline, then you wanna set the option `--option` to `variant_calling`:

https://nf-co.re/sarek/3.4.3/docs/usage/#start-with-variant-calling---step-variant_calling

**Comment by FriederikeHanssen** [comment]
you can use BAM file as input and re-align (`--step mapping`), or start from duplicate marking (`--step markduplicates`), preparing the recalibration table (`--step prepare_recalibration`), recalibrate (`--step recalibrate`), or variant calling (`--step variant_calling`) 

The pipeline will start at the earliest step specified and then run as far as it can. (So no need to specify several steps) 

To make sure variant calling is done, you need to select a tool with `--tools` . 

For visualisation of which inputs are accepted where also check the metro map at https://nf-co.re/sarek/3.4.3/#pipeline-summary

**Comment by martinyanglyu** [comment]
Thank you very much.

**Comment by FriederikeHanssen** [comment]
Has this answered all your questions? In that case let's close this one and re-open if necessary

**Comment by martinyanglyu** [comment]
Yes. Thanks.
Yang

From: Friederike Hanssen ***@***.***>
Date: Friday, August 30, 2024 at 10:06 AM
To: nf-core/sarek ***@***.***>
Cc: Yang Lyu ***@***.***>, Author ***@***.***>
Subject: Re: [nf-core/sarek] Can BAM files be set as the input for the analysis? (Issue #1632)

Has this answered all your questions? In that case let's close this one and re-open if necessary
