### ISSUE TITLE
For input string: "status"

### ISSUE THREAD

**Issue by mkinnaman** [nf-core/sarek#165]
Hi Sarek Team,

I am having a little trouble getting off the ground here. I have sarek installed in the cluster with a conda setup. I would like to run on some already aligned BAM Files from a targeted sequencing panel.

Whenever I run I keep on getting this in the error report:
`For input string: "status"`
My input tsv looks to be set up correctly. I have attached that and the pipeline report. Appreciate your insight.

Thanks,
Michael
[pipeline_report.txt](https://github.com/nf-core/sarek/files/4371586/pipeline_report.txt)
[P-0006113-T01-IM5.txt](https://github.com/nf-core/sarek/files/4371588/P-0006113-T01-IM5.txt)

**Comment by MaxUlysse** [comment]
Hi @mkinnaman 
I'm sorry I didn't notice your issue before.
Can you just remove the first line in your tsv file?

**Comment by MaxUlysse** [comment]
Hi @mkinnaman any updates?

**Comment by mkinnaman** [comment]
Less - fixed this - some other issues have popped up - will reach out on slack when I have more - thanks for your responsiveness!

**Comment by MaxUlysse** [comment]
No problem at all.
Glad to know it was fixed.
Don't hesitate to ping me on Slack if you have any issue.
