### ISSUE TITLE
Variant missing in HaplotypeCaller but present in HaplotypeCallerGVCF

### ISSUE THREAD

**Issue by jfnavarro** [nf-core/sarek#186]
The variant is a "control" variant that should always be detected. It appears in the results of HaplotypeCallerGVCF but not in HaplotypeCaller. This may be a bug?

**Comment by FriederikeHanssen** [comment]
Without further info I don't think we can adress this is within sarek. If it is a bug it might come from the tool itself and would need addressing on their side
