### ISSUE TITLE
FreeEbayes fails with -no_interval command

### ISSUE THREAD

**Issue by peter-yufan-zeng** [nf-core/sarek#187]
Hi, 
When I start sarek with the --no_interval option as below

`./nextflow run sarek/main.nf -profile singularity --sample UWO23.tsv --custom_config_base sarek/conf --genome GRCh38 -c nextflow.slurm.v2.config --tools HaplotypeCaller,ASCAT,ControlFREEC,FreeBayes,Manta,Strelka,TIDDIT,merge --no_intervals`

I get the following error

```
Error executing process > 'FreeBayes (MS6_vs_325B-no_intervals)

Caused by:
  Process `FreeBayes (MS6_vs_325B-no_intervals)` terminated with an error exit status (1)

Command executed:
  freebayes -f Homo_sapiens_assembly38.fasta  --pooled-continuous  --pooled-discrete   --genotype-qualities  --report-genotype-likelihood-max   --allele-balance-priors-off  --min-alternate-fraction 0.03 --min-repeat-entropy 1  --min-alternate-count 2 -t no_intervals.bed         MS6.recal.bam  325B.recal.bam > no_intervals_MS6_vs_325B.vcf

Command exit status:
  1

Command output:
  (empty)

Command error:
  bed targets file is not open

Work dir:
  /gpfs/fs0/scratch/n/nicholsa/zyfniu/work/0a/adcc1bf7e2663ef9ff50c39b84423a
```

I think this is related to #135 

Thanks for your help

**Comment by MaxUlysse** [comment]
HI @peter-yufan-zeng, thanks a lot for reporting this issue.
Can I ask which sarek version were you using?

**Comment by MaxUlysse** [comment]
I don't think it's related to #135 actually
Just ran `nextflow run . -profile test,docker --tools Freebayes --no_intervals` on the current dev.
and the command executed for Freebayes was:
```
freebayes         -f human_g1k_v37_decoy.small.fasta         --pooled-continuous         --pooled-discrete         --genotype-qualities         --report-genotype-likelihood-max         --allele-balance-priors-off         --min-alternate-fraction 0.03         --min-repeat-entropy 1         --min-alternate-count 2                  9876T.recal.bam         1234N.recal.bam > no_intervals_9876T_vs_1234N.vcf
```
There is this `-t no_intervals.bed` in the command line executed in your case that should not be there.
So can you please try with the current dev to see if the bug is still there?

**Comment by peter-yufan-zeng** [comment]
Hi Max, thanks for your quick reply. I am running Sarek 2.5.2. After I ran into the issue and saw #135 , I recloned the git and ran sarek but was running into the same issue. However, I did not rebuild my singularity image - do I need to do that? 

Thanks for your help again.

**Comment by MaxUlysse** [comment]
No need to rebuild the singularity image.

I'll test out the 2.5.2 to see if I can reproduce the error, can you try the dev branch maybe to see if the issue is still there for you?

**Comment by MaxUlysse** [comment]
I meant no need to rebuild the singularity image if you're running the same version, if you're planning to try the dev, then you will need that

**Comment by MaxUlysse** [comment]
OK, so I tried and this issue is indeed in `2.5.2`, but not any more in the `dev` branch.
Working on a `2.6` release at the moment, which is based on the current `dev` branch, so it won't have this bug as well.

**Comment by peter-yufan-zeng** [comment]
I tried running the dev branch, however, I keep running into the error 
`
The params ``--singleCPUMem`` has been removed.
	Please check: https://nf-co.re/sarek/docs/usage.md#--single_cpu_mem
`

I have deleted the lines in my config file that mentions single_cpu_mem, but sarek is still throwing this errror. Any ideas on how I could get around this? 

Thanks!!!

**Comment by MaxUlysse** [comment]
You should replace singleCPUMem with single_cpu_mem in your config file and that should do it

**Comment by peter-yufan-zeng** [comment]
I replaced singleCPUMem with single_cpu_mem, however it is still throwing this error. Grepping in the directory in my files, I also couldn't find any other instances of singleCPUMem that could be giving this error.

**Comment by peter-yufan-zeng** [comment]
Never mind, I repulled all the files and it is running now. I will report back on whether i still run into problems with freeebayes and haplotypecaller

**Comment by MaxUlysse** [comment]
Any updates?

**Comment by peter-yufan-zeng** [comment]
With the dev-version Sarek is currently getting stuck at MarkDuplicates. I am using a slurm cluster with 40 cores and 180 GB of memory. With Sarek version 2.5.2 on the same samples using the same cluster, markduplicates takes about 6 hours. However, with dev version MarkDuplicates did not finish in 20 hours. I've uped the java memory limit and it still isnt working. 

`20/04/20 15:03:56 INFO Executor: Running task 9756.0 in stage 4.0 (TID 19571)
20/04/20 15:03:57 INFO ShuffleBlockFetcherIterator: Getting 4907 non-empty blocks including 4907 local blocks and 0 remote blocks
20/04/20 15:03:57 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 6 ms
20/04/20 15:03:57 INFO Executor: Finished task 9735.0 in stage 4.0 (TID 19550). 1628 bytes result sent to driver
20/04/20 15:03:57 INFO TaskSetManager: Starting task 9757.0 in stage 4.0 (TID 19572, localhost, executor driver, partition 9757, PROCESS_LOCAL, 7662 bytes)
20/04/20 15:03:57 INFO TaskSetManager: Finished task 9735.0 in stage 4.0 (TID 19550) in 174341 ms on localhost (executor driver) (9742/15703)
20/04/20 15:03:57 INFO Executor: Running task 9757.0 in stage 4.0 (TID 19572)
20/04/20 15:03:57 INFO ShuffleBlockFetcherIterator: Getting 4907 non-empty blocks including 4907 local blocks and 0 remote blocks
20/04/20 15:03:57 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 6 ms
20/04/20 15:04:00 INFO Executor: Finished task 9734.0 in stage 4.0 (TID 19549). 1628 bytes result sent to driver
20/04/20 15:04:00 INFO TaskSetManager: Starting task 9758.0 in stage 4.0 (TID 19573, localhost, executor driver, partition 9758, PROCESS_LOCAL, 7662 bytes)
20/04/20 15:04:00 INFO TaskSetManager: Finished task 9734.0 in stage 4.0 (TID 19549) in 178273 ms on localhost (executor driver) (9743/15703)
20/04/20 15:04:00 INFO Executor: Running task 9758.0 in stage 4.0 (TID 19573)
20/04/20 15:04:00 INFO ShuffleBlockFetcherIterator: Getting 4907 non-empty blocks including 4907 local blocks and 0 remote blocks
20/04/20 15:04:00 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 6 ms
`
For example, this is the .command.err for one of the MarkDuplicate processes. I started the run around 2PM ish, and you can see the last entry was at 3PM - however, the MarkDuplicate process is still running. 

Any thoughts on this issue?

**Comment by MaxUlysse** [comment]
I'm guessing this could be due to the GATK Spark, can you try with again with `--no_gatk_spark` to disable it and `-resume` to allow use of cached data

**Comment by peter-yufan-zeng** [comment]
Ok let me try this

**Comment by peter-yufan-zeng** [comment]
With --no_gatk_spark, i made it past MarkDuplicates. However, now the Sareks throws error during baserecalibrator 

`Error executing process > BaseRecalibrator (UWO23-UWO23_CL-no_intervals)`
`
Caused by:
  Process BaseRecalibrator (UWO23-UWO23_CL-no_intervals) terminated with an error exit status (3)`

`Command executed:`

  `gatk --java-options -Xmx180g         BaseRecalibrator         -I UWO23_CL.md.bam         -O UWO23_CL.recal.table         --tmp-dir /tmp         -R Homo_sapiens_assembly38.fasta                  --known-sites dbsnp_146.hg38.vcf.gz         --known-sites Mills_and_1000G_gold_standard.indels.hg38.vcf.gz --known-sites Homo_sapiens_assembly38.known_indels.vcf.gz         --verbosity INFO`

`Command exit status:
  3`

`Command output:
  (empty)`

`Command error:
  00:34:41.330 INFO  ProgressMeter -         chr1:5249134              0.5                879000        1754374.3
  00:34:51.359 INFO  ProgressMeter -         chr1:7022069              0.7               1193000        1785482.7
  00:35:01.395 INFO  ProgressMeter -         chr1:8882252              0.8               1512000        1809803.1
  00:35:11.399 INFO  ProgressMeter -        chr1:10743791              1.0               1833000        1829006.7
  00:35:21.406 INFO  ProgressMeter -        chr1:12570634              1.2               2149000        1838375.8
  00:35:30.079 INFO  BaseRecalibrator - Shutting down engine`
  `[April 21, 2020 12:35:30 AM UTC] org.broadinstitute.hellbender.tools.walkers.bqsr.BaseRecalibrator done. Elapsed time: 1.34 minutes.`

**Comment by MaxUlysse** [comment]
OK, this is strange...
But, regarding the first issue, you should have a TSV and the associated bam files.
Can you try if `--step variantcalling --tools Freebayes --no_intervals` works, and I open another issue for this `BaseRecalibrator` issue

**Comment by peter-yufan-zeng** [comment]
FreeBayes works now, and my issues with baserecalibrator was due to faulty reference files. I repulled them and sarek works fine now. Thanks for your help and closing the issue!

**Comment by MaxUlysse** [comment]
Wonderful, I am relieved.
Thanks again for your help in noticing and solving this issue.
