### ISSUE TITLE
--skip_qc "BaseRecalibrator" doesn't actually skip BaseRecalibrator...

### ISSUE THREAD

**Issue by tefirman** [nf-core/sarek#216]
Hello! I'm trying to skip the "BaseRecalibrator" qc step because it's producing a strange "java.lang.OutOfMemoryError", but when I use --skip_qc "BaseRecalibrator", it still goes right ahead and runs it. Is this intentional? Or am I doing something incorrectly? Thanks for your help!

-TF

**Comment by MaxUlysse** [comment]
HI @tefirman 

Actually, this option is mainly not to keep the QC report from `BaseRecalibrator` and does not skip the actual process.
It could be confusing to have such an option, so I'll be sure to update the docs about it.

What is your actual issue with `BaseRecalibrator`?
Maybe we can help you figure this out.

**Comment by tefirman** [comment]
Gotcha, yeah maybe call it --dropQC instead of --skipQC?

I'm running into the following error with BaseRecalibrator: "java.lang.OutOfMemoryError: unable to create new native thread". After googling around, it looks like I'm either running out of RAM or hitting a limit on the number of threads I can create at a time (i.e. ulimit). I've tried smaller values for the "-Xmx" and "-Xss" options in java, but I'm still getting the same error, so I think it's the thread limiting. I'm running this pipeline on a shared server that has a "ulimit -u" of 4096, so my next step is seeing if I can get that increased. Have you ever run into such an issue?

-TF

**Comment by MaxUlysse** [comment]
never at this particular step.
But you can probably limit the cpus/memory requirement in a custom config file using the [withName selector](https://www.nextflow.io/docs/latest/config.html).

```nextflow
process {
    withName: BaseRecalibrator {
        memory = 4.GB
    }
}
```

or you can also use [maxForks](https://www.nextflow.io/docs/latest/process.html#maxforks) to limit the number of thread happening at the same time.
It's used also in the process scope, so you can use it for all processes, or just for particular ones with a selector.

**Comment by tefirman** [comment]
Sadly, neither of those fixes worked, I was still getting the same "OutOfMemory" error as before, but my system administrator was able to increase my "ulimit" value and it's working like a charm now. Thanks for your help!

**Comment by jacorvar** [comment]
Hi, I'm experiencing the same issue. Which ulimit value did your sysadmin increase @tefirman ?

Thanks

**Comment by tefirman** [comment]
Hello! This was a while ago so I'm not 100% sure, but I'm pretty sure they increased the "max memory size" and "virtual memory" to "unlimited". Hope this helps!
