### ISSUE TITLE
Adding options for GATK

### ISSUE THREAD

**Issue by DrJCampbell** [nf-core/sarek#218]
We noticed that using the default Mutect2 options, a large number of insertions were being called based solely on evidence from soft clipped bases. Adding the option '--dont-use-soft-clipped-bases true' got rid of these.

Is there a way to add specific options to parts of the pipeline whilst using the official version of sarek or do we need to fork the project, make changes and merge in future updates?

Thanks
James

**Comment by MaxUlysse** [comment]
You can fork and make a PR for that now, we can then include that in the dev branch.
That could be a fast process.

I'm planning for a minor release in less than a month, so it could definitively be included into all that.

**Comment by szilvajuhos** [comment]
Cool, I am just building a new PON for our new sequencing data and start testing the latest GATK - so, if you make a fork/PR it would help us also to check this indels issue. Furthermore, by using the `-r dev` option, your changes can be used by you and by others once the PR is accepted. Generally, the latest updates are in the `dev` branch, do not have to merge all the time, you can even abandon your fork. Merge only if you are actively adding a new feature/fix.
Cheers: Szilva
