### ISSUE TITLE
Analysis of single end (Unpaired) fastq files

### ISSUE THREAD

**Issue by javanOkendo** [nf-core/sarek#231]
Hi,

I have a fastq file (single end) raw files from the RNAseq data. How can I process this using this workflow. I have aligned and indexed my BAM file (to get .bam and .bai). will it be okay for me to use these bam files for variant calling?

**Comment by MaxUlysse** [comment]
Hi @javanOkendo, sorry not to have noticed your question before.
Sarek is for DNA, if you want to work with RNAseq data, I'll recommand nf-core/rnaseq and/or nf-core/rnafusion
