### ISSUE TITLE
Checking the sample sheet in DSL2

### ISSUE THREAD

**Issue by ggabernet** [nf-core/sarek#235]
The DSL2 template foresees a Python script to check the structure of the sample sheet.
However Sarek uses Nextflow / Groovy code for that. How do we want to implement this?

**Comment by MaxUlysse** [comment]
We do have plenty different possibilities within sarek for our sample sheet, depending on the steps.
I do like the fact that we're doing it in Nextflow / Groovy.
I'd vote for continuing this way.

**Comment by MaxUlysse** [comment]
I'm having a go at this sample sheet thingy with the meta map magic from @drpatelh

**Comment by drpatelh** [comment]
Its `meta` mate!!!

**Comment by MaxUlysse** [comment]
attempt is here: #256

**Comment by FriederikeHanssen** [comment]
Basic checks are there, there is a follow up issue for more detailed checks, will track progress there and close this one.
See #469
