### ISSUE TITLE
Create germlineResource for GRCh37

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/sarek#25]
We don't have any `germlineResource` for `GRCh37`
Can you please create one?
cf #24

**Comment by szilvajuhos** [comment]
Now we have germlineResource VCFs for iGenomes on munin at

- GRCh37 (Homo_sapiens/GATK/GRCh37/Annotation/GermlineResource):
  - gnomAD.r2.1.1.GRCh37.PASS.AC.AF.only.vcf.gz (and the .tbi)
  - also a dummy_PON.gnomAD.GRCh37.WGS.AF.GT.01.vcf.gz (and the .tbi)
- GRCh38 (Homo_sapiens/GATK/GRCh38/Annotation/GermlineResource)
  - gnomAD.r2.1.1.GRCh38.PASS.AC.AF.only.vcf.gz (.tbi)
  - dummy_PON.gnomAD.GRCh38.WGS.AF.GT.01.vcf.gz (.tbi)

The gnomAD file for [Mutect2 --germline-resource](https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_hellbender_tools_walkers_mutect_Mutect2.php#--germline-resource) have been generated like getting rid of calls from gnomAD missing the PASS field, also writing out only the AC and AF infos to make file smaller.

The dummy PON is a subset of this subset above: only calls with AF > 0.1 were included. This file should not be used for real filtering.

@MaxUlysse pls review, update iGenomes and close once ready.

**Comment by nandan75** [comment]
Hi ,

I have been trying to find downloadable links for the file (to be used with sarek)

GRCh38 (Homo_sapiens/GATK/GRCh38/Annotation/GermlineResource)
gnomAD.r2.1.1.GRCh38.PASS.AC.AF.only.vcf.gz (.tbi)


Can someone point me to the latest working link? I have tried searching a lot on goiogle but failed!

Appreciate it.

regards,

Nandan

**Comment by szilvajuhos** [comment]
Hi, AFAIR I have made those files for tests, should reside somewhere at BTB's storage. @maxulysse maybe can dig it up, but would not be that difficult to re-create them using awk (printing out ounly entries with the PASS flag, and only the AC and AF filelds.)

**Comment by maxulysse** [comment]
@nandan75 AWS igenomes ressources are findable here: https://ewels.github.io/AWS-iGenomes/
The following command should work to download each files:

```
aws s3 --no-sign-request --region eu-west-1 cp s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/GermlineResource/gnomAD.r2.1.1.GRCh38.PASS.AC.AF.only.vcf.gz ./references/Homo_sapiens/GATK/GRCh38/Annotation/GermlineResource/.
aws s3 --no-sign-request --region eu-west-1 cp s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/GermlineResource/gnomAD.r2.1.1.GRCh38.PASS.AC.AF.only.vcf.gz.tbi ./references/Homo_sapiens/GATK/GRCh38/Annotation/GermlineResource/.
```

**Comment by nandan75** [comment]
Thanks

Szilveszter Juhos
and
Maxime U. Garcia

Appreciate your assistance,

regards,

Nandan
