### ISSUE TITLE
markdown_to_html.py: Failed loading extension "pymdownx.extra".

### ISSUE THREAD

**Issue by bimbam23** [nf-core/sarek#254]
I tried to run with provided bam file:
```
nextflow run nf-core/sarek/ --custom_config_base nf-core/sarek/configs-master/ --input bam_files.tsv --step variantcalling --genome hg19

The printed error message is:
[nf-core/sarek] Pipeline completed with errors-
Error executing process > 'Output_documentation'

Caused by:
  Process `Output_documentation` terminated with an error exit status (1)

Command executed:

  markdown_to_html.py output.md -o results_description.html

Command exit status:
  1

Command output:
  (empty)

...

  ImportError: Failed loading extension "pymdownx.extra".
```
I can give more details if needed.

Edit for better markdown rendering by @MaxUlysse

**Comment by MaxUlysse** [comment]
Hi @bimbam23 
Given the error message, I'm assuming you're not using any profile or particular configuration file.
If so Nextflow assume that all tools are available on the system where it's run on.
Can you try with `-profile docker` or `-profile singularity` or `-profile conda`

cf https://nf-co.re/usage/introduction#how-to-run-a-pipeline for more information

**Comment by bimbam23** [comment]
thanks that was a quick help looks like this running now.

**Comment by MaxUlysse** [comment]
No problem at all, don't hesitate if you have any other issues ;-)
