### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by DrJCampbell** [nf-core/sarek#258]
Hi - In the documentation here:
https://nf-co.re/sarek/docs/usage#--tools

There are broken links to:
https://nf-co.re/sarek/docs/usage/variant_calling
https://nf-co.re/sarek/docs/usage/annotation

I found the info I was after in the docs directory in github:
https://github.com/nf-core/sarek/tree/master/docs

**Comment by ewels** [comment]
Moved back to nf-core/sarek again, as this won't be something that is addressed in the website. Note that the website does now give helpful GitHub suggestions in the above examples though, which is something.. ✨

**Comment by davidmasp** [comment]
This link also leads to 404, https://nf-co.re/sarek/2.6.1/docs/input coming from https://nf-co.re/sarek/2.6.1

**Comment by MaxUlysse** [comment]
I'll be refactoring the whole documentation as mentioned in another issue.
Hopefully this will solve all our issues with documentation.
Closing this issue, and I'll open another one for this particular task.
