### ISSUE TITLE
Issues regarding full runs with Sentieon

### ISSUE THREAD

**Issue by szilvajuhos** [nf-core/sarek#273]
I am trying to make a full run to get clinically relevant VCFs, using https://github.com/szilvajuhos/btb-scripts/blob/master/gms/runAll.sh as frontend. Issues so far are:

- we should _not_ run annotations for all files, because it takes ages 
- have to disable GVCF during runs (use `--no_gvcf`) 
- do not run variant callers in a single command, because we are going to run out of inodes/open files/whatever (see #268)
- PON file is run-dependent, we have to remove from configs, as some runs has no PON (have to disable for these)
- VQSR for HaplotypeCaller (#89)

**Comment by MaxUlysse** [comment]
just a comment with an idea before I forgot about it:

in the sarek specific config: https://github.com/nf-core/configs/blob/master/conf/pipeline/sarek/munin.config
We can add a sentieon profile like we did in the uppmax config file with the devel profiles on the uppmax config: https://github.com/nf-core/configs/blob/3d744d9aea2371d712f38fca2c6f36ed3e69853c/conf/uppmax.config#L41-L52
and we can control some specific params (including PON) within this profile.
