### ISSUE TITLE
404 in sarek documentation

### ISSUE THREAD

**Issue by davidmasp** [nf-core/sarek#275]
Hi

I saw a 404 error in https://nf-co.re/sarek/2.6.1/docs/input . 

As instructed, I open the issue.

Cheers

**Comment by ewels** [comment]
Thanks! Yes this is due to a change in how the documentation on the website is built. It’ll need to be fixed in the readme for the next Sarek release.

**Comment by davidmasp** [comment]
So I guess it's the same as #258 . I understand the docs have to be re-wired entirely so I close this issue and comment on the other one. 

Cheers
