### ISSUE TITLE
MultiQC Report - GATK Section (BQSR)

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#277]
I noticed that the description says, that this section shows 'base quality scores in each sample before and after BQSR'. However, I only see the tag `Pre` in the plot. I suppose there are three options:

1. Some file is not displayed
2. The module description does not fit this use case 
3. I missed setting some option or sth in that direction

Attached a screen shot from the report. It was generated using `2.6.1` 
<img width="698" alt="Screenshot 2020-08-31 at 16 46 34" src="https://user-images.githubusercontent.com/12273093/91735083-12c4a180-ebac-11ea-8d3d-c857913d6f59.png">

**Comment by noirot** [comment]
And also the samples names are not good while hovering curves.

**Comment by FriederikeHanssen** [comment]
@noirot Can you detail what you mean?

**Comment by FriederikeHanssen** [comment]
Looking at other multiqc report examples, I believe the plot is shown as expected. A new plot is added now too:
![Screenshot 2022-04-21 at 11 36 15](https://user-images.githubusercontent.com/12273093/164426537-18b3dfe3-94ca-4d18-a902-251f3749552c.png)

The original question/issue is solved with this. @noirot I will need more info to adress your issue.
