### ISSUE TITLE
Cleanup issues before release

### ISSUE THREAD

**Issue by szilvajuhos** [nf-core/sarek#28]
- [ ] rename wgs_calling_regions_CAW.list for GRCh37
- [x] QC processes do launch with '--noReports' (should not)
- [ ] add check for misspelled parameteres (i.e. adding '--pom file.vcf' is silently ignored)
... more to come as I am testing

**Comment by MaxUlysse** [comment]
`--noReports` has been replaced by `--skip all`

**Comment by MaxUlysse** [comment]
You could specify which QC tool to skip with this `--skip` params: (`bamQC`, `BCFtools`, `FastQC`, `MultiQC`, `samtools`, `vcftools`, `versions`)

**Comment by MaxUlysse** [comment]
For the other issues, I think it can all be treated in the current draft PR #19

**Comment by szilvajuhos** [comment]
moved to #19
