### ISSUE TITLE
Update indices to use with BWAMem2

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#281]
For BWA-Mem2, new indices are required, as described here: https://github.com/bwa-mem2/bwa-mem2/tree/cbcc183c0843d20d45c84e066177eb8d58be2f9b

Additionally, for a future version upgrade of this tool, we may once again have to update the indices: https://github.com/bwa-mem2/bwa-mem2

In the long run, this requires a recomputation of the indices stored in igenomes. For the short term, a quick fix could be to not specify the index paths in igenomes anymore, forcing a computation for each run. This would increase the runtime however.

**Comment by MaxUlysse** [comment]
Back to using `bwa-mem` as default.
But `bwa-mem2` is still available as an option in `dev`.
New plan is to provide both versions within sarek with the `--aligner` option.

**Comment by FriederikeHanssen** [comment]
Great :)

**Comment by MaxUlysse** [comment]
I was thinking that we can add a key for bwa-mem2 indices in the *genomes.config

**Comment by FriederikeHanssen** [comment]
You mean providing them there same as with bwa-mem? Yes, that was my original thought. No need to recompute everything all the time.

**Comment by MaxUlysse** [comment]
I'll do some testing with the test-datasets

**Comment by sk-sahu** [comment]
Came here after trying with `--aligner bwa-mem2` it give following error. And realized it not exposed yet in the release 2.7 

```
-----------------------------
Executing in SSE4.1 mode!!
-----------------------------
* Ref file: Homo_sapiens_assembly38.fasta
* Entering FMI_search
ERROR! Unable to open the file: Homo_sapiens_assembly38.fasta.bwt.2bit.64
```

**Comment by FriederikeHanssen** [comment]
Hey @sk-sahu ! For now, you also need to set `--bwa false` so the indices are recomputed for the new aligner. Beware, the resource request for the index computation are currently optimised for bwa-mem and you will probably have to set them yourself. I have so far used:

```
 cpus = { check_max( 12 * task.attempt, 'cpus' ) }
 memory = { check_max( 84.GB * task.attempt, 'memory' ) }
```

but no guarantees.

Other option would be to compute the indices separately and provide the paths to sarek via `--bwa` (see here also: https://nf-co.re/sarek/2.7/parameters#bwa) 

Hope this helps :)
