### ISSUE TITLE
Instructions not clear enough for using custom genome

### ISSUE THREAD

**Issue by RyanYip-Kat** [nf-core/sarek#291]
when I run the commands:
```
nextflow run -bg nf-core/sarek -profile docker \
        --input /home/ye/Work/BioAligment/Variant-Calling/sample.tsv \
        --no_gatk_spark --save_bam_mapped --no_intervals \
        --genome  "GRCh38"  \
        --fasta "/home/ye/Data/genome/GRCh38.primary_assembly.genome.fa" \
        --fasta_fai "/home/ye/Data/genome/GRCh38.primary_assembly.genome.fa.fai" \
        --igenomes_ignore --dbsnp "/home/ye/Data/genome/dbsnp_146.hg38.vcf.gz" \
        --known_indels "/home/ye/Data/genome/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz" \
        --email "ryanyip_@hotmail.com" --email_on_fail --max_cpus 16 --publish_dir_mode  "copy" \
        --outdir sarek-results -w sarek-works -with-report report.html
```

I always got the error:
```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted.
Memory limited without swap.
[E::bwa_idx_load_from_disk] fail to locate the index files.
```
And my sample.tsv is:

```
L9527   M       0       Liusheng        CL1     /home/ye/Data/dataset/totalRNA/Liusheng/C_L1_382382_R1_001.fastq.gz     /home/ye/Data/dataset/totalRNA/Liusheng/C_L1_382382_R2_001.fastq.gz
```

EDIT: formatting

**Comment by MaxUlysse** [comment]
Hi @RyanYip-Kat, thank you for your interest in our sarek project.

Given the warning, I would say that this is an issue with docker.
Can you create a `custom.config` file with:
```
docker.runOptions = '-u \$(id -u):\$(id -g)'
```
and specify it to your command line with `-c custom.config`

**Comment by RyanYip-Kat** [comment]
But when I set the --bwa with my bwa_index file,I got the same error

**Comment by MaxUlysse** [comment]
how do you set up the bwa files with `--bwa`?

**Comment by RyanYip-Kat** [comment]
![image](https://user-images.githubusercontent.com/67267063/95842421-19346480-0d79-11eb-971e-e996afea763e.png)
--bwa /path/GRCh38.primary_assembly.genome.fa

**Comment by MaxUlysse** [comment]
ok, so `GRCh38.primary_assembly.genome.fa` is the fasta file, the bwa indexes are the `amb,ann,bwt,pac,sa`.
Can you try `--bwa "/path/GRCh38.primary_assembly.genome.fa.{amb,ann,bwt,pac,sa}" instead?

**Comment by MaxUlysse** [comment]
@RyanYip-Kat any update?

**Comment by RyanYip-Kat** [comment]
Yes, when set -bwa "/path/GRCh38.primary_assembly.genome.fa.{amb,ann,bwt,pac,sa}",it worked,but I got annother error.When run BaseRecalibrator and I did not set --dict,I got the error: "A USER ERROR has occurred: Fasta dict file file://GRCh38.primary_assembly.genome.dict for reference file://GRCh38.primary_assembly.genome.fa does not exist",maybe generat automatically from the fasta reference failed .It is a bug in docker profile?

**Comment by MaxUlysse** [comment]
I see.
It won't regenerate the dict file by default, because there is actually one
provided within the GRCh38 configuration.
Specify --dict false to remove it and have it generated, or use --genome
custom --igenones_ignore to use a different genome. --genome GRCh38 should
use the genome set up within the igenomes profile.

**Comment by RyanYip-Kat** [comment]
OK,I will set --dict fasle --dbsnp_index false --dbsnp_index false and try aging.Thanks!

**Comment by RyanYip-Kat** [comment]
A USER ERROR has occurred: Fasta dict file file://GRCh38.primary_assembly.genome.dict for reference file://GRCh38.primary_assembly.genome.fa does not exist. Please see http://gatkforums.broadinstitute.org/discussion/1601/how-can-i-prepare-a-fasta-file-to-use-as-reference for help creating it.

I always got the this error even if I set  --dict fasle --dbsnp_index false --dbsnp_index false ... or provived *index files. 
And my scripts is :
   nextflow run -bg nf-core/sarek -profile docker \
        -resume \
        --input /home/ye/Work/BioAligment/Variant-Calling/sample.tsv \
        --no_gatk_spark --save_bam_mapped --no_intervals \
        --genome  "GRCh38"  \
        --dbsnp_index "/home/ye/Data/genome/dbsnp_146.hg38.vcf.gz.tbi" \
        --known_indels_index "/home/ye/Data/genome/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi" \
        --dict "/home/ye/Data/genome/GRCh38.primary_assembly.genome.fa.dict" \
        --fasta "/home/ye/Data/genome/GRCh38.primary_assembly.genome.fa" \
        --bwa "/home/ye/Data/genome/GRCh38.primary_assembly.genome.fa.{amb,ann,bwt,pac,sa}" \
        --fasta_fai "/home/ye/Data/genome/GRCh38.primary_assembly.genome.fa.fai" \
        --igenomes_ignore \
        --dbsnp "/home/ye/Data/genome/dbsnp_146.hg38.vcf.gz" \
        --known_indels "/home/ye/Data/genome/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz" \
        --email "ryanyip_@hotmail.com" --email_on_fail --max_cpus 24 --publish_dir_mode  "copy" \
        --outdir sarek-results -w sarek-works -with-report report.html

I still can not run the nextflow pipeline successfully!

**Comment by MaxUlysse** [comment]
Given the error you have, I would say that GATK does not like that the file is `/home/ye/Data/genome/GRCh38.primary_assembly.genome.fa.dict` and would prefer it to be `/home/ye/Data/genome/GRCh38.primary_assembly.genome.dict`.
Can you try renaming it and relaunching sarek again?

Otherwise, I'll recommend trying:
```
nextflow run -bg nf-core/sarek -profile docker
-resume
--input /home/ye/Work/BioAligment/Variant-Calling/sample.tsv
--no_gatk_spark --save_bam_mapped --no_intervals
--save_reference
--genome "custom"
--dbsnp "/home/ye/Data/genome/dbsnp_146.hg38.vcf.gz"
--dbsnp_index "/home/ye/Data/genome/dbsnp_146.hg38.vcf.gz.tbi"
--known_indels "/home/ye/Data/genome/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
--known_indels_index "/home/ye/Data/genome/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi"
--fasta "/home/ye/Data/genome/GRCh38.primary_assembly.genome.fa"
--bwa "/home/ye/Data/genome/GRCh38.primary_assembly.genome.fa.{amb,ann,bwt,pac,sa}"
--fasta_fai "/home/ye/Data/genome/GRCh38.primary_assembly.genome.fa.fai"
--igenomes_ignore
--email "ryanyip_@hotmail.com" --email_on_fail --max_cpus 24 --publish_dir_mode "copy"
--outdir sarek-results -w sarek-works -with-report report.html
```

**Comment by RyanYip-Kat** [comment]
Thanks for your suggestion! I run the code with your suggestion,It worked and the report.html also show successfully.But the folder  sarek-results/VariantCalling is None,and also got the error :  Failed to invoke `workflow.onComplete` event handler.

**Comment by MaxUlysse** [comment]
Of course..
We actually need to specify some tools with `--tools`
cf https://nf-co.re/sarek/dev/usage#--tools-for-variant-calling

**Comment by MaxUlysse** [comment]
@RyanYip-Kat any progress? Did you managed to get some results in the end?

**Comment by RyanYip-Kat** [comment]
Yes,it worked when add --tools.Thank you very much!

**Comment by MaxUlysse** [comment]
Good, I'm happy to know that it's now working for you.
Don't hesitate if you have any other issue.
I'll keep this issue open for now, to remind me to complete the docs for custom genome usage.

**Comment by FriederikeHanssen** [comment]
we have gone through a few rounds of rewriting, last one is this #668 . I hope this makes the docs more easy to understand. I would close for now but please re-open or open a new issue, if you find them to be insufficient :)
