### ISSUE TITLE
small bug  in main.nf line 439

### ISSUE THREAD

**Issue by chelauk** [nf-core/sarek#292]
https://github.com/nf-core/sarek/blob/0e111ebead1e8176c0a8f8300ff0b13b2ba4e253/main.nf#L439

should be 

```if (params.annotate_tools) summary['Tools to annotate'] = params.annotate_tools.join(', ')```

I think

**Comment by MaxUlysse** [comment]
```
annotateTools = params.annotate_tools ? params.annotate_tools.split(',').collect{it.trim().toLowerCase().replaceAll('-', '')} : []
```

actually the error is here, this `annotateTools` should be `annotate_tools`.

I'll make a PR for it, thanks for spotting that
