### ISSUE TITLE
ConcatVCF process is run for a single sample

### ISSUE THREAD

**Issue by szymonwieloch** [nf-core/sarek#306]
I run the pipeline with only tumor samples and with the ControlFREEC tool. My input file is something like this:

```
e8f63b36-a0b9-406e-905e-69b7621f33ba    XX      1       e8f63b36-a0b9-406e-905e-69b7621f33ba_sample     1       e8f63b36-a0b9-406e-905e-69b7621f33ba_R1.fastq.gz        e8f63b36-a0b9-406e-905e-69b7621f33ba_R2.fastq.gz
a35760da-3f13-40a3-8537-e7e841baa6a1    XX      1       a35760da-3f13-40a3-8537-e7e841baa6a1_sample     1       a35760da-3f13-40a3-8537-e7e841baa6a1_R1.fastq.gz        a35760da-3f13-40a3-8537-e7e841baa6a1_R2.fastq.gz
```
While running the pipeline, the process ConcatVCF is run twice (once per each sample, the failed process was probably just a random error):
```
[50/c0e2d7] process > ConcatVCF (FreeBayes-a35760da-3f13-40a3-8537-e7e841baa6a1_sample)                                                           [100%] 3 of 3, failed: 1 ✔
```

I am no a great expert but I had a discussion with @apeltzer and he suggested that this shouldn't happen - when you have tumor samples without control samples, then no VCF concatenation should take place. He suggested that you may want to know, so I am just letting you know that you have a potential issue.

**Comment by apeltzer** [comment]
My understanding was at least that it shouldn't happen - but happy to see that clarified :-)

**Comment by FriederikeHanssen** [comment]
This should be fixed in `dev` now. Concatenation is done when Variantcalling is done on multiple intervals in parallel for a single sample - VC combination. 
In case you experience this problem again, we can re-open the issue :)
