### ISSUE TITLE
control-FREEC reference file out100m2_hg38.gem doesn't exist in s3/igenomes

### ISSUE THREAD

**Issue by XLuyu** [nf-core/sarek#312]
Hello, 

I have encountered a problem to run control-FREEC on S3.

In nextflow.config, the default `igenomes_base` = `s3://ngi-igenomes/igenomes/`

In conf/igenomes.config, 
`mappability             = "${params.igenomes_base}/Homo_sapiens/GATK/GRCh38/Annotation/Control-FREEC/out100m2_hg38.gem"`
but `s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/Control-FREEC/out100m2_hg38.gem` actually doesn't exist. 

Can you upload the required file? Thank you in advance.

**Comment by MaxUlysse** [comment]
Duplicates of #305
