### ISSUE TITLE
How to change MarkDup java option ?

### ISSUE THREAD

**Issue by noirot** [nf-core/sarek#316]
I'm using  nf-core/sarek v2.6.1 with Nextflow-v20.10.0

I tried to change values of java memory for markdup without success.

`nextflow run nf-core/sarek -c ../genotoul_1.config --input input.tsv ... -resume --tools HaplotypeCaller --no_gatk_spark ` 

In config I tried with and without following lines
`
withName:MarkDuplicates {
  memory = 24.GB
}
`

And in command line I tried with and without the following option: 
`--markdup_java_options "-Xms8000m -Xmx15g" `

The command of markduplicate in command.sh never changed and job is always killed by slurm : 
`
#!/bin/bash -euo pipefail
gatk --java-options "-Xms3g -Xmx6g"         MarkDuplicates         --MAX_RECORDS_IN_RAM 50000         --INPUT ....
`
What am I doing wrong?

**Comment by MaxUlysse** [comment]
Hi @noirot, sorry for the late reply.

`MarkDuplicates` has always been a complicated tool for us to use properly.
We did notice at some point that is was performing well with less memory, and came up with this solution (cc @apeltzer @szilvajuhos ).
https://github.com/nf-core/sarek/blob/bce378e09de25bb26c388b917f93f84806d3ba27/main.nf#L1420
I know that Nextflow has some issues with `-` in quotes (cf https://github.com/nextflow-io/nextflow/issues/1675)
I notice that we actually use `'"-Xms4000m -Xmx7g"'` in our `nextflow.config` file:
https://github.com/nf-core/sarek/blob/bce378e09de25bb26c388b917f93f84806d3ba27/nextflow.config#L54

Can you maybe try to add
```
params.markdup_java_options = `"-Xms8000m -Xmx15g"`
```
in your custom config file?

I wish you the best for the end of the year,
All the best,
Maxime

**Comment by noirot** [comment]
Happy new year !

I figured out a problem ,
the "task.memory.toGiga()" return 7 even if I set 
```
withName:MarkDuplicates {
  memory = 24.GB
OR
  memory = '24.GB'
}
```
And even in .command.run, I have #SBATCH --mem 7168M but I never configured this value for markDup.
Maybe a nextflow pb ?

**Comment by noirot** [comment]
Arrrfff solved ! I forgot process around config :/
Sorry for disturbing.

```
process {
  withName:MarkDuplicates {
    memory = '24.GB'
  }
}
```

**Comment by MaxUlysse** [comment]
Happy new year to you too!!!

I'm glad you managed to make it work.
Don't hesitate if you have any more issues.
