### ISSUE TITLE
Sarek should have an error or at least a warning when no fasta params

### ISSUE THREAD

**Issue by pablosoro** [nf-core/sarek#321]
In my samplesheet I have 15 lines (for my 15 samples) looking like:
`FS_WT_C	XX	0	SUB1152A31	L007	/absolute/path/SUB1152A31_S91_L007_R1_001.fastq.gz	/absolute/path/SUB1152A31_S91_L007_R2_001.fastq.gz`

Sarek version is 2.6.1

Command line:
```
ml load Nextflow/19.04.0
ml load Singularity/3.3.0
nextflow run nf-core/sarek -profile crick --input 'samplesheet.tsv' --igenomes_ignore --genome custom /absolute/path/GCF_001722355.1_ASM172235v1_genomic.fasta
```

I have `results/Preprocessing/TSV` and that TSV folder is empty.
In `results/Reports` I have folders for each of my samples but there's only fastqc files

In my MultiQC report I have General Statistics and then I have FastQC tests like Sequence Counts, Per Sequence Quality Score... and others.

[nextflow_log.txt](https://github.com/nf-core/sarek/files/5819800/nextflow_log.txt)

**Comment by MaxUlysse** [comment]
As discussed on Slack, it was a missing `--fasta` params in the command line.
Sorry I did not realised that earlier.
It should be:
```
nextflow run nf-core/sarek -profile crick --input 'samplesheet.tsv' --igenomes_ignore --genome custom /
--fasta /absolute/path/GCF_001722355.1_ASM172235v1_genomic.fasta
```
Sarek is actually running only `fastqc`.

We should have an error or at least a warning in that case.

**Comment by FriederikeHanssen** [comment]
Sarek/dev is now printing : ```Genome fasta file not specified with e.g. '--fasta genome.fa' or via a detectable config file.```
when no fasta present.

would close this issue now :) Let us know if this is not sufficient

**Comment by mschubert** [comment]
For people googling this message, see documentation here: https://nf-co.re/usage/reference_genomes
