### ISSUE TITLE
Small mistake in usage.md

### ISSUE THREAD

**Issue by heseber** [nf-core/sarek#327]
The paragraph talks about`star`, the code example uses `VEP`.

![image](https://user-images.githubusercontent.com/22882929/105075675-5b60f680-5a8a-11eb-93ba-3bcfff5567a8.png)

**Comment by heseber** [comment]
By the way, it would probably be worthwhile using `withLabel` here to catch both `VEP` and `VEPmerge`.

**Comment by MaxUlysse** [comment]
> The paragraph talks about`star`, the code example uses `VEP`.

Very good catch

> By the way, it would probably be worthwhile using `withLabel` here to catch both `VEP` and `VEPmerge`.

Good idea

I'll add all that to my current PR
