### ISSUE TITLE
Error in test_annotation VEP

### ISSUE THREAD

**Issue by ChillyMomo709** [nf-core/sarek#328]
Hi there,

I tested the annotation part of the pipeline using the test_annotation profile and following command: 

`nextflow run nf-core/sarek -profile test_annotation,docker --tools vep,snpeff`

```
...
-------------------- EXCEPTION --------------------
MSG: ERROR: Cache assembly version (WBcel235) and database or selected assembly version (GRCh37) do not match

If using human GRCh37 add "--port 3337" to use the GRCh37 database, or --offline to avoid database connection entirely
...
```

I attached the failed VEP process log files 

[command.err.txt](https://github.com/nf-core/sarek/files/5841349/command.err.txt)
[command.log.txt](https://github.com/nf-core/sarek/files/5841350/command.log.txt)
[command.sh.txt](https://github.com/nf-core/sarek/files/5841351/command.sh.txt)

[nextflow.log](https://github.com/nf-core/sarek/files/5841337/nextflow.log)

Best,
Momo

**Comment by MaxUlysse** [comment]
Hi @ChillyMomo709
This error has been fixed in the PR #288 which has been merged in `dev`.
Adding `-r dev` to specify the `dev` branch will solve this problem.
Planning for a new release (2.7) soon.
