### ISSUE TITLE
Skip BaseRecalibration

### ISSUE THREAD

**Issue by samkleeman1** [nf-core/sarek#346]
Hi,

We are running some analysis on an inbred mouse strain versus the genome assembly for the specific strain from the Sanger Mouse Genome Project. As a result, it is difficult to define what the 'known SNPs' or 'known indels' would be. I would like to run the pipeline without BaseRecalibration, I was wondering if you can suggest how to do this?

Kind regards,

Sam Kleeman

**Comment by MaxUlysse** [comment]
Hi @samkleeman1
`Known indels` and `known SNPs` would be a list of known variants (cf [GATK docs](https://gatk.broadinstitute.org/hc/en-us/articles/360035890831-Known-variants-Training-resources-Truth-sets)).
> In the strictest sense, a known variants resource is a list of variants that have been previously identified and reported, such as dbSNP. This typically does not imply any level of systematic curation or cross-validation. Tools that take such a resource do not assume that the variant calls are all true. If you do not have a known variants resource available for your organism of interest, you can usually bootstrap one from your own data.

And this `known variants` set is used to to mask out bases at sites of real (expected) variation, to avoid counting real variants as errors. It's an optional but highly recommended step.

cf [GATK docs](https://gatk.broadinstitute.org/hc/en-us/articles/360035890531-Base-Quality-Score-Recalibration-BQSR-).

In Sarek, is you don't provide any known variants, then the `BaseRecalibration` step won't happen.
So you will still have some aligned BAMs, but without recalibration/marked duplicates.
Which will give you less optimal results from variant calling.

For `GRCm38`, we currently use these files for the dbsnp and known_indels ->
https://github.com/nf-core/sarek/blob/7ccfb36509d8380946c048065129b29d69c8443b/conf/igenomes.config#L67
https://github.com/nf-core/sarek/blob/7ccfb36509d8380946c048065129b29d69c8443b/conf/igenomes.config#L73
