### ISSUE TITLE
MarkDuplicates configured with invalid memory options (-Xms0g -Xmx-1g)

### ISSUE THREAD

**Issue by BrunoGrandePhD** [nf-core/sarek#347]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/sarek pipeline documentation](https://nf-co.re/sarek/usage)

## Description of the bug

**Full disclosure:** I'm an absolute novice at Nextflow, so if you think this problem has nothing to do with `sarek`, just let me know and I can migrate the issue to the Nextflow repository. That said, any friendly pointers are well-appreciated! 

For some reason, the `MarkDuplicates` jobs are being configured with invalid Java memory options (`-Xms0g -Xmx-1g`). Unsurprisingly, this results in `Invalid maximum heap size: -Xmx-1g` errors. I've included the full `MarkDuplicates` command below. 

```
gatk --java-options "-Xms0g -Xmx-1g" MarkDuplicates --INPUT TCRBOA3-T.bam --METRICS_FILE TCRBOA3-T.bam.metrics --TMP_DIR . --ASSUME_SORT_ORDER coordinate --CREATE_INDEX true --OUTPUT TCRBOA3-T.md.bam
```

## Steps to reproduce

I'm running the `sarek` workflow on some standard exome FASTQ files derived from tumour-normal pairs. The workflow is running locally on an `m5a.8xlarge` EC2 instance (32 cores and 128 GB of memory). I've included the `nextflow` command below. 

Note that I have to include a value for `--max_memory` because I run into errors with the `qualimap` jobs where they attempt to run with 128 GB when only ~123 GB are actually available. I believe this is a separate issue (although let me know if this assumption is wrong), and at least I have a workaround for it. 

```
export NXF_OPTS='-Xms1g -Xmx4g'

nextflow run \
    nf-core/sarek -revision 2.7 -resume fabulous_poincare \
    -profile docker -with-tower \
    -work-dir /home/ubuntu/runs/sarek-tcrb/work/ \
    --outdir /home/ubuntu/runs/sarek-tcrb/results/ \
    --input /home/ubuntu/scripts/nf-core-sarek/sarek-tcrb-samples-local.tsv \
    --step mapping --tools 'Strelka,Mutect2,VEP' \
    --genome GRCh38 --igenomes_base /home/ubuntu/igenomes/ \
    --max_cpus 4 --max_memory 64 GB
```

I tried setting the available CPUs and memory in a `nextflow.config` file (loaded with the `-config` option), to no avail. 

```
executor {
    $local {
        cpus = 16
        memory = '64 GB'
    }
}
```

I also tried setting `--markdup_java_options '"-Xms4000m -Xmx7g"'` in the Nextflow command, which still didn't work. 

Let me know if you could use more details. Thanks! 

## Expected behaviour

I expected Nextflow and/or the `sarek` workflow to provide a minimum amount of memory to the `MarkDuplicates` jobs. 

## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline
- [x] The `.nextflow.log` file ([nextflow.log](https://github.com/nf-core/sarek/files/5993562/nextflow.log))

## System

- Hardware: AWS EC2 instance (m5a.8xlarge)
- Executor: local
- OS: Ubuntu
- Version: 18.04.4

## Nextflow Installation

- Version: 20.10.0 build 5430

**Comment by MaxUlysse** [comment]
@FriederikeHanssen Can you help out on this one?

**Comment by FriederikeHanssen** [comment]
I will take a look. For the qualimap problem of having less memory available than the machine claims, this is due to some overhead that has to be accounted for. For more information check out the great tutorial by Tobias Neumann [here](https://t-neumann.github.io/pipelines/AWS-pipeline/):
```
...keep in mind that not the entire memory listed in the instance type specification can be used, since some of it will be occupied with running basic instance services
```

**Comment by FriederikeHanssen** [comment]
Ok, so on an initial look, it seems like memory is somehow read as 0:
```
    markdup_java_options = task.memory.toGiga() > 8 ? params.markdup_java_options : "\"-Xms" +  (task.memory.toGiga() / 2).trunc() + "g -Xmx" + (task.memory.toGiga() - 1) + "g\""
```

`params.markdup_java_options` is set, if the taks memory is above 8GB. If it is 0 though, the equation in the second part comes in : `Xms = 0/ 2 = 0` , `Xmx = 0 - 1 = -1` which would match what you got. I wonder, if it could be a formatting issue. 

To set the memory specifically for `MarkDuplicates` you could try the following format:
```
process{
       withName:MarkDuplicates{
          memory = 64.GB
         cpus = 16
     }
}
```

and add it in a `test.config`, then specify it with `-c` in your input.

**Comment by FriederikeHanssen** [comment]
Ok, I think I see the problem: When I specify `--max_memory 64 GB`, what I get in any process is `memory=64.0 B`. In `MarkDuplicates` since it converts to Giga and then truncates, it turns out to be 0.

**Comment by apeltzer** [comment]
Wondered the same when I had a look at the command line that @BrunoGrandePhD specified whether this is the problem. 

`--max_memory 64 GB` will most likely not be converted correctly to nextflow/groovy memory units I fear :-(

**Comment by BrunoGrandePhD** [comment]
@FriederikeHanssen: Thank you for going through the trouble of reproducing the issue! I added periods to all memory values (_e.g._ `64.GB`) and it seems to be working now. I'm glad it was an easy fix. 

I realize this wasn't a sarek issue at all; just my own Groovy ignorance, so I especially appreciate you helping me out! I'll pay it forward by submitting a PR to the general nf-core [troubleshooting page](https://nf-co.re/usage/troubleshooting) in case anyone else runs into this. 

Cheers, everyone!

**Comment by FriederikeHanssen** [comment]
Glad to hear this worked out for you. If you don't mind, I will close this issue. If you get stuck again, feel free to open a new one, re-open it, or ping us on slack 🙂

**Comment by BrunoGrandePhD** [comment]
Fine by me! Thanks for fostering a welcoming community!
