### ISSUE TITLE
[FEATURE] Standard Output = standard ouput and error output

### ISSUE THREAD

**Issue by AxelMaths** [nf-core/sarek#350]
Hi !

I wanted to separate the standard error and the standard output using `1>>` and `2>>` in an ubuntu terminal, but the file generated with `2>>` is empty, and the errors are in the file generated with `1>>`.

## Describe the solution you'd like

I would like to separate the standard output using `1>>` and the standard error output using `2>>`. 

Thanks

## Additional context

I use Sarek v2.7 with this characteristics :
- ubuntu 20.04
- 12 CPUs
- 125 Go of RAM

**Comment by MaxUlysse** [comment]
Hi @AxelMaths I'm afraid this is more a Nextflow issue than a Sarek specific one.
Have you checked the Nextflow docs: https://www.nextflow.io/docs/latest/index.html

**Comment by ewels** [comment]
Which output do you want? From Nextflow itself you mean, or a specific tool?

> the errors are in the file generated with 1>>.

What do you mean by this? Can you paste some example output please?

**Comment by AxelMaths** [comment]
> Which output do you want? From Nextflow itself you mean, or a specific tool?
> 
> > the errors are in the file generated with 1>>.
> 
> What do you mean by this? Can you paste some example output please?

Then for example :
sudo nextflow run nf-core/sarek -profile docker --input Input/tiny-manta-https.tsv --step mapping --save_bam_mapped --fasta https://raw.githubusercontent.com/nf-core/test-datasets/sarek/reference/human_g1k_v37_decoy.small.fasta --tools Mutect2 --bwa=false --outdir testsLea/opt_smallFasta --igenomes_ignore --genome "custom" 1>> opt_smallFasta.txt 2>>error_out.txt

I know this command doesn't work, but my file "error_out.txt" is empty.
And the error is in the opt_smallFasta.txt, but I don't want it.

**Comment by MaxUlysse** [comment]
@AxelMaths This is definitively a request on the Nextflow side.
I'd recommend asking either on the [Nextflow gitter](https://gitter.im/nextflow-io/nextflow), or on the [Nextflow repo](https://github.com/nextflow-io/nextflow/).
As far as I know, all the output from Nextflow goes in the `.nextflow.log` and each process has its own folder in `work/` where you have multiple `.command.` file. (`.command.log` and `.command.err`)
