### ISSUE TITLE
[FEATURE] Filtering of common variants with VEP should be optional

### ISSUE THREAD

**Issue by prmac** [nf-core/sarek#352]
## Is your feature request related to a problem? Please describe
VEP filters out common variants based on frequency in 1000 genomes project

https://github.com/nf-core/sarek/blob/master/main.nf#L3750

## Describe the solution you'd like
This behaviour should be optional.  Quite often we are interested in common variants in a cohort of samples

**Comment by MaxUlysse** [comment]
@prmac thanks a lot for the suggestion, I'll add it to the list for the 3.0 release.
The DSL2 modules that we're making in the nf-core/modules repo will enable us to do that more easilly.
