### ISSUE TITLE
Learn Orientation Bias Artifacts

### ISSUE THREAD

**Issue by QiongICR** [nf-core/sarek#357]
To filter out FFPE artifacts with FilterByOrientationBias. Would you add the learn orientation bias tool (LearnReadOrientationModel) to the mutect workflow?

**Comment by MaxUlysse** [comment]
Hi @QiongICR,
There is no plan to do that before the next planned release 3.0.
But we will be sure to add it.
Thanks for the suggestion

**Comment by FriederikeHanssen** [comment]
@GCJMackenzie  this included in the subworkflow you wrote, right?

**Comment by GCJMackenzie** [comment]
@FriederikeHanssen yes, LearnReadOrientationModel is used in the 
somatic_tumor_normal subworkflow:  https://github.com/nf-core/modules/blob/master/subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/main.nf
the module itself is here: https://github.com/nf-core/modules/blob/master/modules/gatk4/learnreadorientationmodel/main.nf
