### ISSUE TITLE
[BUG] Json schema `--tools`

### ISSUE THREAD

**Issue by ggabernet** [nf-core/sarek#380]
Hi there,

when trying to launch Sarek 2.7 with the new tower interface or the nf-core website launcher, it is not possible to select multiple tools, because the parameter is defined as an `enum` parameter. Maybe there were alredy some discussions on slack that I missed 😄 

I thought it would be nice to start a discussion here on how to solve that, can also help with this on a PR :)
One option would be to keep the `--tools` param, but then define it as a string. It is not possible though to validate then that the tools provided are valid.

Another option would be to have `--caller` and `--annotate` params, etc. And define those as `enum`. A disadvantage of this approach though is that still providing two different variant callers won't be possible again. So that this is possible the param should also be defined only as `string`.

So not sure what would be the best way to solve this really...

**Comment by ggabernet** [comment]
Awesome, thanks!

I'm further testing launching via tower, using the `dev` branch now. I've found another small thing related to the schema in case you want to fix it before this release as well.

The default value of `false` for the email field generates an `Invalid format` error. If the field is left empty it works, so maybe the default value for email in the json schema should be an empty string rather than false?

**Comment by maxulysse** [comment]
I'll fix that then

**Comment by maxulysse** [comment]
Just thought of that, but can you check the `dev_2.7.1` branch instead, which would be the release.
(difference should just be the containers, but that way we can check that everything works well)
