### ISSUE TITLE
[BUG] Mutect2 - java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by xhejtman** [nf-core/sarek#384]
Hello,

please, upgrade GATK to version 4.1.8.0 to fix Mutect2 java.lang.StringIndexOutOfBoundsException as can be seen here:
https://github.com/broadinstitute/gatk/issues/6516

**Comment by maxulysse** [comment]
@xhejtman
GATK is already upgraded to 4.2.0.0 in the in-progress DSL2 release.

We're currently planning a minor DSL1 release (2.7.1) which unfortunately will not include that, as it's just an update on TEMPLATE and tiny bugfixes.
