### ISSUE TITLE
[FEATURE] GATK GenotypeGVCFs option?

### ISSUE THREAD

**Issue by mvelinder** [nf-core/sarek#392]
It doesn't appear GenotypeGVCFs included in `--tools`? Could it be included in a future version? It's an important step for some larger scale studies. GATK documentation and description: https://gatk.broadinstitute.org/hc/en-us/articles/360037057852-GenotypeGVCFs

Thanks!

**Comment by mvelinder** [comment]
Nevermind, it seems this is included here https://nf-co.re/sarek/2.7.1/output#gatk-genotypegvcfs

**Comment by mvelinder** [comment]
So while it is listed in the link I gave previously, https://nf-co.re/sarek/2.7.1/output#gatk-genotypegvcfs - it does not work with `--tools` . What is the usage for GenotypeGVCFs then?

**Comment by maxulysse** [comment]
Hi @mvelinder `--tools haplotypecaller --generate_gvcf` should do the trick.

**Comment by mvelinder** [comment]
Thanks @maxulysse - from the GATK tool, the output is "A final VCF in which all samples have been jointly genotyped." 

My latest run using `--generate_gvcf` (starting from 3 sets of FASTQ files as a trio exome) did indeed result in a `g.vcf.gz` for each sample. Have these individual GVCFs been jointly genotyped but just not merged into a single output VCF? Would it be appropriate to just `bcftools merge` the 3 individual GVCFs to create a multiple sample joint-genotyped VCF?

Appreciate your help and clarification!

**Comment by maxulysse** [comment]
Hi @mvelinder.
At the moment in sarek the g.vcf are not merged yet, so each g.vcf file you have is from one set of FASTQs.
I'd look more into [GenomicsDBImport](https://gatk.broadinstitute.org/hc/en-us/articles/360036732771-GenomicsDBImport) for merging the resulting g.vcf files.
Hopefully it's something that we'll be able to add to the next sarek release.

**Comment by FriederikeHanssen** [comment]
the GATK recommended workflow for joint genotyping is added here #595 including genomicsdbimport, genotypegvcf, and vqsr
