### ISSUE TITLE
[BUG] Wrong references for files in nextflow.config 

### ISSUE THREAD

**Issue by xhejtman** [nf-core/sarek#393]
https://github.com/nf-core/sarek/blob/master/nextflow.config contains wrong references:
timeline {
  enabled = true
  file = "${params.tracedir}/execution_timeline_${trace_timestamp}.html"
}
report {
  enabled = true
  file = "${params.tracedir}/execution_report_${trace_timestamp}.html"
}
timeline {
  enabled = true
  file = "${params.tracedir}/execution_trace_${trace_timestamp}.txt"
}
trace {
  enabled = true
  file = "${params.tracedir}/pipeline_dag_${trace_timestamp}.svg"
}
dag {
  enabled = true
  file = "${params.tracedir}/pipeline_dag_${trace_timestamp}.svg"
}

trace should not be in .svg file? While timeline is present twice.

**Comment by maxulysse** [comment]
This has been fixed in the `dsl2` branch.

**Comment by xhejtman** [comment]
any chance to fix it also in master? unfortunately, kuberun from nextflow pull master branch and I am not sure how to tell to switch branches.

**Comment by FriederikeHanssen** [comment]
you can provide the fixed parameters it in a custom.config with ```-c``` when you run the pipeline. The dsl2 branch is still in heavy development.
