### ISSUE TITLE
Cannot find `nf-core/sarek`

### ISSUE THREAD

**Issue by ld9866** [nf-core/sarek#399]
nextflow pull nf-core/sarek
Checking nf-core/sarek ...
WARN: Cannot read project manifest -- Cause: Connection reset
Cannot find `nf-core/sarek` -- Make sure exists a GitHub repository at this address `https://github.com/nf-core/sarek`

Hello, I can't use it normally after I input the download command. Would you like to ask if I can download the file to the local separately and then install it later?

**Comment by maxulysse** [comment]
Hi @ld9866 
Quite strange that Nextflow can't seem to resolve this github URL.
You should be able to get it with a simple:
```
git clone https://github.com/nf-core/sarek.git
```
But as far as I'm aware, that's exactly what Nextflow is doing...

If this is not working for any reason, please have a look at the releases page: https://github.com/nf-core/sarek/releases
