### ISSUE TITLE
[BUG] MARKDUPLICATES -> QC_MARKDUPLICATES

### ISSUE THREAD

**Issue by nickhsmith** [nf-core/sarek#409]
I recently reinstalled sarek from scratch using the test run command
`nextflow run nf-core/sarek -profile test,singularity -r dsl2 -resume` 

And I believe there is a typo as a result of the recent "code clean up" commit (July 15 @FriederikeHanssen ) the `MARKDUPLICATES` subworkflow was renamed to `QC_MARKDUPLICATES` however on lines 341 and 343 of the sarek.nf workflow still use the name `MARKDUPLICATES` to generate the cram_markduplicates channel, and qc_reports. 

As a result, the pipeline can not continue as written. Locally I renamed the commands on lines 341, 343 and was able to get it running again. I imagine this was a missed typo, but regardless I wanted to point it out.

Thanks for all of your hard work, and I look forward to using sarek more and more often.

**Comment by FriederikeHanssen** [comment]
Thank you! Never a good idea to rename something quickly when the CI test are not running 🤦‍♀️ . I'll fix it.

**Comment by maxulysse** [comment]
#408 should be taking care of that
