### ISSUE TITLE
Mutetc2 on aws and ConcateVCF 

### ISSUE THREAD

**Issue by varun171** [nf-core/sarek#413]
I tried to run pipeline on AWS several time but failed due to Mutect2 and concateVCF.
[sarek-issue-mutect2.txt](https://github.com/nf-core/sarek/files/6861985/sarek-issue-mutect2.txt)
[Sarek-issue-concanvcf.txt](https://github.com/nf-core/sarek/files/6861986/Sarek-issue-concanvcf.txt)

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: nextflow run 'https://github.com/nf-core/sarek'
		 -name tiny_celsius
		 -params-file nf-3fIGCIZ9boB5R5.params.json
		 -with-tower
		 -r 68b9930a74962f3c42eee71f51e6dd2646269199
		 -resume a62adcf8-3b18-4d01-acf9-656cdf20da21
2. See error: Please see attached files.

**Comment by maxulysse** [comment]
@varun171 Which genome are you running Mutect2 with?
I'm afraid Mutect2 needs a germline ressource file to properly function, which might not be available depending on the genome

**Comment by varun171** [comment]
I am running human genome files and I realized PON datafile from GATK does not work in AWS. It is only for GCP.

**Comment by maxulysse** [comment]
You should be able to have the files on your own s3 bucket and specify them on the command line with --pon and/or --germline_ressource
