### ISSUE TITLE
[BUG] using with custom genome

### ISSUE THREAD

**Issue by xiaoyunguo** [nf-core/sarek#414]
Hi,
I tried to use the Sarek pipe line with costume genome, without dbSNP or known indels. I couldn't make it work with the following, wonder if this pipeline is capable of doing it or did I do it wrong? Thanks!

nextflow run /path/variant_calling/sarek \
-profile docker \
--tools Manta, Strelka \
--input  ${input} \
--outdir ${sarek_result} \
--genome "custom" \
--fasta ${ref_fa} \
--bwa $bwa \
--fasta_fai ${fa_fai} \
--email ${email} \
--max_cpus 16 \
--publish_dir_mode "copy" \
-with-report report.html

**Comment by maxulysse** [comment]
@xiaoyunguo 
I ran:
```
nextflow run nf-core/sarek -r 2.7.1
    -profile docker,test
    --genome custom
    --fasta https://raw.githubusercontent.com/nf-core/test-datasets/sarek/reference/human_g1k_v37_decoy.small.fasta
    --tools manta,strelka
```
without issue, what was your exact command line, and what was your sarek version?

**Comment by xiaoyunguo** [comment]
Thanks. I think the difference from this test case for me is that I am not working with human genome. Not sure if that makes a difference or not. 

Here is the command I am using:

nextflow run nf-core/sarek \
-profile docker \
--fasta '/path/Sus_scrofa.Sscrofa11.1.dna.chromosome.MT.fa' \
--input '/path/mtDNA_input.tsv' \
--outdir '/path/mtDNA/results' \
--tools manta, Strelka \
--skip_qc all \
--save_bam_mapped \
--no_strelka_bp \
--igenomes_ignore \
--cpus 16 \
--email myemail@xxx.com

This is the error message I got:
----------------------------------
Error executing process > 'CreateIntervalBeds (wgs_calling_regions.hg38.bed)'

Caused by:
  Process `CreateIntervalBeds (wgs_calling_regions.hg38.bed)` terminated with an error exit status (2)

Command executed:

  awk -vFS="    " '{
    t = $5  # runtime estimate
    if (t == "") {
      # no runtime estimate in this row, assume default value
      t = ($3 - $2) / 1000
    }
    if (name == "" || (chunk > 600 && (chunk + t) > longest * 1.05)) {
      # start a new chunk
      name = sprintf("%s_%d-%d.bed", $1, $2+1, $3)
      chunk = 0
      longest = 0
    }
    if (t > longest)
      longest = t
    chunk += t
    print $0 > name
  }' wgs_calling_regions.hg38.bed

Command exit status:
  2

Command output:
  (empty)

Command error:
  awk: cannot open wgs_calling_regions.hg38.bed (No such file or directory) 
---------------------

It somehow still tried to find some hg38 reference bed file. 

Thanks

**Comment by maxulysse** [comment]
@xiaoyunguo 
You hould have both options in your command line:
`--genome custom --igenomes_ignore`

**Comment by FriederikeHanssen** [comment]
Closed due to inactivity. Please re-open, if you have more questions.

**Comment by hhefzi** [comment]
Something in the docs about including both flags (--genome custom --igenomes_ignore) if using a custom genome would be useful.

**Comment by maxulysse** [comment]
We updated that in the coming `3.0` release, and we'll update the docs regarding that matter
