### ISSUE TITLE
SNPEff completes successfully for custom genomeswith mismatching chromosome names causing empty reports

### ISSUE THREAD

**Issue by ggabernet** [nf-core/sarek#415]
Hi, 

I'm having two different issues with the Sarek MultiQC report that I'm not sure how to solve.

Regarding pipeline versions: I'm using Sarek v2.7.1, with singularity containers (which uses MultiQC1.8).

The first issue is that no results are shown for the SnpEff module and this I observed with two independent analyses already, when using custom genome snpEff cache.

![Screenshot 2021-07-27 at 14 13 26](https://user-images.githubusercontent.com/3973503/127153013-3b000485-e0a0-4c0c-91e6-649c758cb772.png)

The other issue appears for one of the projects for me and not for the other, and it is that the MultiQC report is stuck at "loading" the plots, and no plots are shown, only gray boxes. The same issue persists even when making a fresh re-run of the pipeline to generate a new MultiQC report.

![Screenshot 2021-07-27 at 14 28 46](https://user-images.githubusercontent.com/3973503/127153722-d0976099-f4ab-402e-939c-987a8599da5b.png)

I can send you privately the multiqc report, GitHub does not let me upload it here.

Command used to run the analysis:
```
nextflow run nf-core/sarek -r 2.7.1 -profile cfc \
--input input.tsv \
--fasta "/sfs/7/workspace/ws/qeaga01-QWTPM-0/references/ncbi-genomes-2021-07-16/GCA_000750555.1_ASM75055v1_genomic_Ecoli_BW25113.fa" \
--tools strelka,snpeff \
--step mapping \
--igenomes_ignore \
--genome custom \
--bwa false \
--no_gatk_spark \
--snpeff_cache /sfs/7/workspace/ws/qeaga01-QWTPM-0/Ecoli_BW25113/reference/ \
--annotation_cache true \
--snpeff_db Escherichia_coli_bw25113
```

NXF_VER=20.10.0

**Comment by maxulysse** [comment]
ok, so for the custom snpeff, I'm not sure, but I'll do some test.
For the no value, I assume there could be an empty value that is not understood well by MultiQC which results in it not being able to do anything in the end.
I'd try if the same thing happen with a newer MultiQC version.
Thanks for raising these issues.

**Comment by mGauder** [comment]
Hi there,

I also have the issue with the snpeff plots in the MultiQC report, but with v2.7.
![Screenshot 2021-07-28 at 11 35 15](https://user-images.githubusercontent.com/9446153/127328576-cd6d384c-f59b-4bcf-99c6-1f82404a5e70.png)

For another project with custom genome snpEff cache and version 2.6.1, there were no issues with the snpeff plots in the MultiQC report.

Hope this helps to narrow it down.

Best,
Marie

**Comment by ggabernet** [comment]
Hi @maxulysse and @mGauder , thanks for your help. I have tested it for Sarek `v2.6.1` but I had the same issue that the MultiQC report won't load for one of the projects, but it does for the other one. Super weird! I'll keep you posted if I find the reason why...

**Comment by ggabernet** [comment]
Hi @maxulysse ,

installing locally MultiQC v1.11 and running MultiQC in the work folder solved the issue, so a version update for the next Sarek release would solve the loading issue.

However the SnpEff module for custom reference data seems to be broken also in `MultiQC v1.11`. If that is MultiQC specific, I can also open an issue there :)

**Comment by maxulysse** [comment]
> installing locally MultiQC v1.11 and running MultiQC in the work folder solved the issue, so a version update for the next Sarek release would solve the loading issue.

Easy fix then ;-)

> However the SnpEff module for custom reference data seems to be broken also in `MultiQC v1.11`. If that is MultiQC specific, I can also open an issue there :)

That would be amazing :-)

**Comment by FriederikeHanssen** [comment]
the issue with external cache for snpEff seems to persist.

**Comment by FriederikeHanssen** [comment]
I am starting to suspect that something is happening upstream, since parts of the plot is loaded, so it is not a problem that MultiQC can't find the snpeff files. @ggabernet I couldn't find a relating issue on MultiQC, did you ever follow up there?

**Comment by FriederikeHanssen** [comment]
After some digging with @LaurenceKuhl I got reports with custom genomes where everything worked fine and some that don't. Whenever it fails the following error shows up:
```

ERRORS: Some errors were detected
Error type      Number of errors
ERROR_CHROMOSOME_NOT_FOUND      17522411

```
in Snpeff already and MultiQC just gets an empty report. My best guess is that something is off with the custom SNPeff DB and fasta not matching: https://pcingola.github.io/SnpEff/se_faq/#error_chromosome_not_found-details SNPEff unfortuantely completes without throwing an actual error. I could try to see if we can catch it somehow.
