### ISSUE TITLE
[BUG] Error downloading nf-core/sarek

### ISSUE THREAD

**Issue by ld9866** [nf-core/sarek#421]
hello! l have installed docker version sarek through print "docker pull nfcore/sarek" and it was done successfully.
Besides,  l install nextflow through conda and it can successfully run. But when l print " nextflow run nf-core/sarek -profile docker" it showed that
N E X T F L O W  ~  version 21.04.3
Unknown project `nf-core/sarek` -- NOTE: automatic download from remote repositories is disable.
l'd like to ask how can l solve it ?
thank you!

**Comment by ld9866** [comment]
logfile:
16:54:43.019 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/sarek
16:54:43.186 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.04.0
16:54:43.237 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Unknown project `nf-core/sarek` -- NOTE: automatic download from remote repositories is disabled
        at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:366)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:265)
        at nextflow.cli.Launcher.run(Launcher.groovy:475)
        at nextflow.cli.Launcher.main(Launcher.groovy:657)

**Comment by maxulysse** [comment]
I'm afraid this a [nextflow-io](https://github.com/nextflow-io/nextflow/) issue.
It appears that you can't download repositories on your system.
How was Nextflow installed?

**Comment by ld9866** [comment]
I installed through conda and this command 'curl -fsSL https://get.nextflow.io | bash' , they are both work but can't download repositories

**Comment by maxulysse** [comment]
Definitively a Nextflow issue, I'd recommend either asking on the [Nextflow gitter](https://gitter.im/nextflow-io/nextflow), or opening an issue on the [nextflow-io](https://github.com/nextflow-io/nextflow/) repo.

**Comment by maxulysse** [comment]
We made some documentation about how to get started with our pipelines: https://nf-co.re/usage/introduction

**Comment by ld9866** [comment]
OK! Glad to receive your reply! l will try to open an issue on the NetFlow-io repo.

**Comment by maxulysse** [comment]
Good luck, don't hesitate to reopen or comment this issue if we can help you out ;-)
