### ISSUE TITLE
how to control the number of maximum files in a HPC with lustre and slurm from sarek

### ISSUE THREAD

**Issue by smzt** [nf-core/sarek#423]
Hi!
I'm trying to process 36 whole-genome samples in an HPC cluster with slurm and a lustre filesystem. Sarek runs perfectly well with one sample but when it comes to analyze the whole cohort then it parallelizes so match that it reaches the maximum number of files allowed for the user, which is currently set to 200,000. Is there any way to control the number of maximum files that it can write with sarek for this type of cluster?

Thanks in advance.

S.

**Comment by maxulysse** [comment]
Hi @smzt sorry for the late reply.
I'm afraid I'm not aware of such settings in the configuration, but maybe it's possible within Nextflow, did you check the Nextflow docs?
