### ISSUE TITLE
Nextfow tower[BUG]

### ISSUE THREAD

**Issue by luantunez** [nf-core/sarek#424]
I cannot use Sarek in Nextfow Tower, is this profile available? How can I point the lauchpad to my s3 bucket where I have the tsv? do I need to use fusion for this?
Thank you in advance!

**Comment by FriederikeHanssen** [comment]
You don't need a tower profile to run it there. Works out of the box. For how to set up tower to run with AWS, take a look here: https://help.tower.nf/compute-envs/aws-batch/  Then just set `--input 's3://here/is/my/tsv` 
Personally, I use fusion, have found it to be much more stable.
