### ISSUE TITLE
bamQC runtime exceeded [BUG]

### ISSUE THREAD

**Issue by giesselmann** [nf-core/sarek#425]
Hi there!

I have a problem running the sarek pipeline, the bamQC jobs get canceled after a day and I'm failing to increase the runtime either via command line or config file.

## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/sarek pipeline documentation](https://nf-co.re/sarek/usage)

## Description of the bug

I'm running the pipeline with either
>--max_time '4.day'

or a config file:

>process { withLabel: 'BamQC' {   time = '96h'  }}

Ressources of the machine seem to be correctly determined:
>Max Resources     : 128 GB memory, 16 cpus, 10d time per job

And bamQC is almost making it, before getting cancled after 1d of runtime (last line from job output):
>Processed 450 out of 485 windows...

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 
>nextflow run nf-core/sarek -profile conda -c params.config --input input.tsv --genome GRCh37 --resume
2. See error: 
See also nextflow.log (line 4135)

>'BamQC (HCT116-HCT116_1_1)'
>Caused by:
>Process exceeded running time limit (1d)
>Command executed:
>qualimap --java-mem-size=128G         bamqc         -bam HCT116_1_1.bam         --paint-chromosome-limits         --genome-gc-distr HUMAN                  -nt 16         -skip-duplicated         --skip-dup-mode 0         -outdir HCT116_1_1         -outformat HTML

## Expected behaviour

I assumed either command line or config file should be able to change the bamQC runtime.

## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline
- [x] The `.nextflow.log` file 
[nextflow.log](https://github.com/nf-core/sarek/files/7005681/nextflow.log)

## System

- Hardware: 
Server, 1TB RAM, 128 cores
- Executor: 
Local
- OS: 
Mariux (in-house linux)
- Version 

## Nextflow Installation

- Version: 
21.04.1.5556

## Container engine

- Engine: 
Conda
- version: 
4.9.0
- Image tag: 
nf-core/sarek v2.7

**Comment by giesselmann** [comment]
Hi,
can anyone help? We're still stuck in processing our samples due to the runtime limit.
Pay

**Comment by FriederikeHanssen** [comment]
Hi @giesselmann! Sorry didn't see this before. Could you post your complete config file?

**Comment by giesselmann** [comment]
Hi,
it's online the posted line:
process { withLabel: 'BamQC' { time = '96h' }}
We're currently trying the same with 'withName'. I'm not familiar with nextflow at all, sorry.
Thanks for help,
Pay

**Comment by FriederikeHanssen** [comment]
ah yes, it should work with:

```
process{
      withName:'BamQC'{
            time = '96.h'
     }
}
```

`--max_time --max-cpus` etc.  only sets a maximum to prevent nextflow to request more than for example available on your cluster, but does not increase the resources for an individual process. There is a bit of documentation here https://nf-co.re/usage/configuration?q=--max_cpus#max-resources

**Comment by giesselmann** [comment]
It does, thanks for the support!
