### ISSUE TITLE
Allow saving of BAM files in 3.0

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#437]

**Comment by FriederikeHanssen** [comment]
Module exist. Idea here: allow to output bam files still with a flag such as `--save_as_bam`

**Comment by FriederikeHanssen** [comment]
This would possibly be a lot more tricky then I anticipated. Essentially none of the processes should publish anymore. Instead we need to collect the output and transform it. Simultaneously we need to either track a lot of info to make sure the bam files end up in the correct result directory or add the cram-to_bam module for each process.

**Comment by maxulysse** [comment]
As we have most of the pipeline in cram already, shouldn't we just go for a cram_to_bam modules on the recalibrated bam

**Comment by FriederikeHanssen** [comment]
what about the duplicate marked crams? We are also saving those at the moment.
Ok I guess it is actually only in two places afterall + some logic around the duplicate marking because it can output either bams or crams

**Comment by maxulysse** [comment]
forgot about these...
