### ISSUE TITLE
How to remove temp dir(work dir) in one command

### ISSUE THREAD

**Issue by parkjaeming** [nf-core/sarek#443]
Hello,
I am studying bioinformatics with your sarek pipeline and it has been helpful for me so far!
While using your sarek, I have faced a problem that needs your attention.
I want to properly deal with the disc space by removing temp dir(work dir) in one command line like below!
`
nextflow run nf-core/sarek \
-r 2.7.1 \
-profile test, docker \
**--clean true**
`
So, I tried using `hidden_params` parameter, but there were no parameters related with my concern about disc.
Can you recommend any other options? I would really appreciate your precious piece of advice.

**Comment by priesgo** [comment]
Is that `cleanup=true` still working? I read somewhere they may remove it...

**Comment by FriederikeHanssen** [comment]
possible, I couldn't find anything about either scenario. I guess easiest would be to try it out

**Comment by parkjaeming** [comment]
Thank you for all your attention!
I also heard that `cleanup=true` is not working well...
It seems that the best way is to clean up the temp file manually after the all pipelines...
