### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by j-schoenebeck** [nf-core/sarek#450]
Hello,

I am new to nf-core's Sarek pipeline. Currently I am simply trying the test configurations to make sure that its processes run on our cluster. All test configurations appear to run except 'test_full':

`nextflow run nf-core/sarek -revision 2.7.1 -profile test_full,singularity`

This generates the following message:

N E X T F L O W  ~  version 21.04.3
Launching `nf-core/sarek` [mad_kirch] - revision: 68b9930a74 [2.7.1]
Unknown configuration profile: 'test_full'

Did you mean one of these?
    test_tool

**Comment by maxulysse** [comment]
Hi @j-schoenebeck,
I'm glad you manage to make it work so well.
test_full hasn't been fully implemented yet for sarek, so it's normal it's not working at the moment.
