### ISSUE TITLE
[BUG] step functionality

### ISSUE THREAD

**Issue by nickhsmith** [nf-core/sarek#451]
## Description
**In the dev branch**:
When using the `step` functionality, I noticed a disconnect between the allowed values in `nextflow_schema.json` and the `worfkflows/sarek.nf` code. In the nextflow_schema, values have an '_' separating `variant_calling`, and `prepare_recalibration` while in the workflow they are designated without the separator (variantcalling, and preparerecalibration). This leads to an enum error when designating steps.

## Steps to reproduce

nextflow run nf-core/sarek -profile test,conda --step variantcalling -r dev

## Suggestion
By editing my local version of `nextflow_schema.json` (can I have a 2nd one that overrides the version packaged with SAREK?) to remove the `_` things work as expected.

## Other note
The sarek code seems to allow for an automatic csv input detection when using the step functionality to restart a run for just a given step. However the input is a mandatory input, and SAREK won't run without it, rendering this part essentially useless as far as I can tell. Let me know if I've misread the step case switching block in `workflows/sarek.nf` lines 48-60

Thanks

**Comment by maxulysse** [comment]
Actually, in the `workflows/sarek.nf`, prior to these lines (cf https://github.com/nf-core/sarek/blob/8b6571540322e2d1568717de607f67dd2744d63a/workflows/sarek.nf#L43-L45), we're stripping the params out of `-` and `_`.
So internally the step values should correspond to the ones in the json.
But since we're having this schema, maybe we can actually remove some of this part, that's a valid point.

**Comment by nickhsmith** [comment]
Ok I see now. Thanks for the clarification. As for the automatic input and step case csv finding. I think that point still stands, that input must be defined so you don't use the case switching (although I'd love to be mistaken on that too!).

Thanks

**Comment by maxulysse** [comment]
It was working before we updated the schema, so it might actually be not working anymore, I'll check this out.
Thanks a lot for pointing that out.
