### ISSUE TITLE
Error of Java Runtime Environment

### ISSUE THREAD

**Issue by idewdewi** [nf-core/sarek#452]
A fatal error has been detected by the Java Runtime Environment:
SIGBUS (0x7) at pc=0x00007fd2a496e74a, pid=13426, tid=0x00007fd23caf1700
JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-b01)
Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
 Problematic frame:
C  [libc.so.6+0x15c74a]
Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

`ulimit -c unlimited`
module load nextflow/v21.04.3
module load singularity/v3.8.1
nextflow run nf-core/sarek -profile singularity   --input sample.tsv --genome GRCh38

Server is HPC, slurm, Debian4.19

**Comment by maxulysse** [comment]
Hi @idewdewi, can you elaborate a bit more please?
For example for witch process did this error appeared?

**Comment by idewdewi** [comment]
Sure, it's the beginning to run the pipeline, 
#!/bin/bash
ulimit -c unlimited
module load nextflow/v21.04.3
module load singularity/v3.8.1
nextflow run nf-core/sarek -profile singularity --input sample.tsv --genome GRCh38

**Comment by idewdewi** [comment]
Thanks a lot!

Maybe nextflow v21.04.3 is too new version for the use. Will check with the nextflow site. 

Best,

**Comment by maxulysse** [comment]
Good luck.
Otherwise, if you still have issues, don't hesitate to ask in our help channel on our Slack.

**Comment by idewdewi** [comment]
OK, got it. Thank you very much, appreciate!
