### ISSUE TITLE
[BUG] Tools using Log4j

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#470]
- [ ] GAWK
- [ ] BCFTools (no, c)
- [ ] Deepvariant (python/c++, not)
- [x] GATK4  ( https://github.com/broadinstitute/gatk/search?q=log4j, issue already here: https://github.com/broadinstitute/gatk/pull/)
- [ ] MSISensor (not, c++)
- [x] Qualimap (maybe, maybe not)
- [ ] Samtools ( not, c++)
- [ ] BWA/BWAMEM2 ( not, c+=)
- [ ] Ensembl VEP ( not, perl)
- [x] FastQC ( not, maybe upstream dependency on picard?)
- [ ] FreeBayes ( not, c++)
- [ ] Manta ( not, c++)
- [ ] MultiQC ( not , python)
- [ ] Seqkit ( not, go)
- [ ] Strelka ( not, c++)
- [ ] Tabix ( not, c)
- [ ] TrimGalore (not, perl)

Looked a bit into the repositories of the tools we have on `dev` currently. I think the biggest problem is gatk4, but please correct me if I am wrong, certainly no expert here. Maybe FastQC and Qualimap as well

**Comment by maxulysse** [comment]
https://www.youtube.com/watch?v=zXVBK38-650

**Comment by FriederikeHanssen** [comment]
Based on discussion on slack, assume everything is bad and update everything. However the java modules are all in nf-core/modules, so update there as soon as the tools have merged their fixes and then here

**Comment by FriederikeHanssen** [comment]
So GATK4 ones are all fixed. Qualimap uses an old version of log4j: https://nfcore.slack.com/archives/CJRH30T6V/p1639590313305000 (not the affected one, but I am not sure that the old version won't have other issues, I don't see what we can do though at the moment, since it requires an upstream fix)

fastQC seems fine (see FastQC repo issue 85)

**Comment by FriederikeHanssen** [comment]
I think we are good here
