### ISSUE TITLE
[BUG] modules.config: publishDirmode: 'copy'

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#471]
When changing the publishDir mode, `copy` needs to be stated explicitly everywhere.

see: https://nfcore.slack.com/archives/CGFUX04HZ/p1639391495442600?thread_ts=1639041878.432300&cid=CGFUX04HZ

**Comment by maxulysse** [comment]
I don't remember where, but I saw a pipeline, where they kept the params.publishdirmode and used it instead of having to change to copy everywhere.
I think it's a good idea, it'll allow to change all publishdirmode at once.
Maybe something to think about in the template?
