### ISSUE TITLE
Get Software Versions crashes -- unknown error

### ISSUE THREAD

**Issue by KwameForbes** [nf-core/sarek#486]
> /pine/scr/k/w/kwamek/AlexRotation/nextflow -bg run nf-core/sarek --input Illumina_whole-genome_seq_data.tsv -profile singularity --max_cpus 10

Error executing process > 'get_software_versions'
Caused by:
 Process requirement exceed available CPUs -- req: 8; avail: 1
Command executed:
 alleleCounter --version &> v_allelecount.txt 2>&1 || true
 bcftools --version &> v_bcftools.txt 2>&1 || true
 bwa version &> v_bwa.txt 2>&1 || true
 cnvkit.py version &> v_cnvkit.txt 2>&1 || true
 configManta.py --version &> v_manta.txt 2>&1 || true
 configureStrelkaGermlineWorkflow.py --version &> v_strelka.txt 2>&1 || true
 echo "2.7.1" &> v_pipeline.txt 2>&1 || true
 echo "21.10.6" &> v_nextflow.txt 2>&1 || true
 snpEff -version &> v_snpeff.txt 2>&1 || true
 fastqc --version &> v_fastqc.txt 2>&1 || true
 freebayes --version &> v_freebayes.txt 2>&1 || true
 freec &> v_controlfreec.txt 2>&1 || true
 gatk ApplyBQSR --help &> v_gatk.txt 2>&1 || true
 msisensor &> v_msisensor.txt 2>&1 || true
 multiqc --version &> v_multiqc.txt 2>&1 || true
 qualimap --version &> v_qualimap.txt 2>&1 || true
 R --version &> v_r.txt 2>&1 || true
 R -e "library(ASCAT); help(package='ASCAT')" &> v_ascat.txt 2>&1 || true
 samtools --version &> v_samtools.txt 2>&1 || true
 tiddit &> v_tiddit.txt 2>&1 || true
 trim_galore -v &> v_trim_galore.txt 2>&1 || true
 vcftools --version &> v_vcftools.txt 2>&1 || true
 vep --help &> v_vep.txt 2>&1 || true
 scrape_software_versions.py &> software_versions_mqc.yaml
Command exit status:
 -
Command output:
 (empty)
Work dir:
 /pine/scr/k/w/kwamek/AlexRotation/work/f1/9d44ad544ccdac7d463c51f7456441
Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Execution cancelled -- Finishing pending tasks before exit

**Comment by maxulysse** [comment]
Hi @KwameForbes 
Can you please provide more information?

**Comment by KwameForbes** [comment]
Hi @maxulysse 
I am using my university's cluster to used the sarek pipe on dataset using profile singularity:
**_/pine/scr/k/w/kwamek/AlexRotation/nextflow -bg run nf-core/sarek --input Illumina_whole-genome_seq_data.tsv -profile singularity --max_cpus 10_**

- I used the absolute path to nextflow because I downloaded the most recent version
- I used --max_cpus 10 to try and handling the _Process requirement exceed available CPUs -- req: 8; avail: 1_  error but it didn't work

**Comment by maxulysse** [comment]
Hi @KwameForbes can you give the .command.err and the .command.log files in ` /pine/scr/k/w/kwamek/AlexRotation/work/f1/9d44ad544ccdac7d463c51f7456441` so we can assess more what was the actual issue

**Comment by KwameForbes** [comment]
Whenever I run the code the work dir is always empty.

**Comment by maxulysse** [comment]
even with a `ls -la` to see hidden files?

**Comment by KwameForbes** [comment]
yes

**Comment by maxulysse** [comment]
Wait, the error you have is always the `Process requirement exceed available CPUs -- req: 8; avail: 1`

**Comment by KwameForbes** [comment]
yes

**Comment by maxulysse** [comment]
ok, so this issue will not be solve by limiting the amount of cpus to 10 as the number of cpus available on your system is actually just 1.
May I ask what is your setting?

**Comment by KwameForbes** [comment]
what do you mean by setting?
