### ISSUE TITLE
[BUG] Somatic variant calling with non-unique runID variable error

### ISSUE THREAD

**Issue by Hynst** [nf-core/sarek#499]
Hi,

We are experiencing difficulties when running somatic variant detection for samples defined in a input tsv e.g.:

Patient1 XX 1 sample1 HHK55CCXX sample1_wgs_HHK55CCXX_lane1_R1_fastq.gz sample1_wgs_HHK55CCXX_lane1_R2_fastq.gz
Patient1 XX 0 sample2 HHK55CCXX sample2_wgs_HHK55CCXX_lane1_R1_fastq.gz sample2_wgs_HHK55CCXX_lane1_R2_fastq.gz

The variable idRun in main.nf is set as HHK55CCXX for both the tumour and normal samples. This is used as the ID-tag of Read Groups in the MapReads process. A subsequent freebayes analysis produces the following error:

_ERROR(freebayes): multiple samples (SM) map to the same read group (RG)
samples sample1 and sample2 map to HHK55CCXX
As freebayes operates on a virtually merged stream of its input files, it will not be possible to determine what sample an alignment belongs to at runtime.
To resolve the issue, ensure that RG ids are unique to one sample across all the input files to freebayes.
See bamaddrg (https://github.com/ekg/bamaddrg) for a method which can add RG tags to alignments._

A workaround is to add index to flow cell ID like so: HHK55CCXX_1 and HHK55CCXX_2. However, since it is evident from the .tsv that the two samples are tumor/normal (column 3 - 1/0), we believe that a more foolproof solution would be to build the RGID (idRun variable) in a more unique way, e.g. in the same way, as it is built when specifying input in the "path to files" form: https://nf-co.re/sarek/2.7.1/usage#input-ltsamplegt---step-mapping
...
RGID = "sample_lib_flowcell_index_lane"

Kuba

**Comment by FriederikeHanssen** [comment]
@Hynst very sorry for the late reply. The laneID for the current version must be unique. https://github.com/nf-core/sarek/issues/311 

I will close this issue because it is the same as the linked one. Will be fixed in 3.0
