### ISSUE TITLE
Document how to use sarek without an igenomes genome

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#504]
Document how to use sarek without an igenomes genome in different stages:
- [x] no BWA Indices
- [x] no known indels
- [x] snpEff/VEP on another organism.

Lots of people have problems figuring out how to do this.
We should come up with a better of explaining it.

**Comment by gorgitko** [comment]
Hello, I would also suggest to document the used iGenomes files, i.e. what is their origin, by which tools in the pipeline are they used / what is their purpose, etc.

Thanks! :heart:

**Comment by maxulysse** [comment]
Duplicate of #291 

But nowaways, basically, we need to do:
`--genome null --igenomes_ignore` and specify all necessary files.

**Comment by FriederikeHanssen** [comment]
@gorgitko I added a table for the origin of the reference genomes now in #673
