### ISSUE TITLE
Select only somatic/germline[FEATURE]

### ISSUE THREAD

**Issue by jgarces02** [nf-core/sarek#509]
In order to speed up the (wonderful!) _Sarek_ pipeline, could be it considered to add an option to process somatic *OR* germline variants and not all indistinctly?

Maybe something like `--step somatic/germline`?

Thanks

**Comment by FriederikeHanssen** [comment]
So you mean if ther is tumor-normal pair, to not run the germline samples separatly, right?

Sure that we can add :) Maybe not next release but the one after

**Comment by jgarces02** [comment]
Exactly! Thanks a lot!
