### ISSUE TITLE
[FEATURE] RNA-Seq Support

### ISSUE THREAD

**Issue by JasperO98** [nf-core/sarek#517]
Hey, all. I'm working on a project with tumor-only samples. These tumor samples have been sequenced using WES and RNA-Seq, however we don't have WES data for all samples. Therefore, I would like to be able to do variant calling on the RNA-Seq samples to see if we can find some interesting variants in those samples.

I already have an idea how to do this. Since sarek already follows the GATK best practices for pre-processing I thought it would be best to also follow the same GATK best practices for RNA-Seq variant calling described [here](https://gatk.broadinstitute.org/hc/en-us/articles/360035531192-RNAseq-short-variant-discovery-SNPs-Indels-).
This includes mapping with STAR 2-Pass, Marking Duplicates (already in sarek), and SplitNCigarReads.

STAR could also be replaced by HISAT2, since STAR is quite an computational intensive tool. However, then Mutect2 might not be able to run anymore..

After these pre-processing steps the workflow should run as if it is using WES data or would that introduce problems I'm currently not foreseeing?

**Comment by FriederikeHanssen** [comment]
I believe you are looking for the rnavar pipeline in developement https://github.com/nf-core/rnavar

**Comment by maxulysse** [comment]
Hi @JasperO98, I can see why you have this idea, but our motto in nf-core is one pipeline per data type (and not doing too much), so unfortunately we won't add RNA-seq to sarek.
But good news, @praveenraj2018 is working on a GATK4 best practices pipeline for Variant Calling, and the `dev` branch is mature enough: https://github.com/nf-core/rnavar/

**Comment by maxulysse** [comment]
> I believe you are looking for the rnavar pipeline in developement https://github.com/nf-core/rnavar

you were faster to reply ;-)
