### ISSUE TITLE
[BUG] * --vep_cache_version: expected type: String, found: Integer (99)

### ISSUE THREAD

**Issue by leipzig** [nf-core/sarek#518]
## Check Documentation

I have checked the following places for your error:

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core/sarek pipeline documentation](https://nf-co.re/sarek/usage)

## Description of the bug

`* --vep_cache_version: expected type: String, found: Integer (99)`

## Steps to reproduce

Steps to reproduce the behaviour:
```
./nextflow run sarek-2.7.1  \
--input tiny-manta-https.gcs.tsv 	 \
--step 'mapping'	 \
--outdir './results'			 \
--nucleotides_per_second 1000.0												 \
--aligner 'bwa-mem'	 \
--markdup_java_options '-Xms4000m -Xmx7g'						 \
--cf_coeff 0.05			 \
--cf_ploidy 2.0																				 \
--genome 'smallGRCh37'																	 \
--snpeff_db 'WBcel235.86'	 \
--species 'caenorhabditis_elegans'	 \
--igenomes_base 's3://ngi-igenomes/igenomes'	 \
--genomes_base 'raw.githubusercontent.com/nf-core/test-datasets/sarek/reference'	 \
--igenomes_ignore  		 \
--publish_dir_mode 'copy'		 \
--validate_params  			 \
--max_multiqc_email_size '25.MB'			 \
--tracedir './results/pipeline_info'			 \
--cpus 8	 \
--single_cpu_mem '7 GB'	 \
--max_cpus 16	 \
--max_memory '128.GB'	 \
--max_time '240.h'	 \
--custom_config_version 'master'	 \
--vep_cache_version '99'		 \
--custom_config_base 'https://raw.githubusercontent.com/nf-core/configs/master'	 \
-w gs://somebucket
```

## Expected behaviour

not treat `vep_cache_version` as numeric when it is quoted

## Log files

- [X] The command used to run the pipeline

## System

- Hardware: GCP
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: nextflow version 21.10.6.5660

## Container engine

- Engine: Docker in GCP LS
- Image tag: sarek 2.7.1 

## Additional context

there is no type of quote that will solve this to my knowledge

**Comment by tdanhorn** [comment]
Don't know what OS/shell you are using, but Unix shells strip the quotes, so nextflow (or the pipeline) never gets to see them, i.e it makes no difference (in this case) if you put them there.  If you really want quotes to be seen by the pipeline, `\'99\'` or `"'99'"` should do the trick.  On the other hand, if something should be read as a string and the code autodetects a number and complains, because it thinks it is smarter than you, I'd call that a bug.

**Comment by maxulysse** [comment]
@leipzig sorry for late reply.
As @tdanhorn said, it is indeed a bug which is fixed on the current `dev`.

**Comment by FriederikeHanssen** [comment]
Hm I think there is still something :fish: going on with the vep_cache_version number:

```

ERROR: Validation of pipeline parameters failed!
* --vep_cache_version: expected type: Number, found: String (104)
```

when running:

```
nextflow run nf-core/sarek -r dev -profile cfc \
--input samplesheet.csv \
--outdir ./results \
--genome GATK.GRCh38 \
--aligner bwa-mem2 \
--bwa false \
--save_reference \
-resume
```
Dev version: `5d0a0b9755`
