### ISSUE TITLE
PBS killing job because VMEM exceeding allotted resources

### ISSUE THREAD

**Issue by vincentye2** [nf-core/sarek#541]
Hi there,

I'm trying to run sarek through our institution HPC. In my bash script I have assigned:

nodes=1:ppn=20
gres=localhd:100
mem=200g
vmem=200g

I'm launching the pipeline in my bash script using this command:

nextflow run nf-core/sarek --input ./results/Preprocessing/TSV/duplicates_marked_no_table.tsv --step 'prepare_recalibration'  --genome GRCm38 --path/to/ref -profile singularity --cpus 16 --single_cpu_mem '7 GB'

The --max_memory and --max_cpus are left at default and this should be well within the 200g limit I've set.

However my job is quickly killed by PBS for exceeding resource limit. I've tried to look through the documentation but I'm not sure how to limit the memory allocation further so that this doesn't happen.

> PBS Job Id: 75736704
Job Name:   sarekRecal
Exec host:  node450/0-19
Aborted by PBS Server
Job exceeded a memory resource limit (vmem, pvmem, etc.). Job was aborted
See Administrator for help
Exit_status=-10
resources_used.cput=00:17:35
resources_used.vmem=286793240kb
resources_used.walltime=00:12:06
resources_used.mem=37296368kb
resources_used.energy_used=0
req_information.task_count.0=1
req_information.lprocs.0=20
req_information.total_memory.0=209715200kb
req_information.memory.0=209715200kb
req_information.total_swap.0=209715200kb
req_information.swap.0=209715200kb
req_information.thread_usage_policy.0=allowthreads
req_information.hostlist.0=node450:ppn=20
req_information.task_usage.0.task.0={"task":{"cpu_list":"0-19","mem_list":"0","cores":0,"threads":20,"host":"node450"}}

**Comment by maxulysse** [comment]
I'm assuming it's `--igenomes_base /path/to/ref`

**Comment by vincentye2** [comment]
Yes sorry it is in fact  

>  --igenomes_base /path/to/ref

**Comment by FriederikeHanssen** [comment]
ok, but even with that it is not working? 

I am sorry, have no idea about PBS. Did you set the executor as described here: https://www.nextflow.io/docs/latest/executor.html?highlight=pbs#pbs-torque ?

**Comment by FriederikeHanssen** [comment]
ok great. Will close this issue. Please re-open it if you run into more problems :)
