### ISSUE TITLE
[BUG] iGenomes genome index directory does not exist

### ISSUE THREAD

**Issue by bounlu** [nf-core/sarek#542]
In the `dev` branch, **bwamem2** index directory below does not exist on iGenomes bucket:

https://github.com/nf-core/sarek/blob/3bcf3bbcb6c2bece3c69e4b18558ac1f54107861/conf/igenomes.config#L39

**Comment by FriederikeHanssen** [comment]
yes, we are aware. Same for the dragmap index. It is in the making. Sorry about this. If you want to run bwamem2, you can set `--bwa false` and it will build the index for you

**Comment by FriederikeHanssen** [comment]
Same as #340 will track progress there
