### ISSUE TITLE
create  panel of normals with the pipeline

### ISSUE THREAD

**Issue by sabrina0701** [nf-core/sarek#565]
Hello, when I do somatic variants calling, the pineline suggested to have panel of normals for GATK Mutect2, but I am just wondering that it seems I couldn't produce PON by Sarek. Therefore, is that true that I should go back to GATK to create PON, or the Sarek would do that? Thanks!

**Comment by FriederikeHanssen** [comment]
Hey! Way over time reply: yes you need to create the PON outside of the pipeline. We added docs for this. Also, there will be a new pipeline called nf-core/createpanelrefs which will create the mutect2 pon
