### ISSUE TITLE
[BUG]: VEP version in output vcf and HTML summary report is not updated as per the vep_cache_version provided by the user. 

### ISSUE THREAD

**Issue by IndhuPS** [nf-core/sarek#573]
Hi there!
Am running nf-core sarek pipeline for germline variants and using VEP for variant annotation using cache file (version 106). I use the flags --annotation_cache with --vep_cache_version 106 --vep_cache <file path>. The pipeline is executed successfully. However in my output vcf file and HTML report, I observe that the version is mentioned as "v99", although the cache file path refers to the 106version file. 

## Run command 
nextflow -log germline_vep106.log -bg run nf-core/sarek -profile docker -with-report -with-trace -with-timeline --genome GRCh38 --input input.vcf.gz --outdir ./germline_vep106 --tools vep --vep_cache /vep_cache/ --annotation_cache --vep_cache_version \"106\" --cpus 64

## Issue observed
In the output vcf file -
##**VEP="v99"** time="2022-05-18 07:23:04" cache="/homo_sapiens/106_GRCh38" ensembl-funcgen=99.0832337 ensembl=99.d3e7d31 ensembl-variation=99.642e1cd ensembl-io=99.441b05b 1000genomes="phase3" COSMIC="92" ClinVar="202109" ESP="V2-SSA137" HGMD-PUBLIC="20204" assembly="GRCh38.p13" dbSNP="154" gencode="GENCODE 40" genebuild="2014-07" gnomAD="r2.1.1" polyphen="2.2.2" regbuild="1.0" sift="sift5.2.2"

## Expected output
Right version to be shown on the outputs.

**Comment by IndhuPS** [comment]
<!--
# nf-core/sarek bug report

Hi there!
Am running nf-core sarek pipeline for germline variants and using VEP for variant annotation using cache file (version 106). I use the flags --annotation_cache with --vep_cache_version 106 --vep_cache <file path>. The pipeline is executed successfully. However in my output vcf file and HTML report, I observe that the version is mentioned as "v99", although the cache file path refers to the 106version file. 

## Run command 
nextflow -log germline_vep106.log -bg run nf-core/sarek -profile docker -with-report -with-trace -with-timeline --genome GRCh38 --input input.vcf.gz --outdir ./germline_vep106 --tools vep --vep_cache /home/indhupriya/vep_cache/ --annotation_cache --vep_cache_version \"106\" --cpus 64

## Issue observed
In the output vcf file -
##**VEP="v99"** time="2022-05-18 07:23:04" cache="/homo_sapiens/106_GRCh38" ensembl-funcgen=99.0832337 ensembl=99.d3e7d31 ensembl-variation=99.642e1cd ensembl-io=99.441b05b 1000genomes="phase3" COSMIC="92" ClinVar="202109" ESP="V2-SSA137" HGMD-PUBLIC="20204" assembly="GRCh38.p13" dbSNP="154" gencode="GENCODE 40" genebuild="2014-07" gnomAD="r2.1.1" polyphen="2.2.2" regbuild="1.0" sift="sift5.2.2"

## Expected output
Right version to be shown on the outputs.

**Comment by maxulysse** [comment]
The VEP version is for the VEP tool itself, the VEP cache version would be for the version of the cache.
It does say `cache="/homo_sapiens/106_GRCh38"` for the cache, which is coherent with the cache asked.
Which Sarek version did you use for this command?

**Comment by maxulysse** [comment]
Then, version is actually correctly reported:
- VEP is indeed on version `99` (cf https://github.com/nf-core/sarek/blob/e8f56e5bbb6f8a34793a6b5a2945981eb43090aa/containers/vep/Dockerfile#L17).
- Cache is indeed `106` cf `cache="/homo_sapiens/106_GRCh38`
