### ISSUE TITLE
[FEATURE]: MultiQC does not include VEP reports

### ISSUE THREAD

**Issue by IndhuPS** [nf-core/sarek#574]
Hi,

I am running nf-core Sarek (installed using docker) and am using VEP for variant annotations. The pipeline is successfully completed, but the multiQC report summary does not include the VEP results. 

The version of multiQC (from docker) is 1.8 and I see that VEP section is included only in higher versions. Is there anyway to upgrade the multiQC version in the docker to include the VEP results as well?

**Comment by FriederikeHanssen** [comment]
@IndhuPS for the current release 2.7.1 it is not possible without rebuilding the whole container. We have upgraded the MultiQC version on the dev branch already which will include the VEP report. You could either try the dev version (still under lots of construction but becoming fairly stable) or take the output reports from you sarek run and run MultiQC 1.12 manually.
