### ISSUE TITLE
Create an option to have .pileup files be transient (not retained in the cache)

### ISSUE THREAD

**Issue by jowkar** [nf-core/sarek#579]
As part of the Control-FREEC process, very large uncompressed pileup files are generated and these are by default exported to the final results directory, as well as retained in the cache, and no option seems to exist to prevent this. Given the size of these files (ca 300GB), a run of more than a handful of WGS samples will more than fill about 5-6 TB of cache space and most likely the same amount of space in the results directory (unless --publish_dir_mode is changed to move or symlink). In my case the amount of space taken up in the work directory for the whole run on 16 samples (half of which are pileup files) is enough to cause the pipeline to crash due to reaching the physical limits of a 12TB hard drive entirely dedicated as work directory. I suspect not all users will be interested in retaining these files, which are mostly a means to an end to make Control-FREEC run. Therefore, it would be good if either these were deleted within the relevant process (so that they are not retained in the work directory) or if there was an option to do so. They are relatively easy to recreate from the BAM files later on if needed.

**Comment by FriederikeHanssen** [comment]
Hi @jowkar! on the dev branch the mpileup files are now zipped. Per default they are still published however with dsl2 you can easily overwrite that in a custom config by setting something like:

```
withName:'MPILEUP|CAT_MPILEUP'{
      publishDir       = [
            enabled: false
        ]
}
```

It is unfortunately not possible to remove them from the work directory while the pipeline runs. Hopefully the above steps still help to reduce the data foot print enough for you to not constantly run into this anymore.
