### ISSUE TITLE
TIDDIT output folder named `null`

### ISSUE THREAD

**Issue by apeltzer** [nf-core/sarek#621]
As described on SLack, the output folder of the current `dev` branch for TIDDIT when annotated is simply called `null`.

**Comment by asp8200** [comment]
@FriederikeHanssen : Are you solving this issue or should I take a look at it?

**Comment by maxulysse** [comment]
It'll be fixed by https://github.com/nf-core/sarek/pull/618

**Comment by FriederikeHanssen** [comment]
#618 is merged
