### ISSUE TITLE
missing container tag 2.7.2.GRCm38 for sareksnpeff

### ISSUE THREAD

**Issue by intawat** [nf-core/sarek#627]
2. See error:

**Comment by intawat** [comment]
Please guide me how to fix the error.

**Comment by maxulysse** [comment]
@intawat we're simply missing this tag for this container.
I probably find some time to build it and push it during the week.
Otherwise, you have two options:
- use the sarek 2.7.1 version, with which the corresponding containers are there
- Build the container locally

**Comment by intawat** [comment]
I did try 2.7.2 it said "No such variable: ch_software_versions_yaml" 
Another problem.  I should wait, I think.

**Comment by maxulysse** [comment]
Containers is now built and pushed to dockerhub. You should not have issue with that anymore.

**Comment by maxulysse** [comment]
This container is big, so I'd recommend setting up a `NXF_SINGULARITY_CACHEDIR` ENV on your system, and downloading this image there.

**Comment by intawat** [comment]
I set NXF_SINGULARITY_CACHEDIR and the image was downloaded however, error is still present as below.
------------------

Pulling Singularity image docker://nfcore/sarekvep:2.7.2.GRCm38 [cache /storage/Intawat/Jhx_data/forDocker/nfcore-sarekvep-2.7.2.GRCm38.img]
Pulling Singularity image docker://nfcore/sareksnpeff:2.7.2.GRCm38 [cache /storage/Intawat/Jhx_data/forDocker/nfcore-sareksnpeff-2.7.2.GRCm38.img]
Error executing process > 'Snpeff (NB - TIDDIT - TIDDIT_NB.vcf.gz)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name nfcore-sareksnpeff-2.7.2.GRCm38.img.pulling.1658363013340 docker://nfcore/sareksnpeff:2.7.2.GRCm38 > /dev/null
  status : 255
  message:
    [31mFATAL:   While making image from oci registry: failed to get checksum for docker://nfcore/sareksnpeff:2.7.2.GRCm38: Error reading manifest 2.7.2.GRCm38 in docker.io/nfcore/sareksnpeff: manifest unknown: manifest unknown

**Comment by maxulysse** [comment]
My bad, I pushed `2.7.2.GRcm38` and not `2.7.2.GRCm38`.
Fixing that right now.
Should be ok in 1 hour or 2
