### ISSUE TITLE
Azure errors at Map reads step with segementation fault

### ISSUE THREAD

**Issue by vsmalladi** [nf-core/sarek#678]
### Description of the bug

In Azure we see an error with igenomes using Map reads. We get a segementation fault, which I beleive is due to some issue with S3 pulling the indexes down.

### Command used and terminal output

```console
nextflow run nf-core/sarek -c /home/zvasconcelos/data/sarek/azure --input /home/zvasconcelos/data/sarek/sarek_azure.tsv --outdir 'az://genomas-raros/results' --tools HaplotypeCaller -work-dir 'az://genomas-raros/work'
```

### System information

Nextflow version : 22.04.04
Hardware: Cloud 
Executor: Azurebatch
Container engine: Docker
OS: Centos
Version of nf-core/sarek: 2.7.2

**Comment by pditommaso** [comment]
Is there any logs showing the error?
