### ISSUE TITLE
errors using Launch on website

### ISSUE THREAD

**Issue by sheucke** [nf-core/sarek#694]
### Description of the bug

Hi Sarek Team,

I wanted to try the new 3.0 version but run into a lot of errors doing so.

First the documentations is wrong here:

First, go to the [nf-core/sarek releases page](https://github.com/nf-core/sarek/releases) and find the latest version number - numeric only (eg. 3.0.0). Then specify this when running the pipeline with -r (one hyphen) - eg. -r 3.0.0.

It only works like with -r 3.0 otherwise I get error that 3.0.0 does not exist.

then I get errors with the launch tool:

for the --input field with: example_pair_fastq.csv

Must match pattern \.csv$
Path to comma-separated file containing information about the samples in the experiment.

I did transform the tsv into a csv file, that can not be the problem.

then later for --tools:  FreeBayes, HaplotypeCaller, Manta, snpEff, VEP

I get the error:

Must match pattern ^((ascat|cnvkit|controlfreec|deepvariant|freebayes|haplotypecaller|manta|merge|mpileup|msisensorpro|mutect2|snpeff|strelka|tiddit|vep)*,?)*$

sry i cant translate that, in the help its still written comma separated, which I did.

best regards
sebastian

**Comment by FriederikeHanssen** [comment]
Can you post your full command line and possible your input.csv? From what you have posted:

1. Yes revision is 3.0
2. tools must all be lower case, comma-separated, no spaces
3. csv file must contain a header line and end on `.csv`

**Comment by sheucke** [comment]
Hi Friederike,

its the Launch tool which gives error by it self, it does not know my csv and at that point it should not matter if the csv file in it self is wrong. I use the launch tool to get an params.json file.

best regards 
sebastian

**Comment by maxulysse** [comment]
Hi @sheucke
The params validation is done right at the start.
We need to check that proper params, including the one used to specify the samplesheet have been used, and then we can start checking the csv file.

**Comment by sheucke** [comment]
Hi max,
What I mean is your Launch tool https://nf-co.re/launch?pipeline=sarek&release=3.0. I f you enter any file name with .csv it will give you an error and so you will never get a params.json file.

I hope I could make it clear now. Please try the link for yourself.

Best regards 
sebastian

**Comment by sheucke** [comment]
![error](https://user-images.githubusercontent.com/21970508/181491719-cebbafae-be8b-4970-a26c-6c9e5076eb9e.png)

**Comment by maxulysse** [comment]
Oh I see, I finally understand what's your issue.
Yes, definitively an issue on our side, we must have messed up the pattern, sorry about that, we'll work on a fix in `dev`

**Comment by sheucke** [comment]
thank you. For the tools input my personal preference would be the exact tool name, as they are written in the help, but if you need everything in lowercase its ok, but i think it could also be done in background or with a more open regular expression.

I will close the issue now.

**Comment by FriederikeHanssen** [comment]
Hi @sheucke ! Is the launch tool now working for you?

**Comment by joshuamschmidt** [comment]
in fact, the underlying regex only matches a file named `.csv`:

![sarek_launch_csv](https://user-images.githubusercontent.com/20945945/197912140-53ef2320-2cac-4efd-808d-fcbcff82f371.JPG)

**Comment by maxulysse** [comment]
Thanks for reporting the issue, I'll make sure to fix that ASAP

**Comment by FriederikeHanssen** [comment]
Fix is now available on dev
