### ISSUE TITLE
BAM index (bai) should be provided

### ISSUE THREAD

**Issue by sabrina0701** [nf-core/sarek#700]
### Description of the bug

When I started with (u)BAM, I prepare a CSV contained patient, status, sample, lane, bam columns, I got an error: BAM index (bai) should be provided.

Why does this happen? The tutorial doesn't say Samplesheet Columns must contain bai. Must I provide Bam index bai when I start with (u)BAM? 

### Command used and terminal output

```console
command: nextflow run nf-core/sarek \
--input /SAN/colcc/CPI_raw/Jansen_CRC/Jansen_CRC.csv \
-profile singularity \
--step mapping

output:
BAM index (bai) should be provided.
Argument of `file` function cannot be null
```

### System information

Nextflow: 22.04.5.5708
Hardware: HPC
Container: Singularity
nf-core/sarek v3.0

**Comment by wlyucl** [comment]
Hello, 

I've encountered the same issue when starting from unmapped bam files using Sarek v3.1.2. Are the BAI files still required for this version? 

_WARN: There's no process matching config selector: NFCORE_SAREK:SAREK:CRAM_QC_NO_MD:SAMTOOLS_STATS -- Did you mean: NFCORE_SAREK:SAREK:CRAM_QC_RECAL:SAMTOOLS_STATS?
BAM index (bai) should be provided.

Argument of `file` function cannot be null_

Thank you
