### ISSUE TITLE
Improve the process requests for tools in the pipeline

### ISSUE THREAD

**Issue by SPPearce** [nf-core/sarek#701]
### Description of feature

Samtools pileup has the config process label of `process_medium`, but is not parallelised at all. 
It requests 6 cores and 36GB of RAM by default, but doesn't need the cores.
If the RAM requirement could also be decreased by default that would also be a good idea.

These are the modules that use `process_medium`:
https://github.com/nf-core/sarek/search?q=process_medium

**Comment by FriederikeHanssen** [comment]
Addressed for a good amount of modules in #734 and #725 and part of the upcoming release 3.0.2 .

For mpileup but also a good chunk of other modules. We probably missed some here and there. Let's open a new issue once we detect them.
