### ISSUE TITLE
Output from ascat not stable

### ISSUE THREAD

**Issue by asp8200** [nf-core/sarek#702]
### Description of the bug

When running the following test, which is also also part of the CI-test `tests/test_tools_manually.yml`,

```nextflow run main.nf -profile test,tools_somatic_ascat```

@SusiJo found that the content (not just timestamps or something like that, but proper values!) of the output-files 
```
results/variant_calling/ascat/sample4_vs_sample3/sample4_vs_sample3.tumour_tumourBAF.txt
results/variant_calling/ascat/sample4_vs_sample3/sample4_vs_sample3.tumour_tumourLogR.txt
```
change on reruns:

![image](https://user-images.githubusercontent.com/37172585/184126552-c929a530-8bbb-4a1f-9591-fac45f8f600a.png)

### Command used and terminal output

```console
nextflow run main.nf -profile test,tools_somatic_ascat


"unstable" output-files
results/variant_calling/ascat/sample4_vs_sample3/sample4_vs_sample3.tumour_tumourBAF.txt
results/variant_calling/ascat/sample4_vs_sample3/sample4_vs_sample3.tumour_tumourLogR.txt
```

### Relevant files

`sample4_vs_sample3.tumour_tumourBAF.txt` from consecutive runs of the test: 

[ascat2.zip](https://github.com/nf-core/sarek/files/9308388/ascat2.zip)
[ascat1.zip](https://github.com/nf-core/sarek/files/9308389/ascat1.zip)

**Comment by FriederikeHanssen** [comment]
what did you use to run it? Docker?

**Comment by asp8200** [comment]
> what did you use to run it? Docker?

@SusiJo told me she used Docker.

**Comment by FriederikeHanssen** [comment]
Looking at the manual here: https://raw.githubusercontent.com/VanLoo-lab/ascat/master/man/ASCAT-manual.pdf looks like one can set seeds for a few functions. Haven't cross-checked them with the ones that are used, but seems like a good place to start.

**Comment by SusiJo** [comment]
So they fixed the issue on the master branch but we probably need to wait for the 3.1 release to make a new mulled container.

**Comment by FriederikeHanssen** [comment]
Hey! Let's keep this open until it is actually merged into the pipeline and added to the changelog or we will forget :)
