### ISSUE TITLE
markduplicate change memory option is not work !

### ISSUE THREAD

**Issue by intawat** [nf-core/sarek#703]
### Description of the bug

I try to change memory for mark duplicate but it not working. I used the command below. Please suggest what I should do.

sbatch --nodes=1 --ntasks=128 --time=100:00:00 --mem=120gb --partition=phi --job-name=sarekHB --output=sarekHB_vcall.log --wrap "conda activate nextflow; module load singularity; nextflow run nf-core/sarek -r 2.7.2 --input infiles.tsv --genome GRCm38 -profile singularity --max_memory 180GB --max_cpus 30 -resume --tools HaplotypeCaller,Strelka,Manta,TIDDIT,snpEff,VEP --markdup_java_options \"-Xms4000m -Xmx200g\" "

However it use the default set up

Command executed:

  gatk --java-options "-Xms3g -Xmx6g"         MarkDuplicates         --INPUT SAMPLE_ID.bam         --METRICS_FILE SAMPLE_ID.bam.metrics         --TMP_DIR .         --ASSUME_SORT_ORDER coordinate         --CREATE_INDEX true         --OUTPUT SAMPLE_ID.md.bam

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO  2022-08-13 03:06:39     MarkDuplicates  Tracking 16042768 as yet unmatched pairs. 10821298 records in RAM.
  INFO  2022-08-13 03:09:57     MarkDuplicates  Read   980,000,000 records.  Elapsed time: 12:30:19s.  Time for last 1,000,000:  198s.  Last read position: 2:98,667,040
  INFO  2022-08-13 03:09:57     MarkDuplicates  Tracking 16372570 as yet unmatched pairs. 11133555 records in RAM.
  INFO  2022-08-13 03:13:41     MarkDuplicates  Read   981,000,000 records.  Elapsed time: 12:34:03s.  Time for last 1,000,000:  223s.  Last read position: 2:98,667,042
  INFO  2022-08-13 03:13:41     MarkDuplicates  Tracking 16534416 as yet unmatched pairs. 11275291 records in RAM.
  INFO  2022-08-13 03:14:14     MarkDuplicates  Read   982,000,000 records.  Elapsed time: 12:34:36s.  Time for last 1,000,000:   33s.  Last read position: 2:98,667,044
  INFO  2022-08-13 03:14:14     MarkDuplicates  Tracking 16964439 as yet unmatched pairs. 11681597 records in RAM.
  INFO  2022-08-13 03:14:50     MarkDuplicates  Read   983,000,000 records.  Elapsed time: 12:35:12s.  Time for last 1,000,000:   35s.  Last read position: 2:98,667,046
  INFO  2022-08-13 03:14:50     MarkDuplicates  Tracking 17317945 as yet unmatched pairs. 12008545 records in RAM.
  INFO  2022-08-13 03:15:30     MarkDuplicates  Read   984,000,000 records.  Elapsed time: 12:35:51s.  Time for last 1,000,000:   39s.  Last read position: 2:98,667,048
  INFO  2022-08-13 03:15:30     MarkDuplicates  Tracking 17470328 as yet unmatched pairs. 12127653 records in RAM.
  INFO  2022-08-13 03:16:09     MarkDuplicates  Read   985,000,000 records.  Elapsed time: 12:36:30s.  Time for last 1,000,000:   38s.  Last read position: 2:98,667,050
  INFO  2022-08-13 03:16:09     MarkDuplicates  Tracking 17829708 as yet unmatched pairs. 12455928 records in RAM.
  INFO  2022-08-13 03:16:51     MarkDuplicates  Read   986,000,000 records.  Elapsed time: 12:37:13s.  Time for last 1,000,000:   42s.  Last read position: 2:98,667,053
  INFO  2022-08-13 03:16:51     MarkDuplicates  Tracking 18240443 as yet unmatched pairs. 12835077 records in RAM.
  INFO  2022-08-13 03:17:29     MarkDuplicates  Read   987,000,000 records.  Elapsed time: 12:37:51s.  Time for last 1,000,000:   37s.  Last read position: 2:98,667,055
  INFO  2022-08-13 03:17:29     MarkDuplicates  Tracking 18530286 as yet unmatched pairs. 13091879 records in RAM.
  INFO  2022-08-13 03:19:56     MarkDuplicates  Read   988,000,000 records.  Elapsed time: 12:40:17s.  Time for last 1,000,000:  146s.  Last read position: 2:98,667,057
  INFO  2022-08-13 03:19:56     MarkDuplicates  Tracking 18672057 as yet unmatched pairs. 13198180 records in RAM.
  INFO  2022-08-13 03:22:52     MarkDuplicates  Read   989,000,000 records.  Elapsed time: 12:43:14s.  Time for last 1,000,000:  176s.  Last read position: 2:98,667,058
  INFO  2022-08-13 03:22:52     MarkDuplicates  Tracking 18747010 as yet unmatched pairs. 13235826 records in RAM.
  INFO  2022-08-13 03:27:34     MarkDuplicates  Read   990,000,000 records.  Elapsed time: 12:47:56s.  Time for last 1,000,000:  282s.  Last read position: 2:98,667,061
  INFO  2022-08-13 03:27:34     MarkDuplicates  Tracking 19174881 as yet unmatched pairs. 13628199 records in RAM.
  INFO  2022-08-13 03:36:55     MarkDuplicates  Read   991,000,000 records.  Elapsed time: 12:57:17s.  Time for last 1,000,000:  560s.  Last read position: 2:98,667,063
  INFO  2022-08-13 03:36:55     MarkDuplicates  Tracking 19466422 as yet unmatched pairs. 13881969 records in RAM.
  [Sat Aug 13 04:11:05 UTC 2022] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 811.50 minutes.
  Runtime.totalMemory()=5726797824
  To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
  Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.String.<init>(String.java:325)
        at htsjdk.samtools.util.StringUtil.bytesToString(StringUtil.java:301)
        at htsjdk.samtools.util.StringUtil.bytesToString(StringUtil.java:288)
        at htsjdk.samtools.BinaryTagCodec.readNullTerminatedString(BinaryTagCodec.java:423)
        at htsjdk.samtools.BinaryTagCodec.readSingleValue(BinaryTagCodec.java:318)
        at htsjdk.samtools.BinaryTagCodec.readTags(BinaryTagCodec.java:282)
        at htsjdk.samtools.BAMRecord.decodeAttributes(BAMRecord.java:412)
        at htsjdk.samtools.BAMRecord.getAttribute(BAMRecord.java:391)
        at htsjdk.samtools.SAMRecord.isValid(SAMRecord.java:2034)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:848)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:834)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:802)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:574)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:553)
        at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:524)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)

Work dir:
  /storage/Intawat/Jhx_data/HBres/work/a1/f0a4cb854b4cfc9abd964fecc74c40

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

### Command used and terminal output

```console
sbatch --nodes=1 --ntasks=128 --time=100:00:00 --mem=120gb --partition=phi --job-name=sarekHB --output=sarekHB_vcall.log --wrap "conda activate nextflow; module load singularity; nextflow run nf-core/sarek -r 2.7.2 --input infiles.tsv --genome GRCm38 -profile singularity --max_memory 180GB --max_cpus 30 -resume --tools HaplotypeCaller,Strelka,Manta,TIDDIT,snpEff,VEP --markdup_java_options \"-Xms4000m -Xmx200g\" "
```

**Comment by intawat** [comment]
Any help on this from the developer ?

**Comment by FriederikeHanssen** [comment]
@maxulysse were you able to reproduce this?

**Comment by maxulysse** [comment]
Afraid I couldn't either.

**Comment by intawat** [comment]
It is very important step when user need to deal with large amount of sequencing data. I am looking forward on this bug fix :).

**Comment by FriederikeHanssen** [comment]
Hi @intawat ! I am sorry you are experiencing this issue. We are unfortunately not able to provide bugfixes for issues < sarek 3.0 due to time constraints. 

I hope you are understand this.
