### ISSUE TITLE
Add documentation for Azure config specs

### ISSUE THREAD

**Issue by vsmalladi** [nf-core/sarek#714]
### Description of feature

Add Azure specifc Sarek pipeline VM_sizes documentation

```
azure {
    batch {
        pools {
            auto {
               autoScale = true

               sku = "batch.node.centos 7"

               offer = "centos-container"

               publisher = "microsoft-azure-batch"

               vmType = 'Standard_E64_v3'

               vmCount = 1

            }
        }
    }
}
```

**Comment by drpatelh** [comment]
Thanks @vsmalladi ! Be awesome if you are able to upload the full command / `.nextflow.log` file here which will contain more extensive information as to which versions of the pipeline, NF and the command used.

**Comment by vsmalladi** [comment]
Sarek version: 3.0.1
NExtflow Version: 22.04.3.5703

Command: 
nextflow run sarek/main.nf -c azure.config -w "az://work" --outdir "az://results"  --tools haplotypecaller --input sarek.csv
