### ISSUE TITLE
More input checks

### ISSUE THREAD

**Issue by maxulysse** [nf-core/sarek#717]
### Description of feature

- [x] `--joint_germline` should fail if no `--tools haplotypecaller` is provided
- [ ] ~~samples' uniqueness' tests should be tested on multiple `samplesheet.csv` files~~

**Comment by asp8200** [comment]
@maxulysse : In the case where the user is supplying several samplesheets for the same pipeline-run, what kind of "uniqueness"-checks do we want across the samplesheets?  Could one samplesheet contain fastq-files while another contain bam-files?

**Comment by FriederikeHanssen** [comment]
actually haven't tried whether this works. i would expect some hickups, but might be worth a test drive

**Comment by asp8200** [comment]
It turned out that the current version of Sarek doesn't support inputting multiple csv-files in a list. Over on Slack in the sarek-channel, we had a vote and it was decided that the feature isn't needed.
