### ISSUE TITLE
Singularity: container creation failed possible causes are that your kernel doesn't support the compression algorithm or the image is corrupted

### ISSUE THREAD

**Issue by jiehuichen** [nf-core/sarek#747]
### Description of the bug

Hi,

Thanks for your time.

I installed nextflow and singularity referred the manual of 'https://nf-co.re/sarek'

To run it offline, iGenome files (GRCh38) were downloaded with 'bash aws-igenomes.sh -s GATK'.

And the fastq files were 
SRR7890918_WES_HCC1395-EA_tumor_1.fastq.gz
SRR7890918_WES_HCC1395-EA_tumor_2.fastq.gz
SRR7890919_WES_HCC1395BL-EA_normal_1.fastq.gz
SRR7890919_WES_HCC1395BL-EA_normal_2.fastq.gz.

The sarek pipeline always crash at 'BWAMEM1_MEM', could you help me solving this. Thanks a lot.

By the way, I have run the nf-core-rnaseq-3.7 successfully , but sarek always failed.

### Command used and terminal output

```console
nextflow run /home/cjh/jiehui/WES/nf-core-sarek-3.0.1/workflow -profile singularity \
	--custom_config_base /home/cjh/jiehui/WES/nf-core-sarek-3.0.1/configs \
	--input samplesheet.csv \
	--igenomes_base /home/cjh/download/references \
	--outdir /home/cjh/jiehui/WES/nf-core-awsmegatests/output
```

### Relevant files

[Sarek_jiehui.zip](https://github.com/nf-core/sarek/files/9565171/Sarek_jiehui.zip)

### System information

Nextflow version:version 22.04.5, build 5708 (15-07-2022 16:09 UTC)
Hardware:HPC
Container engine: Singularity
OS:Linux
Version of nf-core/sarek:3.0.1

**Comment by FriederikeHanssen** [comment]
Error message:

```
  FATAL:   container creation failed: mount /proc/self/fd/3->/opt/singularity/3.9.2/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: kernel reported a bad superblock for squashfs image partition, possible causes are that your kernel doesn't support the compression algorithm or the image is corrupted
  ```
  
@maxulysse looks like a singularity issue. Any idea?

**Comment by maxulysse** [comment]
Either issues with `squashfs` or corrupted image as said in the error.
I'm afraid that for more ideas, we'll have to ask the wizards

**Comment by stefcardinale** [comment]
> Error message:
> 
> ```
>   FATAL:   container creation failed: mount /proc/self/fd/3->/opt/singularity/3.9.2/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: kernel reported a bad superblock for squashfs image partition, possible causes are that your kernel doesn't support the compression algorithm or the image is corrupted
> ```
> 
> @maxulysse looks like a singularity issue. Any idea?

I don't understand, what does this have with the issue above? Sorry!

**Comment by stefcardinale** [comment]
Hello, I have got the same error after doing a test with a pair of small fastq files.

Error executing process > 'NFCORE_SAREK:SAREK:GATK4_MAPPING:BWAMEM2_MEM (1-1)'

Caused by:
  java.lang.UnsupportedOperationException

any idea where the problem is?

**Comment by FriederikeHanssen** [comment]
> > Error message:
> > ```
> >   FATAL:   container creation failed: mount /proc/self/fd/3->/opt/singularity/3.9.2/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: kernel reported a bad superblock for squashfs image partition, possible causes are that your kernel doesn't support the compression algorithm or the image is corrupted
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @maxulysse looks like a singularity issue. Any idea?
> 
> I don't understand, what does this have with the issue above? Sorry!

That is the error message reported by the user (stated in the execution_report.html, that is attached in the zip file)

**Comment by FriederikeHanssen** [comment]
> Hello, I have got the same error after doing a test with a pair of small fastq files.
> 
> Error executing process > 'NFCORE_SAREK:SAREK:GATK4_MAPPING:BWAMEM2_MEM (1-1)'
> 
> Caused by: java.lang.UnsupportedOperationException
> 
> any idea where the problem is?

No, sorry we need more info here; such as nextflow version, sarek  version, input command, samplesheet, and any log files you have. Would suggest to open a new issue actually, since the error code is unrelated

**Comment by FriederikeHanssen** [comment]
@jiehuichen have you tried removing the images and redownloading them to see if something broke during the download?

**Comment by stefcardinale** [comment]
> > Hello, I have got the same error after doing a test with a pair of small fastq files.
> > Error executing process > 'NFCORE_SAREK:SAREK:GATK4_MAPPING:BWAMEM2_MEM (1-1)'
> > Caused by: java.lang.UnsupportedOperationException
> > any idea where the problem is?
> 
> No, sorry we need more info here; such as nextflow version, sarek version, input command, samplesheet, and any log files you have. Would suggest to open a new issue actually, since the error code is unrelated

OK, thanks. I will open a new ticket.

**Comment by jiehuichen** [comment]
> @jiehuichen have you tried removing the images and redownloading them to see if something broke during the download?

I have tested this method you mentioned, and it has been on different HPCs, and the problem still exists. Thanks.

**Comment by jiehuichen** [comment]
I have tested this method you mentioned, and it has been on different HPCs, and the problem still exists. Thanks. @FriederikeHanssen

**Comment by pontus** [comment]
Could you please locate the singularity image (likely called 

 mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40:8110a70be2bfe7f75a2ea7f2a89cda4cc7732095-0

and run some checksum utility (e.g. sha1sum) on it and report the checksum?

**Comment by pontus** [comment]
(switching aligners might also help as it would avoid this specific process.)

**Comment by jiehuichen** [comment]
> Could you please locate the singularity image (likely called
> 
> mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40:8110a70be2bfe7f75a2ea7f2a89cda4cc7732095-0
> 
> and run some checksum utility (e.g. sha1sum) on it and report the checksum?

37fd251d74d96228e9ccf857ed9df499de11a1a6  depot.galaxyproject.org-singularity-bcftools-1.15.1--h0ea216a_0.img
5f91ddd25c80f8a73a88d54fd13802e090a1eac1  depot.galaxyproject.org-singularity-bwa-0.7.17--hed695b0_7.img
831365b7651886df4ec3d207af333bf2d1b08abc  depot.galaxyproject.org-singularity-bwa-mem2-2.2.1--he513fc3_0.img
f2c109a9826814367e57b9ed748220db0f98fb7b  depot.galaxyproject.org-singularity-cnvkit-0.9.9--pyhdfd78af_0.img
870eb582fac188a61cbebd7a29a2206047e30caa  depot.galaxyproject.org-singularity-control-freec-11.6--h1b792b2_1.img
a44b2315267efdee287e4d3a34d0f40c5cc8dfa2  depot.galaxyproject.org-singularity-dragmap-1.2.1--hd4ca14e_0.img
a8af6f2b990334236760da38cb19400e397aa216  depot.galaxyproject.org-singularity-ensembl-vep-106.1--pl5321h4a94de4_0.img
48ceabecb042eec385893bfd2c9d83c387df9f2e  depot.galaxyproject.org-singularity-fastp-0.23.2--h79da9fb_0.img
3c03ba36fb762ce05119022b6ab07160cb742af6  depot.galaxyproject.org-singularity-fastqc-0.11.9--0.img
5368a378780d7e167490932a9838a0bb7b924951  depot.galaxyproject.org-singularity-fgbio-2.0.2--hdfd78af_0.img
7b48017ffeafa09c014b51f3d412f8394f6e34dd  depot.galaxyproject.org-singularity-freebayes-1.3.5--py38ha193a2f_3.img
ed61a862a09c3b644d9780f4be2f5eb6ff1ec479  depot.galaxyproject.org-singularity-gatk4-4.2.6.1--hdfd78af_0.img
d9313846de2bcbd1506ba7d405b5b92ab9097b58  depot.galaxyproject.org-singularity-gawk-5.1.0.img
f8f6e0efed862cf01ae580004b18028c4f38ceaa  depot.galaxyproject.org-singularity-manta-1.6.0--h9ee0642_1.img
490b66cb7e08920c929fc3c82845b4c496f40242  depot.galaxyproject.org-singularity-mosdepth-0.3.3--hdfd78af_1.img
8716242967000f4cd779123dd96f0b1ce0a0ef75  depot.galaxyproject.org-singularity-msisensor-pro-1.2.0--hfc31af2_0.img
eaee0c4c0ae9f05723f6da6414bdb6df5d9bdf89  depot.galaxyproject.org-singularity-mulled-v2-19fa9f1a5c3966b63a24166365e81da35738c5ab-fff03944e664bbf9a139f7b174b9cb2d4163271a-0.img
29c538287f0cefd0ac1a74fa4b5f4188e2806365  depot.galaxyproject.org-singularity-mulled-v2-580d344d9d4a496cd403932da8765f9e0187774d-5ebebbc128cd624282eaa37d2c7fe01505a91a69-0.img
e6cdef27a8cdfb9bb7b0b11ea5aa23a9a3613973  depot.galaxyproject.org-singularity-mulled-v2-780d630a9bb6a0ff2e7b6f730906fd703e40e98f-304d1c5ab610f216e77c61420ebe85f1e7c5968a-0.img
a41f87a2a5be2ff98b88476f5f97ea16528728f4  depot.galaxyproject.org-singularity-mulled-v2-c278c7398beb73294d78639a864352abef2931ce-dfe5aaa885de434adb2b490b68972c5840c6d761-0.img
c35e9663d311e9322b42598f4474c17d6a7c9323  depot.galaxyproject.org-singularity-mulled-v2-c8daa8f9d69d3c5a1a4ff08283a166c18edb0000-56d0a468970fbb474d92f0591abcf677757fb370-0.img
660877d5830035d8b74c9a94cbcf869f91bcf05e  depot.galaxyproject.org-singularity-mulled-v2-e5d375990341c5aef3c9aff74f96f66f65375ef6-38aed4501da19db366dc7c8d52d31d94e760cfaf-0.img
6b2df4f1dbb34ee97b292eb9704376f2e344ea3d  depot.galaxyproject.org-singularity-mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40-8110a70be2bfe7f75a2ea7f2a89cda4cc7732095-0.img
6e99899fa9584b11f4948d267013755f94812872  depot.galaxyproject.org-singularity-multiqc-1.13a--pyhdfd78af_1.img
6f469a1b9e0e8d0f6bfacf7e872727a08a506951  depot.galaxyproject.org-singularity-p7zip-15.09--h2d50403_4.img
5213a4d83fce3d5081e6fbddfbce15262bbc1ae6  depot.galaxyproject.org-singularity-pigz-2.3.4.img
0c09177a7f4f4ddfee4e7de42a57522886e720f5  depot.galaxyproject.org-singularity-samtools-1.15.1--h1170115_0.img
b43fe5f28a073f1adc32816dbdf14ce58ddb24ec  depot.galaxyproject.org-singularity-snpeff-5.1--hdfd78af_2.img
20d00d7fd579c401b91ab1e55cf3ff9be5496a0b  depot.galaxyproject.org-singularity-strelka-2.9.10--h9ee0642_1.img
247c3ee0dca78c3f417a8ca194771e0c05bd6193  depot.galaxyproject.org-singularity-tabix-1.11--hdfd78af_0.img
5f9dbd32c4928ef52ecc1bef26935ce84efdb0a0  depot.galaxyproject.org-singularity-tiddit-3.1.0--py39h59fae87_1.img
1cecef1af4bd14589a07ac179569bbdb339c6a01  depot.galaxyproject.org-singularity-ubuntu-20.04.img
75380f489c20a48d02f6a87756f711cc7e7c6f0e  depot.galaxyproject.org-singularity-vcftools-0.1.16--he513fc3_4.img
658092fc9ea961e214a578ad3dd8b959759563c5  nfcore-snpeff-5.1.GRCh38.img
9a1ee13c9cdb6d96dc16905192e03145ed24e742  nfcore-vep-106.1.GRCh38.img

**Comment by jiehuichen** [comment]
> Could you please locate the singularity image (likely called
> 
> mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40:8110a70be2bfe7f75a2ea7f2a89cda4cc7732095-0
> 
> and run some checksum utility (e.g. sha1sum) on it and report the checksum?

Thanks, the sha1sum of these images is listed.

37fd251d74d96228e9ccf857ed9df499de11a1a6  depot.galaxyproject.org-singularity-bcftools-1.15.1--h0ea216a_0.img
5f91ddd25c80f8a73a88d54fd13802e090a1eac1  depot.galaxyproject.org-singularity-bwa-0.7.17--hed695b0_7.img
831365b7651886df4ec3d207af333bf2d1b08abc  depot.galaxyproject.org-singularity-bwa-mem2-2.2.1--he513fc3_0.img
f2c109a9826814367e57b9ed748220db0f98fb7b  depot.galaxyproject.org-singularity-cnvkit-0.9.9--pyhdfd78af_0.img
870eb582fac188a61cbebd7a29a2206047e30caa  depot.galaxyproject.org-singularity-control-freec-11.6--h1b792b2_1.img
a44b2315267efdee287e4d3a34d0f40c5cc8dfa2  depot.galaxyproject.org-singularity-dragmap-1.2.1--hd4ca14e_0.img
a8af6f2b990334236760da38cb19400e397aa216  depot.galaxyproject.org-singularity-ensembl-vep-106.1--pl5321h4a94de4_0.img
48ceabecb042eec385893bfd2c9d83c387df9f2e  depot.galaxyproject.org-singularity-fastp-0.23.2--h79da9fb_0.img
3c03ba36fb762ce05119022b6ab07160cb742af6  depot.galaxyproject.org-singularity-fastqc-0.11.9--0.img
5368a378780d7e167490932a9838a0bb7b924951  depot.galaxyproject.org-singularity-fgbio-2.0.2--hdfd78af_0.img
7b48017ffeafa09c014b51f3d412f8394f6e34dd  depot.galaxyproject.org-singularity-freebayes-1.3.5--py38ha193a2f_3.img
ed61a862a09c3b644d9780f4be2f5eb6ff1ec479  depot.galaxyproject.org-singularity-gatk4-4.2.6.1--hdfd78af_0.img
d9313846de2bcbd1506ba7d405b5b92ab9097b58  depot.galaxyproject.org-singularity-gawk-5.1.0.img
f8f6e0efed862cf01ae580004b18028c4f38ceaa  depot.galaxyproject.org-singularity-manta-1.6.0--h9ee0642_1.img
490b66cb7e08920c929fc3c82845b4c496f40242  depot.galaxyproject.org-singularity-mosdepth-0.3.3--hdfd78af_1.img
8716242967000f4cd779123dd96f0b1ce0a0ef75  depot.galaxyproject.org-singularity-msisensor-pro-1.2.0--hfc31af2_0.img
eaee0c4c0ae9f05723f6da6414bdb6df5d9bdf89  depot.galaxyproject.org-singularity-mulled-v2-19fa9f1a5c3966b63a24166365e81da35738c5ab-fff03944e664bbf9a139f7b174b9cb2d4163271a-0.img
29c538287f0cefd0ac1a74fa4b5f4188e2806365  depot.galaxyproject.org-singularity-mulled-v2-580d344d9d4a496cd403932da8765f9e0187774d-5ebebbc128cd624282eaa37d2c7fe01505a91a69-0.img
e6cdef27a8cdfb9bb7b0b11ea5aa23a9a3613973  depot.galaxyproject.org-singularity-mulled-v2-780d630a9bb6a0ff2e7b6f730906fd703e40e98f-304d1c5ab610f216e77c61420ebe85f1e7c5968a-0.img
a41f87a2a5be2ff98b88476f5f97ea16528728f4  depot.galaxyproject.org-singularity-mulled-v2-c278c7398beb73294d78639a864352abef2931ce-dfe5aaa885de434adb2b490b68972c5840c6d761-0.img
c35e9663d311e9322b42598f4474c17d6a7c9323  depot.galaxyproject.org-singularity-mulled-v2-c8daa8f9d69d3c5a1a4ff08283a166c18edb0000-56d0a468970fbb474d92f0591abcf677757fb370-0.img
660877d5830035d8b74c9a94cbcf869f91bcf05e  depot.galaxyproject.org-singularity-mulled-v2-e5d375990341c5aef3c9aff74f96f66f65375ef6-38aed4501da19db366dc7c8d52d31d94e760cfaf-0.img
6b2df4f1dbb34ee97b292eb9704376f2e344ea3d  depot.galaxyproject.org-singularity-mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40-8110a70be2bfe7f75a2ea7f2a89cda4cc7732095-0.img
6e99899fa9584b11f4948d267013755f94812872  depot.galaxyproject.org-singularity-multiqc-1.13a--pyhdfd78af_1.img
6f469a1b9e0e8d0f6bfacf7e872727a08a506951  depot.galaxyproject.org-singularity-p7zip-15.09--h2d50403_4.img
5213a4d83fce3d5081e6fbddfbce15262bbc1ae6  depot.galaxyproject.org-singularity-pigz-2.3.4.img
0c09177a7f4f4ddfee4e7de42a57522886e720f5  depot.galaxyproject.org-singularity-samtools-1.15.1--h1170115_0.img
b43fe5f28a073f1adc32816dbdf14ce58ddb24ec  depot.galaxyproject.org-singularity-snpeff-5.1--hdfd78af_2.img
20d00d7fd579c401b91ab1e55cf3ff9be5496a0b  depot.galaxyproject.org-singularity-strelka-2.9.10--h9ee0642_1.img
247c3ee0dca78c3f417a8ca194771e0c05bd6193  depot.galaxyproject.org-singularity-tabix-1.11--hdfd78af_0.img
5f9dbd32c4928ef52ecc1bef26935ce84efdb0a0  depot.galaxyproject.org-singularity-tiddit-3.1.0--py39h59fae87_1.img
1cecef1af4bd14589a07ac179569bbdb339c6a01  depot.galaxyproject.org-singularity-ubuntu-20.04.img
75380f489c20a48d02f6a87756f711cc7e7c6f0e  depot.galaxyproject.org-singularity-vcftools-0.1.16--he513fc3_4.img
658092fc9ea961e214a578ad3dd8b959759563c5  nfcore-snpeff-5.1.GRCh38.img
9a1ee13c9cdb6d96dc16905192e03145ed24e742  nfcore-vep-106.1.GRCh38.img

**Comment by pontus** [comment]
Ok, that checksum doesn't match what I see on the file I pulled (076ea1537b96841248dd214526125c2858daf09a), so I'd say that file is corruped.

**Comment by jiehuichen** [comment]
> 

Thanks, how could I get the complete file, is there a download link?

**Comment by pontus** [comment]
`https://depot.galaxyproject.org/singularity/mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40:8110a70be2bfe7f75a2ea7f2a89cda4cc7732095-0`

**Comment by pontus** [comment]
(nf-core tools can of course also help with this, although you'd need to pull the entire pipeline IIRC.)

**Comment by jiehuichen** [comment]
> (nf-core tools can of course also help with this, although you'd need to pull the entire pipeline IIRC.)

Good news.

I run this pipeline after removing the corruped file, depot.galaxyproject.org-singularity-mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40-8110a70be2bfe7f75a2ea7f2a89cda4cc7732095-0.img.

Then the nf-core tools pulled the file automatically, which has right sha1sum as you mentioned above.

-[nf-core/sarek] Pipeline completed successfully-

Overall, this issue is resovled.

Thank you all.
