### ISSUE TITLE
Enable joint variant calling for germline samples

### ISSUE THREAD

**Issue by ikeller** [nf-core/sarek#75]
Allow calling of germline short variants jointly on multiple samples as outlined here https://software.broadinstitute.org/gatk/documentation/article?id=11019. This approach is expected to increase accuracy and sensitivity as it makes use of population-wide information.

Each sample is first called individually using HaplotypeCaller in -ERC GVCF mode. GenotypeGVCF is then run on all g.vcfs together. See GATK documentation here: https://software.broadinstitute.org/gatk/best-practices/workflow?id=11145

**Comment by MaxUlysse** [comment]
cf #185

**Comment by MaxUlysse** [comment]
from @jfnavarro on #185 
> It would be nice if Sarek would support to perform a joint analysis, for example with Strelka2 and HaplotypeCaller since they both support it. It would also be nice to combine variants for each caller (all samples).

**Comment by knokknok** [comment]
Hi, any progress on this?
Thanks!

**Comment by MaxUlysse** [comment]
Hi @knokknok
No progress on it yet, but hopefully will start working on it soon-ish now that there is modules for both these tools nf-core/modules.
Plan is to make a sub-workflow dedicated to that (Joint variant calling).

**Comment by georgiesamaha** [comment]
Hi all, has any progress been made on this since the Hackathon in October 2021?

**Comment by FriederikeHanssen** [comment]
@GCJMackenzie is working on it at the moment to add it to 3.0

**Comment by FriederikeHanssen** [comment]
added in #595
