### ISSUE TITLE
Add an option in '--tools' parameter for QC task only

### ISSUE THREAD

**Issue by senzhaocode** [nf-core/sarek#753]
### Description of feature

Dear Serak developer, 

I have tumor-normal pair bam files, and would like to only do a BAM file QC analysis (without any variant calling process). Is that possible for add such an option in --tools parameter, and ask the pipeline to run QC tasks only (e.g. fastqc, samtools, BamQC, bcftools, multiQC....). 

Thanks in advance

Sen

**Comment by FriederikeHanssen** [comment]
Hi @senzhaocode ! Thank you for your inquiry. Starting from step duplicate marking + skipping markduplicates with `skip_tools`, you could run mosdepth & samtools which will then generate a multiqc report. However, the remaining qc steps are not possible. Fastqc is run on the input reads, and bcftools/vcftools on the resulting vcf files.

Currently we don't see that this would be in scope of this pipeline and we are not planning to add this feature at the moment. 

Cheers,
Rike
