### ISSUE TITLE
cnvkit Process exceeded running time limit (4h)

### ISSUE THREAD

**Issue by sheucke** [nf-core/sarek#756]
I do get the following error, when using the following run command with json.params file:

comand:

```bash
nextflow run nf-core/sarek -r 3.0 -profile docker -params-file nf-params.json -bg
```

params.json:

```json
{
    "input": "example_pair_fastq.csv",
    "tools": "freebayes,msisensorpro,controlfreec,snpeff,vep,cnvkit",
    "wes": true,
    "vep_cache_version": 104,
    "vep_cache": "\/mnt\/quobyte\/local_vep_cache_dir_tmp",
    "max_cpus": 28,
    "max_memory": "245.GB",
    "max_time": "10.h"
}
```

execution_report error:

Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: null.

The full error message was:

Error executing process > 'NFCORE_SAREK:SAREK:PAIR_VARIANT_CALLING:RUN_CNVKIT:CNVKIT_BATCH (SAMPLE_ID_SRR7890844_vs_SAMPLE_ID_SRR7890845)'

Caused by:
  Process exceeded running time limit (4h)

Command executed:

  samtools view -T Homo_sapiens_assembly38.fasta --fai-reference Homo_sapiens_assembly38.fasta.fai SAMPLE_ID_SRR7890844.recal.cram -@ 2 -o SAMPLE_ID_SRR7890844.recal.bam
  samtools view -T Homo_sapiens_assembly38.fasta --fai-reference Homo_sapiens_assembly38.fasta.fai SAMPLE_ID_SRR7890845.recal.cram -@ 2 -o SAMPLE_ID_SRR7890845.recal.bam
  
  cnvkit.py \
      batch \
      SAMPLE_ID_SRR7890844.recal.bam \
      --normal SAMPLE_ID_SRR7890845.recal.bam \
      --fasta Homo_sapiens_assembly38.fasta \
       \
      --targets wgs_calling_regions.hg38.bed \
      --processes 2 \
      --method hybrid --diagram --scatter
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SAREK:SAREK:PAIR_VARIANT_CALLING:RUN_CNVKIT:CNVKIT_BATCH":
      samtools: $(echo $(samtools --version 2>&1) | sed 's/^.*samtools //; s/Using.*$//')
      cnvkit: $(cnvkit.py version | sed -e "s/cnvkit v//g")
  END_VERSIONS

Command exit status:
  -

Command output:
  (empty)

Command error:
  Extracting sequences from chromosome chr2
  Extracting sequences from chromosome chr3
  Extracting sequences from chromosome chr4
  Extracting sequences from chromosome chr5
  Extracting sequences from chromosome chr6
  Extracting sequences from chromosome chr7
  Extracting sequences from chromosome chr8
  Extracting sequences from chromosome chr9
  Extracting sequences from chromosome chr10
  Extracting sequences from chromosome chr11
  Extracting sequences from chromosome chr12
  Extracting sequences from chromosome chr13
  Extracting sequences from chromosome chr14
  Extracting sequences from chromosome chr15
  Extracting sequences from chromosome chr16
  Extracting sequences from chromosome chr17
  Extracting sequences from chromosome chr18
  Extracting sequences from chromosome chr19
  Extracting sequences from chromosome chr20
  Extracting sequences from chromosome chr21
  Extracting sequences from chromosome chr22
  Extracting sequences from chromosome chrX
  Extracting sequences from chromosome chrY
  Correcting for GC bias...
  Correcting for RepeatMasker bias...
  /usr/local/lib/python3.9/site-packages/cnvlib/reference.py:149: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
    ref_df = ref_df.append(anti_ref_df, ignore_index=True, sort=False)
  Calculating average bin coverages
  Calculating bin spreads
  Targets: 5287260 (48.2236%) bins failed filters (log2 < -5.0, log2 > 5.0, spread > 1.0)
  Antitargets: 1187 (100.0000%) bins failed filters
  Wrote ./reference.cnn with 10965235 regions
  Running 1 samples in 2 processes (that's 2 processes per bam)
  Running the CNVkit pipeline on SAMPLE_ID_SRR7890844.recal.bam ...
  [E::idx_find_and_load] Could not retrieve index file for 'SAMPLE_ID_SRR7890844.recal.bam'
  Indexing BAM file SAMPLE_ID_SRR7890844.recal.bam
  Processing reads in SAMPLE_ID_SRR7890844.recal.bam
  Time: 3422.543 seconds (29624 reads/sec, 3203 bins/sec)
  Summary: #bins=10964048, #reads=101389421, mean=9.2474, min=0.0, max=7112.3650793650795 
  Percent reads in regions: 95.430 (of 106244758 mapped)
  Wrote ./SAMPLE_ID_SRR7890844.targetcoverage.cnn with 10964048 regions
  Processing reads in SAMPLE_ID_SRR7890844.recal.bam
  Time: 2.356 seconds (0 reads/sec, 504 bins/sec)
  Summary: #bins=1187, #reads=0, mean=0.0000, min=0.0, max=0.0 
  Percent reads in regions: 0.000 (of 106244758 mapped)
  Wrote ./SAMPLE_ID_SRR7890844.antitargetcoverage.cnn with 1187 regions
  Processing target: SAMPLE_ID_SRR7890844
  Keeping 5676800 of 10964048 bins
  Correcting for GC bias...
  Correcting for density bias...

Work dir:
  /mnt/quobyte/sarek_3_complete/work/34/4b16903a28c29a3f2a021605318444

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by FriederikeHanssen** [comment]
Hi @sheucke ! This unfortuantely sometimes happens since the resource requests often depend on the data analysed. You can easily extend the time for the process by adding into a custom.config:
```
process {

     withName:'NFCORE_SAREK:SAREK:PAIR_VARIANT_CALLING:RUN_CNVKIT:CNVKIT_BATCH' {
        time = 8.h
   }
}
```

and adding it with `-c` to the run command. For more info on this and how to automatically allow resubmission in case of time out, see here:  https://nf-co.re/docs/usage/troubleshooting#i-get-a-exceeded-job-memory-limit-error

**Comment by ollieeknight** [comment]
Friederike,

I wanted to ask - is there a param I can put into the custom config that will extend the maximum runtime of every process, instead of individually? The cluster I'm running on is quite slow due to oversubscription so it would be great.

Best

Ollie

**Comment by maxulysse** [comment]
@ollieeknight you can use the params `max_time` for that: https://nf-co.re/sarek/dev/parameters#max_time

**Comment by ollieeknight** [comment]
Thank you Maxime! I've set that, but I still get timeout for several functions at 8h. My function is
```
nextflow run nf-core/sarek --input samplesheet.csv --outdir lgl1_wes_outs --genome GATK.GRCh38 -c cubi.config -profile singularity --email oliver.knight@drfz.de --tools cnvkit,mutect2,strelka,snpeff,vep -resume
```
where my config is
```
params {
    max_memory = 128.GB
    max_cpus = 32
    max_time = 144.h
}

process {

     withName:'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_SINGLE_STRELKA:STRELKA_SINGLE' {
        time = 48.h
   }
}
process {

     withName:'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_SOMATIC_ALL:BAM_VARIANT_CALLING_SOMATIC_MUTECT2:MUTECT2_PAIRED' {
     time = 48.h
   }
}

process {

     withName:'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_SOMATIC_ALL:BAM_VARIANT_CALLING_SOMATIC_STRELKA:STRELKA_SOMATIC' {
     time = 48.h
   }
}

process {

    withName:'NFCORE_SAREK:SAREK:CRAM_QC_RECAL:MOSDEPTH' {
    time = 48.h
   }
}
```
A bit messy I know, but it's my first time using nextflow so wanted to make sure everything worked well...

**Comment by ollieeknight** [comment]
The ones that I've had to set custom times for - I started with the first (strelka) but each time I have resumed it the next one appeared.

**Comment by FriederikeHanssen** [comment]
`max_time`should work as a ceiling. You could do this:

```
  process {
       time = 144.h
       
       withName:'NFCORE_SAREK:SAREK:CRAM_QC_RECAL:MOSDEPTH' {
        <here-any-other-custom-configurations>
       }
    }
}

**Comment by ollieeknight** [comment]
thank you - I think I'll just have to copy and paste them all in but this is still great! I really appreciate the help.

**Comment by chumawinnie** [comment]
Issue with Extending Process Time Limit in nf-core/sarek Using Custom Configuration

Hi nf-core community,

I’m encountering an issue while running the nf-core/sarek pipeline where a specific process (`MUTECT2_PAIRED`) consistently exceeds the default time limit of 8 hours, causing the pipeline to fail. I attempted to resolve this by providing a custom configuration file to extend the time limit, but it seems the changes are not being applied as expected.

### Pipeline Command

I’m running the pipeline with the following command:

```bash
nextflow run nf-core/sarek -profile docker \
  --input sample-merge-sheet.csv \
  --outdir /home/winnie/test-work-sarek/Merged-WES-Results \
  --genome hg19 \
  --dbsnp /home/winnie/whole-Exon-single-seq/ref-genome/known_sites.vcf/dbsnp_138.hg19.vcf.gz \
  --known_indels /home/winnie/whole-Exon-single-seq/ref-genome/known_indels.vcf/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz \
  --max_cpus 20 \
  --max_memory '30 GB' \
  --wes \
  --intervals /home/winnie/whole-Exon-single-seq/ref-genome/exom_targets.bed/HyperExomeV2_primary_targets.hg19.bed \
  --tools mutect2,strelka \
  --pon /home/winnie/whole-Exon-single-seq/ref-genome/panel-of-normal/updated_Mutect2-exome-panel_vcf.vcf.gz \
  --vep \
  --vep_cache /home/winnie/vep_cache/homo_sapiens/112_GRCh37 \
  --vep_species homo_sapiens \
  --vep_assembly GRCh37 \
  -c custom.config
```

### Custom Configuration File

I created a `custom.config` file in the pipeline's working directory with the following content:

```groovy
process {
    time = '72h'  // Set a global time limit to 72 hours

    withName: 'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_SOMATIC_ALL:BAM_VARIANT_CALLING_SOMATIC_MUTECT2:MUTECT2_PAIRED' {
        memory = '30 GB'  // Allocate more memory for the Mutect2 process
        cpus = 20         // Allocate more CPUs for the Mutect2 process
        time = '72h'      // Specific time limit for this process
    }
}
```

### Issue

Despite adding the `-c custom.config` option to my Nextflow command, the pipeline continues to fail with the error:

```
ERROR ~ Error executing process > 'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_SOMATIC_ALL:BAM_VARIANT_CALLING_SOMATIC_MUTECT2:MUTECT2_PAIRED (Tumour_vs_Normal)'

Caused by:
  Process exceeded running time limit (8h)
```

It seems that the custom time limit isn’t being applied to the process, and I’m not sure why. 

### Steps Taken

- I confirmed that the `custom.config` file is in the correct directory.
- I attempted both global time limits and process-specific settings.
- I checked the logs but didn’t find any indication that the custom configuration was applied.


Could someone help me understand why the custom time limit is not being applied? Is there a specific way to ensure that custom configuration files are correctly recognized and applied by the nf-core/sarek pipeline?

Any guidance or suggestions would be greatly appreciated.

Thank you!

Winner 
![sarek-failed](https://github.com/user-attachments/assets/1b87d0a3-8394-48e6-998b-c0efe929a647)
![sarek-failed](https://github.com/user-attachments/assets/a12ba4fe-4642-4835-bd7e-f1df908d2c4e)

**Comment by FriederikeHanssen** [comment]
Hey! Overall the config looks fine. can you try with this syntax:


```
process {
    // adding a regex to prevent the fully qualified name to take precedence
    withName: ".*" {
            time = 72.h
    }

    withName: 'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_SOMATIC_ALL:BAM_VARIANT_CALLING_SOMATIC_MUTECT2:MUTECT2_PAIRED' {
        memory = 30.GB  // Allocate more memory for the Mutect2 process
        cpus = 20         // Allocate more CPUs for the Mutect2 process
        time = 72.h      // Specific time limit for this process
    }
}
```

**Comment by chumawinnie** [comment]
Hi Friederike,

Thank you so much for your prompt and helpful response! I appreciate the detailed explanation and the solution you provided. The addition of the regex to ensure the time limit applies correctly makes perfect sense, and I’m confident this will resolve the issue I've been encountering.

I also want to take this opportunity to express my gratitude for the fantastic work you're doing at Universitätsklinikum Tübingen. Your contributions to the nf-core community are invaluable, and your dedication to helping others is truly commendable. It's a privilege to benefit from your expertise.

Many thanks again from Augsburg, and I look forward to putting your advice into practice.

Best regards,

Winner

**Comment by TILccit** [comment]
Hello [chumawinnie](https://github.com/chumawinnie), 
Did it work for you?
I am struggling with the similar issue.
Thank you.
Best,
Shawez

**Comment by chumawinnie** [comment]
Hey, Shawez. Yes, i did worked out. let me know if you need help

**Comment by TILccit** [comment]
Hello [chumawinnie](https://github.com/chumawinnie),
Thank you very much for your reply. 

Actully, I am running nf-core/sarek on Ubuntu 22.04.3 LTS (GNU/Linux 5.15.153.1-microsoft-standard-WSL2 x86_64). I encountered the error: "Process exceeded running time limit (8h)."

Command:
nextflow -log /mnt/f/ARIA/sarek_output/log/M14TIL55.log
run nf-core/sarek -r 3.4.2 -profile docker --input M14TIL55_sarekinput.csv --genome GATK.GRCh38 --outdir /pt55/out/ --max_cpus 8 --tools mutect2,strelka,vep,snpeff,controlfreec,ascat --only_paired_variant_calling -c custom.config

Execution_report error:
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: null.

The full error message was:

Error executing process > 'NFCORE_SAREK:SAREK:FASTQC (55_healthy-1)'

Caused by:
Process exceeded running time limit (8h)

Command executed:

printf "%s %s\n" noinfo-pt55healthy_R1_001.fastq.gz 55_healthy-1_1.gz noinfo-pt55healthy_R2_001.fastq.gz 55_healthy-1_2.gz | while read old_name new_name; do
[ -f "${new_name}" ] || ln -s $old_name $new_name
done

fastqc
--quiet
--threads 4
--memory 4096
55_healthy-1_1.gz 55_healthy-1_2.gz

cat <<-END_VERSIONS > versions.yml
"NFCORE_SAREK:SAREK:FASTQC":
fastqc: $( fastqc --version | sed '/FastQC v/!d; s/.*v//' )
END_VERSIONS

Command exit status:
Command output:
application/gzip
application/gzip

Command wrapper:
application/gzip
application/gzip

Work dir:
/mnt/f/ARIA/work/0b/66d2170cbbe48f92750fc33fc0ca1e

Tip: when you have fixed the problem you can continue the execution adding the option -resume to the run command line

Please note that: My custom.config is
params {
max_memory = 128.GB
max_time = 144.h
}
process {

 withName: 'NFCORE_SAREK:SAREK:FASTQC (55_healthy-1)' {
    time = 48.h // Specific time limit for this process
}
}
process {

 withName: 'NFCORE_SAREK:SAREK:FASTQC (55_baseline-1)' {
    time = 48.h // Specific time limit for this process
}
}
process {

 withName: 'NFCORE_SAREK:SAREK:FASTQC (55_progression-1)' {
    time = 48.h // Specific time limit for this process
}
}

### .command.log from
Work dir:
/mnt/f/ARIA/work/0b/66d2170cbbe48f92750fc33fc0ca1e

application/gzip
application/gzip
Error response from daemon: cannot stop container: nxf-WF6UjjdSRFxhxbOdAIedosOd: tried to kill container, but did not receive an exit event

Could you please help me with this?

**Comment by chumawinnie** [comment]
could you please share your config file

**Comment by TILccit** [comment]
[custom.config.txt](https://github.com/user-attachments/files/17128590/custom.config.txt)

Kindly find the attached config file. 

I using **-c /mnt/f/ARIA/custom.config \** in my nextflow command

Thank you.

**Comment by TILccit** [comment]
FYI:
I created this config file as txt and then I chnaged the extenstion using mv command:
mv custom.config.txt custom.config

**Comment by chumawinnie** [comment]
ok, i have seen it, please which step caused the abrupt in-completion  of the process?
could you help me with screenshot of the error message that could broken, like i provided above, so i can know how to structure your config file

**Comment by chumawinnie** [comment]
this should work, but provide the above request to be sure
params {
    max_memory = 128.GB
    max_time = 144.h
}

process {
    // Apply default time limit of 100 hours to all processes
    withName: ".*" {
        time = 100.h
    }

    // Specific time limit for FASTQC processes
    withName: 'NFCORE_SAREK:SAREK:FASTQC .*' {
        time = 48.h
    }
}

**Comment by FriederikeHanssen** [comment]
Tracked here as well: #1634 

@chumawinnie small correction: the configs apply to all samples and the `withName` directive just needs process name you need to remove the wildcard from the process-specific declaration:

// Specific time limit for FASTQC processes
withName: 'NFCORE_SAREK:SAREK:FASTQC' {
    time = 48.h
}

**Comment by TILccit** [comment]
I have three sample type: baseline, healthy and prefression. Crashing can start with any one and finally stpe. I am shring screenshot for healthy and pregression. 
My Command:
nextflow -log /mnt/f/ARIA/sarek_output/log/M14TIL55.log
run nf-core/sarek -r 3.4.2 -profile docker --input M14TIL55_sarekinput.csv --genome GATK.GRCh38 --outdir /pt55/out/ --max_cpus 8 --tools mutect2,strelka,vep,snpeff,controlfreec,ascat --only_paired_variant_calling -c custom.config
![healthy](https://github.com/user-attachments/assets/1c368bef-30aa-4f53-8b0b-25319111a5ba)
![progression](https://github.com/user-attachments/assets/ff5ed17c-9746-4d5a-a49d-5a0d151ad6b7)

**Comment by FriederikeHanssen** [comment]
The above configuration will apply the time limit to all FASTQC tasks, so to all your samples.

**Comment by chumawinnie** [comment]
@FriederikeHanssen thank you for the correction, @TILccit  please try this the below!




params {
    max_memory = 128.GB
    max_time = 144.h
}

process {
    // Apply default time limit of 100 hours to all processes
    withName: ".*" {
        time = 100.h
    }

    // Specific time limit for FASTQC processes
    withName: 'NFCORE_SAREK:SAREK:FASTQC' {
        time = 48.h
    }
}

**Comment by TILccit** [comment]
Thanks both, 
Now I am running the my pipeline wiht the follwoing config file:
params {
max_memory = 128.GB
max_time = 144.h
}

process {
// Apply default time limit of 100 hours to all processes
withName: ".*" {
time = 100.h
}

// Specific time limit for FASTQC processes
withName: 'NFCORE_SAREK:SAREK:FASTQC' {
    time = 48.h
}
}

I will update withe progress.
