### ISSUE TITLE
[FEATURE] Option to output gvcf files from haplotypecaller

### ISSUE THREAD

**Issue by wpoehlm** [nf-core/sarek#764]
### Description of feature

In previous versions of Sarek, there was an option to save gvcf files as output from the GATK haplotypecaller. With the addition of joint-calling to the pipeline, the option to save gvcfs is no longer present in Sarek 3. I suggest that this feature should be re-introduced for a few reasons:

- Analysts often use gvcf files for QC and preliminary analysis
- QC should be performed before joint calling so that poor-quality samples can be flagged and removed before joint calling. Without the option to save gvcfs, the user is locked into doing the joint calling blindly with all samples
- If a user wants to add additional samples or cohorts at a later time, they will be unable to perform joint calling without access to previously generated gvcf outputs. 

I realize that this issue is similar to [#453](https://github.com/nf-core/sarek/issues/453), so if you would like me to remove it and expand the conversation on that issue just let me know!

Best,
Will

**Comment by FriederikeHanssen** [comment]
Hey! added in #1172 , it was partially already there but should be now available for various scenarios
