### ISSUE TITLE
containers missing in nf-core download

### ISSUE THREAD

**Issue by egenomics** [nf-core/sarek#769]
### Description of the bug

Hi,

I have downloaded sarek latest version using nf-core tools, with all singularity containers (in theory). When I move the pipeline to the cluster (no internet access) and execute it selecting deepvariant as a variant caller it fails locating the deepvariant container and therefore the job fails (no internet).

I can download it manually with the command line:
```bash
singularity pull  --name google-deepvariant-1.3.0.img.pulling.1663095569629 docker://google/deepvariant:1.3.0 > /dev/null
```

but perhaps this is happening for other containers? It might be worth taking a look into the list.

Best,
JL

### Command used and terminal output

```console
Error executing process > 'NFCORE_SAREK:SAREK:GERMLINE_VARIANT_CALLING:RUN_DEEPVARIANT:DEEPVARIANT (WTCHG_722292)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name google-deepvariant-1.3.0.img.pulling.1663095569629 docker://google/deepvariant:1.3.0 > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://google/deepvariant:1.3.0: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp 54.242.59.189:443: i/o timeout
```

**Comment by egenomics** [comment]
I have downloaded again the dev version with nf-core download and this time I see a container names deepvariant. I will run the platinum sample in our HPC and let you know if sarek recognizes the container.

Best,
JL

**Comment by maxulysse** [comment]
:crossed_fingers:

**Comment by egenomics** [comment]
Hi,
I believe it now finds the deepvariant container and runs it succesfully, generating the haplotypecaller VCF as well as the deepvariant VCF.

However the job itself does not reach completion as is missing yet another container:

_Error executing process > 'NFCORE_SAREK:SAREK:GERMLINE_VARIANT_CALLING:RUN_HAPLOTYPECALLER:SINGLE_SAMPLE:CNNSCOREVARIANTS (WTCHG_722293)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name broadinstitute-gatk-4.2.6.1.img.pulling.1664843838919 docker://broadinstitute/gatk:4.2.6.1 > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://broadinstitute/gatk:4.2.6.1: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp 34.205.13.154:443: i/o timeout_

Possibly is occuring the same that happened to the deepvariant container. There is actually a downloaded container from gatk:
depot.galaxyproject.org-singularity-gatk4-4.2.6.1--hdfd78af_0.img

So perhaps is just a matter of the name. Could this be happening not only for these 2 but for more containers?

JL

**Comment by maxulysse** [comment]
OK, I see the issue, and I know how to fix it now:
https://github.com/nf-core/modules/blob/master/modules/nf-core/gatk4/cnnscorevariants/main.nf
we need double quotes here as well...
I'll fix that ASAP

**Comment by maxulysse** [comment]
OK, can you try `nf-core download nf-core/sarek -r dev -c singularity` one more time, this should download the correct `broadinstitute/gatk:4.2.6.1` container

**Comment by egenomics** [comment]
It works!

However I am only using --tools haplotypecaller,deepvariant so perhaps it would be wise to check if there are any other containers from other tools in a similar situation.

JL

**Comment by maxulysse** [comment]
You actually got super lucky and managed to find the only 2 modules in Sarek that defined containers differently

**Comment by egenomics** [comment]
Hi,
I believe VEP has the same issue:
Error executing process > 'NFCORE_SAREK:SAREK:ANNOTATE:ANNOTATION_ENSEMBLVEP:ENSEMBLVEP (WTCHG_722293_NE755566)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name nfcore-vep-106.1.GRCh38.img.pulling.1665616628628 docker://nfcore/vep:106.1.GRCh38 > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://nfcore/vep:106.1.GRCh38: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp 34.205.13.154:443: i/o timeout

**Comment by pontus** [comment]
That looks like an older version of sarek?  For those it's a known issue that nf-core download to not pick up these containers.

**Comment by pontus** [comment]
Ok, my bad.

@maxulysse @FriederikeHanssen I expect you've thought about this already, but just to check; would it be sensible to add placeholder processes for the provided caches so that `nf-core download` would work.

**Comment by maxulysse** [comment]
Yes, but the main issue is that we need to figure out how to deal with that within tools.
Possibility would be to use the `.nf-core-lint.yml` file to handle alternate download based on options:
https://github.com/nf-core/tools/issues/1051

**Comment by pontus** [comment]
Yes, these fake processes would be a stop-gap until tools offers a better way.

**Comment by JSegueni** [comment]
I had a similar issue recently (same error message with another workflow) and was able to solve the problem by downgrading sqlite to 3.40. Hopefully, this can help someone!
