### ISSUE TITLE
Allow for processing of single-end data

### ISSUE THREAD

**Issue by dmalzl** [nf-core/sarek#781]
### Description of feature

For a pilot analysis we wanted to use sarek to call somatic variants from single-end data. However, testing and having a look at the pipeline code revealed that the newest version strictly requires paired-end data. This was not the case for previous versions of the pipeline as far as I know. Is there a possibility to allow for the usage of single-end data for variant calling too?

**Comment by FriederikeHanssen** [comment]
Hi @dmalzl, we never actively supported single-end data for sarek. Currently this is not in the scope of the pipeline and we don't plan to support it.
