### ISSUE TITLE
How to prepare the basic referece, GATK bundle and annotation database with bad network connection?

### ISSUE THREAD

**Issue by xflicsu** [nf-core/sarek#787]
### Description of the bug

Dear sarek developers,
I wonder implement sarek to my WGS project. But the network is bad. So, how can I build this pipeline step by step with local download reference and other basic database for variation detection and annotation?
BTW, for the bad network of my platform, the basic database for this pipeline could not download directly with wget commend, any suggestion for this situation.

Thanks,

**Comment by FriederikeHanssen** [comment]
Hi @xflicsu ! Have you considered the nf-core/tools option `download` https://nf-co.re/tools/#downloading-pipelines-for-offline-use . This will download the pipeline and make it usable in an offline setting. IN addition, I would recommend downloading the igenomes references you need before using the pipeline and specifiying the `igenomes_path`: https://ewels.github.io/AWS-iGenomes/

Apologies for the delayed response between the Nextflow Summit and some vacation afterwards, I didn't get to the issue beforehand.
