### ISSUE TITLE
Can be tumor-only somatic variant calling performed using Strelka?

### ISSUE THREAD

**Issue by ariadnaaterrades** [nf-core/sarek#803]
### Description of the bug

As you mention in your Nextflow pipeline: @https://nf-co.re/sarek/3.0.2/parameters it would be possible to obtain the results of tumor-only somatic variant calling using strelka tool (among other methods). 

I've run the pipeline using strelka with tumor-only samples and I've ended up having results for germline variants (variants.vcf.gz, genome.S${N}.vcf.gz) instead of somatic ones (somatic.snvs.vcf.gz, somatic.indels.vcf.gz) (@https://github.com/Illumina/strelka/blob/v2.9.x/docs/userGuide/README.md ).

I read that strelka can perform somatic variant calling when you have tumor-normal samples pairs, however it is not possible to do so when you have tumor-only samples.  @https://academic.oup.com/bioinformatics/article/28/14/1811/218573. Did I miss any extra parameter?

Sorry in advance if i misunderstood something.

**Comment by FriederikeHanssen** [comment]
Hi @ariadnaaterrades ! Can you please post some more details: command run, samplesheet, any other configs/param files you are using, and the nextflow log?

**Comment by ariadnaaterrades** [comment]
Hi @FriederikeHanssen , thanks for your quick reply.

I've been using mainly the default parameters with GRCh38 genome version , here is the command run:

> cd /DNA/Batch_01
> srun --mpi=none --mem=40G --nodes=4 --ntasks-per-node=2 --partition=long --pty bash -i 
> 
> module load Java/13.0.2
> module load singularity/3.7.3
> 
> ./nextflow run nf-core/sarek --input ./samplesheet_10102022.csv --outdir /DNA/Batch_01/ --genome GATK.GRCh38 -profile singularity --wes --intervals /DNA/xgen-exome-hyb-panel-v2-targets-hg38.bed --tools mutect2,freebayes,cnvkit,strelka
> 

The sample sheet looks like this:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 6.4.7.2 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>


patient | status | sample | lane | fastq_1 | fastq_2
-- | -- | -- | -- | -- | --
Sample1 | 1 | Sample1_Tumor | 1 | /DNA/Batch_01/Sample1_R1_001.fastq.gz | /DNA/Batch_01/Sample1_R2_001.fastq.gz
Sample2 | 1 | Sample2_Tumor | 1 | /DNA/Batch_01/Sample2_R1_001.fastq.gz | /DNA/Batch_01/Sample2_R2_001.fastq.gz
Sample3 | 1 | Sample3_Tumor | 1 | /DNA/Batch_01/Sample3_R1_001.fastq.gz | /DNA/Batch_01/Sample3_R2_001.fastq.gz
Sample4 | 1 | Sample4_Tumor | 1 | /DNA/Batch_01/Sample4_R1_001.fastq.gz | /DNA/Batch_01/Sample4_R2_001.fastq.gz
Sample5 | 1 | Sample5_Tumor | 1 | /DNA/Batch_01/Sample5_R1_001.fastq.gz | /DNA/Batch_01/Sample5_R2_001.fastq.gz
Sample6 | 1 | Sample6_Tumor | 1 | /DNA/Batch_01/Sample6_R1_001.fastq.gz | /DNA/Batch_01/Sample6_R2_001.fastq.gz
Sample7 | 1 | Sample7_Tumor | 1 | /DNA/Batch_01/Sample7_R1_001.fastq.gz | /DNA/Batch_01/Sample7_R2_001.fastq.gz


</body>

</html>

And the thing is that there is no error in the execution_report_2022-10-11_13-00-30.html file...all the processes seem to be complete correctly. I did end up having output files, but not the somatic ones. For that reason I decided to look at the strelka tool information and I realized that it might not be possible to run tumor-only somatic variant calling.

**Comment by FriederikeHanssen** [comment]
Hey! Apologies for the late reply, I was OOO, but back now. So strelka is run with the following command for tumor-only samples:

https://github.com/nf-core/sarek/blob/master/modules/nf-core/modules/strelka/germline/main.nf

So with the "germline" module which is the only one we have available now as you correctly noted. However, there should still be the respective output present for you sample names. The somatic ones can only be called with paired samples to my knowledge.

**Comment by ariadnaaterrades** [comment]
Hi!

As you mention, I ended up having germline results instead of somatic ones. However, I decided to run strelka among other methods to perform tumor-only somatic variant calling because **in your website indicates that it would be possible to do so**. [https://nf-co.re/sarek/3.0.2/parameters](url)

![image](https://user-images.githubusercontent.com/63337883/199698397-dbc6d981-9eda-45ed-85e4-b98976e4bd51.png)

As you said, according to strelka's paper: [https://academic.oup.com/bioinformatics/article/28/14/1811/218573](url) **it is not possible to run it** but when I saw your website information I thought that you may have implemented some changes in order to be capable of running it. 

I think that changing the website information could prevent other people from misunderstanding.

Thank you so much!
