### ISSUE TITLE
resolved path doesn't match with opened path singularity

### ISSUE THREAD

**Issue by jackmo375** [nf-core/sarek#804]
### Description of the bug

I am encountering a bug previously described on the archived version of this pipeline here: https://github.com/SciLifeLab/Sarek/issues/780

basically the issue is that when I run a pipeline with the sarek container, I get the following:
```
Error executing process > 'trimSampleReads (18)'

Caused by:
  Process `trimSampleReads (18)` terminated with an error exit status (255)

Command executed [/mnt/lustre/users/jmorrice/projects/fifty-genomes/templates/pre-processing/trim-sample-reads.sh]:

  #!/bin/bash
  
  trim_galore     --basename SCD-369_trimmed     --paired     --fastqc     --gzip     HCFVTCCXX-7_S0_L007_R1_001.fastq.gz HCFVTCCXX-7_S0_L007_R2_001.fastq.gz

Command exit status:
  255

Command output:
  (empty)

Command error:
  FATAL:   resolved path /mnt/lustre/users/jmorrice/projects/fifty-genomes/software/sarek_latest.sif doesn't match with opened path /mnt/lustre/users/jmorrice/projects/fifty-genomes/software/sarek_latest.sif (deleted)
```

Did anyone find a resolution to this issue? The thread ended when the pipeline was moved to nf core and I could not find the thread continued on this new repo. 

Warm regards,
Jack

**Comment by maxulysse** [comment]
Hi @jackmo375 which Nextflow version are your using?
And which Sarek version?

**Comment by jackmo375** [comment]
Im using nextflow v22. Im actually not using the sarek pipeline, just the container, with a custom pipeline.

**Comment by jackmo375** [comment]
Thank you for your reply! I've been stuck on this for a while :)

**Comment by maxulysse** [comment]
how do you specify the path to the container, or the singularity cache dir ?
In either command line, config file, or profile, env variable...

**Comment by jackmo375** [comment]
I specify the path to the sarek container image (.sif) in the config file, with the process scope. This image file is not in the same place as the singularity cache directory, and the cache directory path is also specified in the config file. I am running the pipeline on an HPC shared filesystem.

**Comment by maxulysse** [comment]
Can you try supplying the singularity image with `-with-singularity /mnt/lustre/users/jmorrice/projects/fifty-genomes/software/sarek_latest.sif`?

**Comment by jackmo375** [comment]
Hi @maxulysse OK I just tried with this option and had the same error:

Command error:
  FATAL:   resolved path /mnt/lustre/users/jmorrice/projects/fifty-genomes/software/sarek_latest.sif doesn't match with opened path /mnt/lustre/users/jmorrice/projects/fifty-genomes/software/sarek_latest.sif (deleted)

**Comment by maxulysse** [comment]
@pontus any idea on that one?

**Comment by pontus** [comment]
https://github.com/apptainer/singularity/issues/3249?

What's the version of singularity here?

**Comment by jackmo375** [comment]
I am running singularity 3.5.3

**Comment by pontus** [comment]
Then I'd recommend upgrading that for a start.

**Comment by jackmo375** [comment]
Ah OK, for that I will have to contact the administrators of the HPC system I am using.

This seems to be an issue with singularity rather than the sarek container?

**Comment by pontus** [comment]
Yes, that's how it looks to me.
