### ISSUE TITLE
Collect MarkDuplicatesSpark metrics with the standalone Picard tool EstimateLibraryComplexity

### ISSUE THREAD

**Issue by maxulysse** [nf-core/sarek#81]
cf #64 
cf https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_hellbender_tools_spark_transforms_markduplicates_MarkDuplicatesSpark.php
> Collecting duplicate metrics slows down performance and thus the metrics collection is optional and must be specified for the Spark version of the tool with '-M'. It is possible to collect the metrics with the standalone Picard tool EstimateLibraryComplexity.

**Comment by FriederikeHanssen** [comment]
Addressed in PR #388
