### ISSUE TITLE
pipeline launch from nf-core website - input csv bug

### ISSUE THREAD

**Issue by aheritas** [nf-core/sarek#811]
### Description of the bug

When inputing the csv path in the graphical interface (website) of nf-core (e.g. https://nf-co.re/launch) the input csv shows an error even when the path is correct. The error is related to pattern matching.  For an example how this looks like, see: 
![image](https://user-images.githubusercontent.com/106694299/200316592-56c8bb4b-0d25-46a3-bf6a-459236f10609.png) 

### System information

-     Hardware: nf-core website
-     Version of nf-core/sarek: 3.0.2

**Comment by FriederikeHanssen** [comment]
Hi @aheritas ! Thank you for reporting this, we are tracking this issue and are working on a fix in #694 . I would therefore close this issue to keep everything in one place :)
