### ISSUE TITLE
Rename GRCh38 > hg38 in igenomes.config

### ISSUE THREAD

**Issue by drpatelh** [nf-core/sarek#86]
The Broad/GATK ships their genome resource bundles relative to UCSC builds i.e. `hg19` and `hg38` and these are also used in Sarek. However, they have been named according to the Ensembl naming convention i.e. `GRCh38` and `GRCh37`. This is slightly misleading and also adds to the confusion when trying to figure out how the pipeline is using and providing its genome reference data. 

The keys in `igenomes.config` for these assemblies will have to be changed from `GRCh38` > `hg38` and `GRCh37` > `hg19`, and any custom files added for use with the pipeline will also have to be renamed appropriately (and uploaded to AWS iGenomes!).

**Comment by MaxUlysse** [comment]
cf: https://github.com/nf-core/sarek/issues/184

**Comment by maxulysse** [comment]
Fixed: https://github.com/nf-core/sarek/blob/57c41408d8f7b502fd9f5e81bef75fe0abec9aa5/conf/igenomes.config#L14-L66
