### ISSUE TITLE
Is it possible to change Mutect2 variant read threshold for samples with lower tumour cellularity 

### ISSUE THREAD

**Issue by Ahas4** [nf-core/sarek#866]
### Description of feature

The type of tumour samples I work with tend to have low tumour cellularity by nature, when running Mutect2 (nf-core/sarek) in Wes mode, I have noticed that some of the variants are filleted out by Mutect2 , so for example a sample with 10% tumour cellularity that has a variant read below 13% is excluded although this variant is present and a true variant, which is important to be aware of in case of rare cancers. could you please guide me to how to solve this issue and get Mutect2 to have a lower filter threshold. 

To run the pipeline I use : 

 nextflow run nf-core/sarek -r 3.0.2 -profile singularity \
-c nextflow.config \
 --input Samplesheet.csv \
 -w /scratch/designated work space \
 --genome GATK.GRCh38 \
 --wes \
 --intervals /specified target_sorted.unique.bed \
 --tools cnvkit,freebayes,manta,mpileup,mutect2,strelka,tiddit,vep,snpeff
-- step annotate ^((cnvkit|freebayes|manta|merge|mpileup|mutect2|snpeff|strelka|tiddit|vep)?,?)*[^,]+$

Any guidance is appreciated.

**Comment by maxulysse** [comment]
Do you know which Mutect2 args to use for that?

**Comment by Ahas4** [comment]
> Do you know which Mutect2 args to use for that?

Hi, No I am very new to this so I have no insight .

**Comment by maxulysse** [comment]
I'm afraid my knowledge of Mutect2 is limited as well, I'll look in the docs when I can free some time to see if I can find anything.
So I suggest you do the same.
I'd recommend starting with:
https://gatk.broadinstitute.org/hc/en-us/articles/360035531132

**Comment by Ahas4** [comment]
Thank you so much for your time ! I appreciate it. I will look into this article now. I looked at a few sources but couldn't find an answer, hopefully this one will hold some clarity. Thank you !!!

**Comment by FriederikeHanssen** [comment]
there should be filtered and unfiltered calls. Do you mean your variants of interest are removed from the filtered vcf or the non-filtered one?

**Comment by Ahas4** [comment]
When I go on IGV for a sample that is at 5% tumour cellularity and search for the Variant for example KRAS , which is a known to be present for this type of cancer  in almost 100% of samples, I can see the KRAS variant on Chromosome 12 at the expected position on IGV but it does not appear on the non-filtered file ( Tumour_11.mutect2.vcf). I am working with a rare cancer type , its very difficult to get samples with high tumour content , thus I want to find a solution to identify variants that are at a low read % , for example to at least detect variants at 10% - 13% reads in samples with low cellularity (i.e. 5%-10% cellularity) as with the current performance of mutect2 , novel variants at a lower read would go unnoticed. I would deeply appreciate any help as this is a new field for me. Thanks

**Comment by Ahas4** [comment]
To answer your question, Yeas there is variants of interest removed from the non-filtered file, is there a way to lower the threshold when running nf-core/sarek so that I can get the variants that are at a lower threshold ? This is how I incorporate the tools used for my analysis: 

To run the pipeline I use :

nextflow run nf-core/sarek -r 3.0.2 -profile singularity 
-c nextflow.config 
--input Samplesheet.csv 
-w /scratch/designated work space 
--genome GATK.GRCh38 
--wes 
--intervals /specified target_sorted.unique.bed 
--tools cnvkit,freebayes,manta,mpileup,mutect2,strelka,tiddit,vep,snpeff
-- step annotate ^((cnvkit|freebayes|manta|merge|mpileup|mutect2|snpeff|strelka|tiddit|vep)?,?)*[^,]+$

**Comment by FriederikeHanssen** [comment]
> To answer your question, Yeas there is variants of interest removed from the non-filtered file, is there a way to lower the threshold when running nf-core/sarek so that I can get the variants that are at a lower threshold ? This is how I incorporate the tools used for my analysis:
> 
> To run the pipeline I use :
> 
> nextflow run nf-core/sarek -r 3.0.2 -profile singularity -c nextflow.config --input Samplesheet.csv -w /scratch/designated work space --genome GATK.GRCh38 --wes --intervals /specified target_sorted.unique.bed --tools cnvkit,freebayes,manta,mpileup,mutect2,strelka,tiddit,vep,snpeff -- step annotate ^((cnvkit|freebayes|manta|merge|mpileup|mutect2|snpeff|strelka|tiddit|vep)?,?)*[^,]+$

You can overwrite the arguments provided to mutect and play around with the threshold options given by the tool. For this you need to provde a custom.config with:

```
process{
    withName:"PAIRED_MUTECT2" {
         ext.args = { params.ignore_soft_clipped_bases ?
                                "--dont-use-soft-clipped-bases true --f1r2-tar-gz ${task.ext.prefix}.f1r2.tar.gz --normal-sample ${meta.patient}_${meta.normal_id} <add more arguments here>" :
                                "--f1r2-tar-gz ${task.ext.prefix}.f1r2.tar.gz --normal-sample ${meta.patient}_${meta.normal_id} <add more arguments here>" }
    
    }

}
```

(assuming here you have matched samples, if you don't we can adapt the config)

> -- step annotate ^((cnvkit|freebayes|manta|merge|mpileup|mutect2|snpeff|strelka|tiddit|vep)?,?)*[^,]+$
something is of with this line. this is not a valid one. I guess you just want to start from step annotae?

**Comment by Ahas4** [comment]
I see thank you !! I do not have matched normal for some of my samples, so I plan to run the tumour only samples separately to the tumour paired with normal sample. For the custom.config file do I add this in the same line as the initial config file. as in : 

nextflow run nf-core/sarek -r 3.0.2 -profile singularity
-c nextflow.config custom.config ( or do I add it in as a new line?) 
--input Samplesheet.csv


"-- step annotate ^((cnvkit|freebayes|manta|merge|mpileup|mutect2|snpeff|strelka|tiddit|vep)?,?)*[^,]+$
something is of with this line. this is not a valid one. I guess you just want to start from step annotate?" Oh I see, with this line I assumed it would add the annotations from VEP and snpeff to the same annotated VCF but then realised it wasn't the case , I must have misunderstood the purpose of it. I am glad you pointed it out. 

I truly appreciate your time and very thankful for it, I have a lot to learn.

**Comment by FriederikeHanssen** [comment]
If you specify multiple configs, I believe you have to add it like this: `-c config1.config -c config2.config` and so on. If you don't have matched normals, you might want to consider creating a panel-of-normals beforehand. We don't have it automitzed yet, but GATK offers some docs here: https://gatk.broadinstitute.org/hc/en-us/articles/360037058172-CreateSomaticPanelOfNormals-BETA-

For annotating, just add `--tools snpeff,vep` to the tools command you have. Then all vcf files are annotated :)

**Comment by Ahas4** [comment]
I see thank you !! May I please request your email address if its okay with you to send you a copy of my current config files to make sure I have everything in the correct format ? I would appreciate it. 

I see, mutect2 actually performed well with some of the tumour only samples, but I have been exploring the option to create a panel-of-normals for when I re-analyse the samples.

Thank you so much for your time :)

**Comment by FriederikeHanssen** [comment]
Are you on slack? If not, you can join here: https://nf-co.re/join
