### ISSUE TITLE
json schema does not validate --tools and --skip_tools

### ISSUE THREAD

**Issue by maxulysse** [nf-core/sarek#892]
### Description of the bug

```
nextflow run nf-core/sarek --profile test,docker --tools strelka2
```
should fail, but isn't

**Comment by asp8200** [comment]
I confirm the error. A cmd like
```
nextflow run nf-core/sarek -r 3.1.1 -profile test,singularity --tools foo --skip_tools bar
```
doesn't cause the pipeline to an early exit, instead:

```
Main options
  [...]
  tools                     : foo
  skip_tools                : bar
```

**Comment by maxulysse** [comment]
Do you think we can tests for failure in pytest?
I realize there are many expected failures that we should test...
Looking forward to test all that in nf-test

**Comment by FriederikeHanssen** [comment]
weird, do you know why? I thought everything is validated by default....

**Comment by maxulysse** [comment]
And I'm pretty sure this used to work

**Comment by asp8200** [comment]
> And I'm pretty sure this used to work

I - incidentally - tested it on Sarek 2.7, and it worked there.
