### ISSUE TITLE
configManta.py ignores `crai` index file path

### ISSUE THREAD

**Issue by Hoeze** [nf-core/sarek#901]
### Description of the bug

Hi, I just hit a problem that the `crai` index file path does not get passed to the `configManta.sh` script:
```bash
# cat .command.sh 
#!/bin/bash -euo pipefail
configManta.py         --bam GTEX-11EM3-0004-SM-6WBUK.cram         --reference Homo_sapiens_assembly38.fasta         --runDir manta         --callRegions chr18_20571467-20830724.bed.gz         
```

My files are named:
- `GTEX-11EM3-0004-SM-6WBUK.cram`
- `GTEX-11EM3-0004-SM-6WBUK.crai`
and I denoted this in the sample annotation.

 However, this information is not passed on to configManta.sh and therefore this step fails without properly named `.cram.crai` files.

### Command used and terminal output

```console
Setup any sample annotation with a non-standard index file name.
```

### System information

- nextflow version 22.04.5.5708
- Slurm cluster with Conda engine
- RockyLinux 8
- Sarek 3.1.1

**Comment by maxulysse** [comment]
Hi @Hoeze I'm afraid the crai file needs to have the cram extension before as well, so `GTEX-11EM3-0004-SM-6WBUK.cram.crai`
