### ISSUE TITLE
VEP tab output does not retain FILTER info

### ISSUE THREAD

**Issue by ftucos** [nf-core/sarek#903]
### Description of the bug

When I export the variants as table with the option ` --vep_out_format 'tab'` I have no trace of the variants marked as "PASS" in the final table.
I think it would make sense to annotate only variants that passed the filter or retain the "PASS" status in the final table

**Comment by FriederikeHanssen** [comment]
Hey! Is this an issue only with mutect variants or also other variantcallers? And do you know if the PASS column can be  kept from the VEP side?

**Comment by ftucos** [comment]
Hi @FriederikeHanssen ,
I did not experiment with other variant callers. 
I had to export the annotated variants as VCF to retain the PASS annotation in VEP.

**Comment by ftucos** [comment]
It happens only when I export the output of VEP as tab. I see the PASS field too in the VCF format.
P.S. I'm running the pipeline in "tumor only" mode. Maybe that could be relevant.

**Comment by FriederikeHanssen** [comment]
https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#tab it looks like this VEP specific for tab output :/

**Comment by ftucos** [comment]
Oh ok, thank you for the clarification.
