### ISSUE TITLE
Filter out variants in  homopolymeric regions

### ISSUE THREAD

**Issue by ftucos** [nf-core/sarek#904]
### Description of feature

In my experience, filtering out homopolymeric variants significantly contributed to removing artifactual variants.
I think that implementing VCFPolyX from [jvarkit](http://lindenb.github.io/jvarkit/) would be a nice feature.

**Comment by maxulysse** [comment]
Would love to add any tool made by @lindenb but I'm afraid I don't find it in bioconda.
Any easy install solution, or should we try an add it to bioconda?

**Comment by lindenb** [comment]
@maxulysse  I would **love** to see all my tools in bioconda but I'm too lazy for now (now = many years :smile:    )

**Comment by maxulysse** [comment]
Let's begin with one tool, and we'll see from there ;-)

**Comment by lindenb** [comment]
2018 : https://github.com/bioconda/bioconda-recipes/issues/8540 :-P

**Comment by pinin4fjords** [comment]
There are already a few jvarkit recipes - e.g. https://github.com/bioconda/bioconda-recipes/tree/master/recipes/jvarkit-bam2wig

```
> mamba search jvarkit
...
done
No match found for: jvarkit. Search: *jvarkit*
# Name                       Version           Build  Channel             
jvarkit-bam2svg         201904251722               1  bioconda            
jvarkit-bam2wig         201904251722               1  bioconda            
jvarkit-bamstats04        2021.10.13      hdfd78af_0  bioconda            
jvarkit-msa2vcf         201904251722               0  bioconda            
jvarkit-msa2vcf         201904251722               1  bioconda            
jvarkit-wgscoverageplotter        20201223               0  bioconda            
jvarkit-wgscoverageplotter        20201223               1  bioconda            
jvarkit-wgscoverageplotter        20201223               2  bioconda            
jvarkit-wgscoverageplotter        20201223      hdfd78af_3  bioconda
```

It will just be a case of copying the patterns used there.

**Comment by pinin4fjords** [comment]
> I saw it. And that's very very cool. But I would love to see all those programs in one and only one conda recipe and avoid those (ugly IMHO) java wrappers. I want something like `java -jar ${JVARKIT_DIST}/bam2svg.jar etc...`

The docs say "You shouldn't try to compile all the tools because some of them are not tested, deprecated, or just too specific to my lab.". So you'd need to generate a list of the ones that _should_ be included I guess?

**Comment by lindenb** [comment]
not bioconda but I created a docker https://hub.docker.com/repository/docker/lindenb/jvarkit/general

**Comment by maxulysse** [comment]
do you have the Dockerfile anywhere we can maybe try to biocondaize it

**Comment by lindenb** [comment]
> do you have the Dockerfile anywhere we can maybe try to biocondaize it

sure: https://github.com/lindenb/jvarkit/blob/dev/Dockerfile

**Comment by lindenb** [comment]
there is now: https://anaconda.org/bioconda/jvarkit
