### ISSUE TITLE
gnomAD and ExAC from VEP

### ISSUE THREAD

**Issue by maxulysse** [nf-core/sarek#91]
Issue by @szilvajuhos, moved from SciLifeLab#622

> **Add this AF metrics to annotation output**

> In the "gnomAD and ExAC" section of https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html it is stated that gnomAD replacing ExAC, and we should add this feature as it is not enabled by default.
> Also see: https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_af_gnomad

**Comment by FriederikeHanssen** [comment]
@maxulysse can this be closed now?
