### ISSUE TITLE
Unknown config attribute `params.test_data_base` -- check config file

### ISSUE THREAD

**Issue by aihualin** [nf-core/sarek#912]
### Description of the bug

Hi, 
I test the pipeline with 
nextflow run nf-core/sarek -profile test,docker --outdir outdir_test

got error:
N E X T F L O W  ~  version 22.10.4
Unknown config attribute `params.test_data_base` -- check config file: /home/xxx/.nextflow/assets/nf-core/sarek/nextflow.config

### Command used and terminal output

```console
nextflow run nf-core/sarek -profile test,docker --outdir outdir_test


N E X T F L O W  ~  version 22.10.4
Unknown config attribute `params.test_data_base` -- check config file: /home/xxx/.nextflow/assets/nf-core/sarek/nextflow.config
```

### System information

Ubuntu 22.04.1 LTS

N E X T F L O W  ~  version 22.10.4

Docker version 20.10.17

**Comment by maxulysse** [comment]
@aihualin sorry about it, that's totally on me.
It'll be fix in in the coming release.
In the meanwhile can you try:
```
nextflow run nf-core/sarek -profile test,docker --outdir outdir_test --test_data_base https://raw.githubusercontent.com/nf-core/test-datasets/modules
```

**Comment by aihualin** [comment]
> @aihualin sorry about it, that's totally on me. It'll be fix in in the coming release. In the meanwhile can you try:
> 
> ```
> nextflow run nf-core/sarek -profile test,docker --outdir outdir_test --test_data_base https://raw.githubusercontent.com/nf-core/test-datasets/modules
> ```

Hi

**Comment by aihualin** [comment]
Hi, Yes, it worked.

Thank you very much!

All the best, Aihua
