### ISSUE TITLE
cpu requirement

### ISSUE THREAD

**Issue by aihualin** [nf-core/sarek#913]
### Description of the bug

Hi, I run a sample test on my laptop. Is number of cpu a hard requirement?  

I got error:

Execution cancelled -- Finishing pending tasks before exit
-[nf-core/sarek] Pipeline completed with errors-
WARN: There's no process matching config selector: NFCORE_SAREK:SAREK:CRAM_QC_NO_MD:SAMTOOLS_STATS -- Did you mean: NFCORE_SAREK:SAREK:CRAM_QC_RECAL:SAMTOOLS_STATS?
Error executing process > 'NFCORE_SAREK:SAREK:FASTP (tumor_sample-lane_1)'

Caused by:
  Process requirement exceeds available CPUs -- req: 12; avail: 8

### Command used and terminal output

```console
nextflow run nf-core/sarek --input ${dir_p}/sarek/samplesheet.csv --outdir ${dir_p}/sarek/output/test --genome GATK.GRCh37  -profile docker
```

**Comment by maxulysse** [comment]
Try with --cpus 4 or --cpus 6

**Comment by aihualin** [comment]
tried and the same error reported.

**Comment by maxulysse** [comment]
Sorry --max_cpus instead...

**Comment by aihualin** [comment]
it is working now, thank you.
