### ISSUE TITLE
Pipeline completed with errors

### ISSUE THREAD

**Issue by aihualin** [nf-core/sarek#917]
I did analysis for target sequencing, with a .bed file. 

In the output folder, there is no variant_calling, What does this mean?
only folders: csv  multiqc  pipeline_info  preprocessing  reports
This was done without using the parameter --tools

then i tried --tools 'strelka,mutect2'. the anslysis stopped with error:
**The sample-sheet only contains normal-samples, but the following tools, which were requested with "--tools", expect at least one tumor-sample : mutect2**

My samplesheet.csv
patient,sample,lane,fastq_1,fastq_2
MP1708655B_S15,tumor_sample,lane_1,/dir/MP1708655B_S15_L001_R1_001.fastq.gz,/dir/MP1708655B_S15_L001_R2_001.fastq.gz

All the best
Aihua

**Comment by aihualin** [comment]
solved

**Comment by FriederikeHanssen** [comment]
Hi! Without seeing your command, I am guessing you didn't add the `--tools`parameter with which you can determine which tools to analyze your data with. For an overview over all possibilities see here: https://nf-co.re/sarek#pipeline-summary and here: https://nf-co.re/sarek/3.1.2/usage#which-variant-calling-tool-is-implemented-for-which-data-type 

You can in the same way also specify the annotation tools, e.g.: `--tools strelka,manta,vep` will run first strelka and manta and then annotates the results of both with vep

**Comment by FriederikeHanssen** [comment]
"The sample-sheet only contains normal-samples, but the following tools, which were requested with "--tools", expect at least one tumor-sample : mutect2"

Mutect can only be run on tumor-only or paired samples. In the csv this is indicated by the status column having a 1. If no status column is provided, it defaults to 0. So If you have tumor samples, add that column, and then it should work

**Comment by aihualin** [comment]
i see, thank you.
