### ISSUE TITLE
Pipeline completed with errors

### ISSUE THREAD

**Issue by aihualin** [nf-core/sarek#919]
### Description of the bug

Pipeline completed with errors

### Command used and terminal output

```console
nextflow run nf-core/sarek --input ${dir_p}/sarek/samplesheet.csv --intervals ${dir_p}/sarek/test.bed --tools 'strelka,mutect2,manta,vep' --outdir ${dir_p}/sarek/output/test --genome GATK.GRCh37  -profile docker --max_cpus 6 --max_memory '10.GB'

Pipeline completed with errors-
WARN: Unable to get file attributes file: s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Annotation/GATKBundle/af-only-gnomad.raw.sites.vcf.gz -- Cause: com.amazonaws.SdkClientException: Unable to execute HTTP request: Network is unreachable
WARN: Unable to get file attributes file: s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Annotation/GATKBundle/af-only-gnomad.raw.sites.vcf.gz.tbi -- Cause: com.amazonaws.SdkClientException: Unable to execute HTTP request: Network is unreachable
WARN: Unable to get file attributes file: s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Sequence/WholeGenomeFasta/human_g1k_v37_decoy.dict -- Cause: com.amazonaws.SdkClientException: Unable to execute HTTP request: Network is unreachable
WARN: Unable to get file attributes file: s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Annotation/GATKBundle/af-only-gnomad.raw.sites.vcf.gz -- Cause: com.amazonaws.SdkClientException: Unable to execute HTTP request: Network is unreachable
WARN: Unable to get file attributes file: s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Annotation/GATKBundle/af-only-gnomad.raw.sites.vcf.gz.tbi -- Cause: com.amazonaws.SdkClientException: Unable to execute HTTP request: Network is unreachable
WARN: Unable to get file attributes file: s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Annotation/GATKBundle/af-only-gnomad.raw.sites.vcf.gz -- Cause: com.amazonaws.SdkClientException: Unable to execute HTTP request: Network is unreachable
WARN: Unable to get file attributes file: s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/Annotation/GATKBundle/af-only-gnomad.raw.sites.vcf.gz.tbi -- Cause: com.amazonaws.SdkClientException: Unable to execute HTTP request: Network is unreachable
```

**Comment by maxulysse** [comment]
Hi @aihualin
I'm happy to see that you're trying out sarek quite extensively.
Thanks a lot for all the new issues, comments etc.
I'm always thrilled to have new people using sarek (or any nf-core pipeline), that's always a good opportunity for us to enhance docs, and add features.

For this issue, I can see that you're having connection issues, and that Nextflow is not able to download the AWS igenomes reference files from the s3 bucket.
May I recommend to try and download the files separately, and use --igenomes_base to point to the correct location on your system?

Something like that should do the trick using the [aws cli](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html):
```
aws s3 --no-sign-request --region eu-west-1 sync s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh37/ <PATH_TO_YOUR_SHARED_REFERENCE>/Homo_sapiens/GATK/GRCh37/
```
(adapt the <PATH_TO_YOUR_SHARED_REFERENCE> to your system.

**Comment by maxulysse** [comment]
And of course, I forgot to point to the documentation we actually have for that:
https://nf-co.re/usage/reference_genomes

**Comment by aihualin** [comment]
Hi, thank you. I got a new error :)

My mail goal is to get the vcf files using mutect2 and strelka. 

nextflow run nf-core/sarek --input ${dir_p}/samplesheet.csv --intervals ${dir_p}/gene_ABL1.bed --tools 'strelka,mutect2' --outdir ${dir_out} --genome GATK.GRCh37  -profile docker --igenomes_base ${dir_p}/ --max_cpus 6 --max_memory '10.GB'

Pipeline completed with errors-
Error executing process > 'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_TUMOR_ONLY_ALL:BAM_VARIANT_CALLING_TUMOR_ONLY_MUTECT2:CALCULATECONTAMINATION (tumor_sample)'

Caused by:
  Process `NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_TUMOR_ONLY_ALL:BAM_VARIANT_CALLING_TUMOR_ONLY_MUTECT2:CALCULATECONTAMINATION (tumor_sample)` terminated with an error exit status (3)

Command executed:

  gatk --java-options "-Xmx10g" CalculateContamination \
      --input tumor_sample.mutect2.pileupsummaries.table \
      --output tumor_sample.mutect2.contamination.table \
       \
      --tmp-dir . \
      -tumor-segmentation tumor_sample.mutect2.segmentation.table

**Comment by maxulysse** [comment]
Do you have any extra info about the error?
What's in the `.command.err` file in the corresponding work folder?

**Comment by aihualin** [comment]
here is the content in .command.err:

Using GATK jar /usr/local/share/gatk4-4.3.0.0-0/gatk-package-4.3.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx10g -jar /usr/local/share/gatk4-4.3.0.0-0/gatk-package-4.3.0.0-local.jar CalculateContamination --input tumor_sample.mutect2.pileupsummaries.table --output tumor_sample.mutect2.contamination.table --tmp-dir . -tumor-segmentation tumor_sample.mutect2.segmentation.table
11:20:47.951 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/gatk4-4.3.0.0-0/gatk-package-4.3.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
11:20:48.579 INFO  CalculateContamination - ------------------------------------------------------------
11:20:48.579 INFO  CalculateContamination - The Genome Analysis Toolkit (GATK) v4.3.0.0
11:20:48.580 INFO  CalculateContamination - For support and documentation go to https://software.broadinstitute.org/gatk/
11:20:48.580 INFO  CalculateContamination - Executing as aihua@5bf0564cafc0 on Linux v5.15.0-58-generic amd64
11:20:48.580 INFO  CalculateContamination - Java runtime: OpenJDK 64-Bit Server VM v11.0.15-internal+0-adhoc..src
11:20:48.580 INFO  CalculateContamination - Start Date/Time: January 23, 2023 at 11:20:47 AM GMT
11:20:48.580 INFO  CalculateContamination - ------------------------------------------------------------
11:20:48.581 INFO  CalculateContamination - ------------------------------------------------------------
11:20:48.582 INFO  CalculateContamination - HTSJDK Version: 3.0.1
11:20:48.582 INFO  CalculateContamination - Picard Version: 2.27.5
11:20:48.582 INFO  CalculateContamination - Built for Spark Version: 2.4.5
11:20:48.582 INFO  CalculateContamination - HTSJDK Defaults.COMPRESSION_LEVEL : 2
11:20:48.582 INFO  CalculateContamination - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
11:20:48.583 INFO  CalculateContamination - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
11:20:48.583 INFO  CalculateContamination - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
11:20:48.583 INFO  CalculateContamination - Deflater: IntelDeflater
11:20:48.583 INFO  CalculateContamination - Inflater: IntelInflater
11:20:48.583 INFO  CalculateContamination - GCS max retries/reopens: 20
11:20:48.583 INFO  CalculateContamination - Requester pays: disabled
11:20:48.584 INFO  CalculateContamination - Initializing engine
11:20:48.584 INFO  CalculateContamination - Done initializing engine
11:20:48.757 INFO  CalculateContamination - Shutting down engine
[January 23, 2023 at 11:20:48 AM GMT] org.broadinstitute.hellbender.tools.walkers.contamination.CalculateContamination done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=257949696
java.lang.IllegalArgumentException: Null object is not allowed here.
	at org.broadinstitute.hellbender.utils.Utils.nonNull(Utils.java:643)
	at org.broadinstitute.hellbender.utils.Utils.nonNull(Utils.java:631)
	at org.broadinstitute.hellbender.utils.tsv.TableWriter.writeMetadata(TableWriter.java:183)
	at org.broadinstitute.hellbender.tools.walkers.contamination.MinorAlleleFractionRecord.writeToFile(MinorAlleleFractionRecord.java:48)
	at org.broadinstitute.hellbender.tools.walkers.contamination.CalculateContamination.doWork(CalculateContamination.java:128)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by maxulysse** [comment]
I'm concerned by ` java.lang.IllegalArgumentException: Null object is not allowed here.`
Can you check if any of the file is empty?
I think I remember you were working with targeted sequencing, right?

**Comment by aihualin** [comment]
Do you mean to check the output folder?

Actually i got variant calling files from mutect2 and strelka. I don't know in which step the error happened
Mutect/tumor_sample:
tumor_sample.mutect2.artifactprior.tar.gz                tumor_sample.mutect2.pileupsummaries.table
tumor_sample.mutect2.contamination.table                 tumor_sample.mutect2.segmentation.table
tumor_sample.mutect2.filtered.vcf.gz                     tumor_sample.mutect2.vcf
tumor_sample.mutect2.filtered.vcf.gz.filteringStats.tsv  tumor_sample.mutect2.vcf.gz.stats
tumor_sample.mutect2.filtered.vcf.gz.tbi                 tumor_sample.mutect2.vcf.gz.tbi

 strelka/tumor_sample/:
tumor_sample.strelka.genome.vcf.gz      tumor_sample.strelka.variants.vcf
tumor_sample.strelka.genome.vcf.gz.tbi  tumor_sample.strelka.variants.vcf.gz.tbi

**Comment by aihualin** [comment]
and yes, it is targeted sequncing

**Comment by maxulysse** [comment]
> Can you check if any of the file is empty?

Sorry, I should have been clearer, I meant any of the input files in that work sub-folder

**Comment by aihualin** [comment]
I tried that single sample in the input folder, and just check 2 reads are not empty.

But just tried some other samples, the pipeline completed successfully. 
I can try more samples and see if the same error reported and then keep you updated.  
Thank you for your time.

**Comment by aihualin** [comment]
Hi it seems the pipeline works fine for all my other samples.
Thank you so much for your time and help!!
All the best
