### ISSUE TITLE
AD value of Strelka vcf

### ISSUE THREAD

**Issue by aihualin** [nf-core/sarek#925]
### Description of the bug

Hi, it turns out that the AD values in strelka vcf is incorrect for my analysis. 
where, ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed

because in my output, Allelic depths for the ref  is always 0. 

### Command used and terminal output

```console
nextflow run nf-core/sarek --input ${dir_sarek}/samplesheet.csv --intervals ${dir_sarek}/gene_${gene}.bed --tools 'strelka,mutect2' --outdir ${dir_out_sarek} --genome GATK.GRCh37  -profile docker --igenomes_base ${dir_sarek}/igenomes --max_cpus 6 --max_memory '10.GB'
```

EDIT by @maxulysse Markdown syntax

**Comment by maxulysse** [comment]
Hi @aihualin 
`igenomes_base` should point to a shared folder, which contains the reference data, and can include data for other pipelines than sarek.

In your case, given that you don't have any other issue, I would assume that the path resolves well, and that the issue is not there.

**Comment by maxulysse** [comment]
@aihualin can you explain more what is the issue for you there?

**Comment by aihualin** [comment]
For the tumor only sample analysis, the strelka vcf has a vairable called AD, which means, Allelic depths for the ref and alt alleles in the order listed.
I need to calculate the allelic fraction of the tumor and was told it can be calculated from the values of AD. 
for example if AD=10,5
then allelic fraction = 5/ (10+5) =0.33, right?

But in my output, Almost all AD=0, X,
that means the allelic fraction will always be 1 according to the formula, if it is right.

Thank you.

**Comment by maxulysse** [comment]
Is there any params in Strelka that could be use for that?
