### ISSUE TITLE
Add check for unique lanes in sample when parsing TSV files from FASTQ samples

### ISSUE THREAD

**Issue by maxulysse** [nf-core/sarek#93]
Issue by @MaxUlysse, moved from SciLifeLab#626

> We should have a warning when at least one sample has more than 2 FASTQ with the same lane.
> Right now, it's failing at the merging BAMs step.

> **Describe the solution you'd like**

> Add some checks when parsing the TSV file

> **Describe alternatives you've considered**

> No alternatives considered at the moment

> **Additional context**

> Issue discovered by Katja when running some WES project

Issue by @nicweb, moved from SciLifeLab#714

> When there is no lane information given in the sample.tsv markduplicates will fail with

> ```
>htsjdk.samtools.SAMFormatException: Error parsing SAM header. Problem
>parsing @rg key:value pair.
>```
> as readgroup ID is empty.

> Would be nice to check TSV before execution or autoset empty lane with sampleID or similar to avoid downstream execution halt, or update documentation that field should not be empty.

**Comment by FriederikeHanssen** [comment]
I'll reopen it, this was not actually closed.

**Comment by asp8200** [comment]
Message from @maxulysse in Slack-thread Sarek-3.0 (https://nfcore.slack.com/archives/C02MDBZAYJK/p1656668331195689): for the uniqueness of lanes and samples.
For a single patient, we can have several times the same sample as long as they have different lanes
And I think a sample should be unique (we should not have the same sample in different patients)

**Comment by asp8200** [comment]
This GitHub-issue seem to consists of two parts (https://github.com/SciLifeLab/Sarek/issues/626 and https://github.com/SciLifeLab/Sarek/issues/714). The latter part may already have been fixed. I tried running dev-Sarek with an input csv-like this:

patient,sex,sample,lane,fastq_1,fastq_2
NA12878,XX,NA12878,,/faststorage/home/aspe/test_data/85gnb0878-NA12878-DNA_Blood-WGS_v2_SUB_R1.fastq.gz,/faststorage/home/aspe/test_data/85gnb0878-NA12878-DNA_Blood-WGS_v2_SUB_R2.fastq.gz

that is, one where the lane-field is just empty, and Sarek crashed with the error message :
```
WARN  nextflow.Nextflow - Missing or unknown field in csv file header. Please check your samplesheet
```
