### ISSUE TITLE
ControlFreec Plots broken

### ISSUE THREAD

**Issue by apeltzer** [nf-core/sarek#931]
### Description of the bug

https://nf-co.re/sarek/results#sarek/results-c87f4eb694a7183e4f99c70fca0f1d4e91750b33/somatic_test/variant_calling/controlfreec/HCC1395T_vs_HCC1395N/HCC1395T_vs_HCC1395N_BAF.png

**Comment by FriederikeHanssen** [comment]
Same as #921 ?

**Comment by maxulysse** [comment]
Looks exactly the same indeed, closing this issue
