### ISSUE TITLE
Download link for the configuration file

### ISSUE THREAD

**Issue by songzhirui0o0** [nf-core/sarek#939]
Hi, I want to ask a seemingly stupid question. Could you please provide the download link for the configuration file in the link below. Thank you very much!

https://github.com/nf-core/sarek/blob/master/conf/igenomes.config

G1000_alleles_hg19.zip G1000_loci_hg19.zip GC_G1000_hg19.zip RT_G1000_hg19.zip 

I need the above four files. Hope you can provide some help or clues. grateful～

**Comment by FriederikeHanssen** [comment]
Docs are here: https://nf-co.re/sarek/3.1.2/usage#where-do-the-used-reference-genomes-originate-from nad here https://nf-co.re/sarek/latest/usage#how-to-run-ascat-with-whole-exome-sequencing-data
Ascat references: https://github.com/VanLoo-lab/ascat/tree/master/ReferenceFiles/WGS 
Under  "Data availability" you will find the links to the hg19 files

**Comment by songzhirui0o0** [comment]
Thank you very much for your reply

**Comment by FriederikeHanssen** [comment]
on a side note, any reference file that we use in the pipeline automatically is currently also stored in aws-igenomes: https://ewels.github.io/AWS-iGenomes/
