### ISSUE TITLE
Igenomes download failed

### ISSUE THREAD

**Issue by olu2016** [nf-core/sarek#940]
Hi,

I used the following command and the attached samplesheet to test run sarek:
nextflow run sarek --input samplesheet.csv --outdir sarek_out --genome GATK.GRCh38 -profile docker

But I got the following error:
Unexpected error [UnsupportedOperationException]
-- Check script 'sarek/./workflows/sarek.nf' at line: 56 or see '.nextflow.log' file for more details

I attached error logs.
[.nextflow.log](https://github.com/nf-core/sarek/files/10723033/default.nextflow.log)

I’m not sure what went wrong. Please help.

Best wishes,

Olu

**Comment by FriederikeHanssen** [comment]
Hi Olu!
Where are you running the analysis? I think the issue is that the reference genomes can't be properly accessed.

**Comment by olu2016** [comment]
Hi Friederike,

Thanks for replying.

I'm running sarek on a local server. I've looked into the issue of access to reference genome. I attached my latest error.

[.nextflow.log](https://github.com/nf-core/sarek/files/10732156/default.nextflow.log)

**Comment by FriederikeHanssen** [comment]
Hm can you try downlaoding the reference files before and set `--igenomes_base` ? 
Here you can download the data: https://ewels.github.io/AWS-iGenomes/
Set the fields as in the image below for GRCh38 
![Screenshot 2023-02-14 at 23 31 05](https://user-images.githubusercontent.com/12273093/218878234-b12b69cf-0e10-4902-bd20-880e6fae8bcd.png)

And then set `--igenomes_base` to whereever you have downloaded the data to. (Also this will make the pipeline run faster, as you don't need to redownload everything and so on for each run.

**Comment by olu2016** [comment]
Hi Friederike,

Problem now solved. Thanks
