### ISSUE TITLE
 mixing tumor-only and paired samples and having a tool that only works for paired samples causes the pipeline to fail

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#948]
### Description of the bug

When specifying mixed samples (tumor-only and paired) and some tools do not work for tumor-only, like msisensorpro, the pipeline will fail.

Reported by @MolPath-Bioinfo on Slack https://nfcore.slack.com/archives/CGFUX04HZ/p1676972372078189?thread_ts=1676897338.792179&cid=CGFUX04HZ

I am guessing we went a bit overboard with validating the tools parameter on input sample sheet parsing.

**Comment by FriederikeHanssen** [comment]
hm I can't reproduce this issue. Tested with `nextflow run main.nf -profile test,variantcalling_channels,docker --tools msisensorpro  --outdir ./results` the samplesheet contains:

```
patient,sex,status,sample,cram,crai
test,XX,0,sample1,https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/illumina/cram/test.paired_end.recalibrated.sorted.cram,https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/illumina/cram/test.paired_end.recalibrated.sorted.cram.crai
test1,XX,1,sample2,https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/illumina/cram/test2.paired_end.recalibrated.sorted.cram,https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/illumina/cram/test2.paired_end.recalibrated.sorted.cram.crai
test3,XX,0,sample3,https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/illumina/cram/test.paired_end.recalibrated.sorted.cram,https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/illumina/cram/test.paired_end.recalibrated.sorted.cram.crai
test3,XX,1,sample4,https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/illumina/cram/test2.paired_end.recalibrated.sorted.cram,https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/homo_sapiens/illumina/cram/test2.paired_end.recalibrated.sorted.cram.crai
```

So a mix of paired and tumor-only sample. Using msisensorpro I would expect a failure based on the report, but it works fine for me.

**Comment by MolPath-Bioinfo** [comment]
Hi. I will try another mixed run this week and get back to you.
________________________________
Von: Friederike Hanssen ***@***.***>
Gesendet: Montag, 29. Mai 2023 12:31:02
An: nf-core/sarek
Cc: Mihaela Martis-Thiele; Mention
Betreff: Re: [nf-core/sarek] mixing tumor-only and paired samples and having a tool that only works for paired samples causes the pipeline to fail (Issue #948)


I will need more info on the issue to fix.

**Comment by FriederikeHanssen** [comment]
closed as non reproducable. Please reopen if you encounter this issue again
