### ISSUE TITLE
Running the annotation step does not work with the full samplesheet file described on the website or with the variantcalling.csv file generated by the pipeline in a previous step

### ISSUE THREAD

**Issue by MolPath-Bioinfo** [nf-core/sarek#949]
### Description of the bug

Running only the **annotation step** using the csv file generated by the Sarek 3.1.2 pipeline in a previous run (variantcaller.csv) ends with the following error:

_`The sample-sheet only contains normal-samples, but the following tools, which were requested with "--tools", expect at least one tumor-sample : mutect2`_

The content of the variantcaller.csv corresponds to the full samplesheet described on the website and has the following format:
```
patient,sample,variantcaller,vcf
P1,H-2022-09665,mutect2,H-2022-09665.mutect2.filtered.vcf.gz
P1,H-2022-09665,strelka,H-2022-09665.strelka.variants.vcf.gz
```
**Solution**: adding the columns **sex** and **status** to the input file (directly after the **patient** column) solves the problem
```
patient,sex,status.sample,variantcaller,vcf
P1,XX,1,H-2022-09665,mutect2,H-2022-09665.mutect2.filtered.vcf.gz
P1,XX,1,H-2022-09665,strelka,H-2022-09665.strelka.variants.vcf.gz
```
The documentation on the website needs to be adapted and the 2 columns added to the full samplesheet example.

This behavior is not consistent in all steps. If I run the pipeline from the beginning with the tools 
`--tools mutect2,strelka,vep`
then the error does not occur.

The columns **sex** and **status** seems to be required in all cases when one runs the individual steps using the **--step** parameter. I encountered this also while running only the variant calling step.

### Command used and terminal output

```console
nextflow run /home/thiele/local_apps/nf-core-sarek-3.1.2/workflow -profile singularity -c "/mnt/Molpath/users/mihaela/projects/variant_calling/WES/220728_A01542_0030_AHNCCMDRXY_3Aug_TWIST/VIP_tumorOnly/config/nf_wes.config" -params-file "/mnt/Molpath/users/mihaela/projects/variant_calling/WES/220728_A01542_0030_AHNCCMDRXY_3Aug_TWIST/VIP_tumorOnly/config/nf_params.json" --step annotate --vep_species "homo_sapiens" --vep_version '106.1' --vep_include_fasta --vep_loftee --vep_spliceregion


The sample-sheet only contains normal-samples, but the following tools, which were requested with "--tools", expect at least one tumor-sample : mutect2
```

### System information

- System: Linux 5.4.0-136-generic Ubuntu
- nf-core/sarek 3.1.2
- executor: local
- hardware: Desktop
- nextflow version: 22.10.4 build 5836
- container engine: Singularity

**Comment by FriederikeHanssen** [comment]
See also #948

**Comment by FriederikeHanssen** [comment]
Hi Mihaela! Is this working when just `Sex`?

**Comment by MolPath-Bioinfo** [comment]
Hi Friederike, no it doesn't. It requests that one provides the sex and if tumor or normal sample. Theoretically it requests the full input file as one would run the preprocessing and variant call step too.
________________________________
Von: FriederikeHanssen ***@***.***>
Gesendet: Montag, 27. März 2023 17:25:46
An: nf-core/sarek
Cc: Mihaela Martis-Thiele; Author
Betreff: Re: [nf-core/sarek] Running the annotation step does not work with the full samplesheet file described on the website or with the variantcalling.csv file generated by the pipeline in a previous step (Issue #949)


Hi Mihaela! Is this working when just status?

**Comment by MolPath-Bioinfo** [comment]
Yes, mutect is not an annotation tool, but in this step I  don't call it. I just make use of its output, which I want to annotate....
________________________________
Von: FriederikeHanssen ***@***.***>
Gesendet: Montag, 27. März 2023 17:31:44
An: nf-core/sarek
Cc: Mihaela Martis-Thiele; Author
Betreff: Re: [nf-core/sarek] Running the annotation step does not work with the full samplesheet file described on the website or with the variantcalling.csv file generated by the pipeline in a previous step (Issue #949)


hm I am thinking about this issue. and it should probably fail: mutect2 is not an annotation tool, but it starts from --step annotate, so it should fail but for a different reason

**Comment by FriederikeHanssen** [comment]
Tool validation will now be skipped if `--step annotate`is run. However, if starting from annotation, there shouldn't be any need to set a variant caller
