### ISSUE TITLE
More check for the samplesheet

### ISSUE THREAD

**Issue by maxulysse** [nf-core/sarek#950]
### Description of feature

no space in sample or id

**Comment by maxulysse** [comment]
We could have spaces replaced by `_`

**Comment by asp8200** [comment]
> We could have spaces replaced by `_`

Users could potentially be confused by such automatic changes to identifiers like sample and id. Perhaps it would be better just to enforce a policy of no spaces in sample or id, and then let the users deal with that themselves? 🤔

**Comment by matrulda** [comment]
Fix merged in https://github.com/nf-core/sarek/pull/978
