### ISSUE TITLE
Community feedback needed: Add tutorials/faqs describing different usages to the website

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#955]
### Description of feature

We are looking into expanding the documentation by adding tutorials for different usages. For this we would love some community feedback: 

What are some questions you asked yourself when starting out? What would you like to see explained in more detail? Where do you find the documentation is lacking?

**Comment by maxulysse** [comment]
- How to use sarek with genome not in iGenomes (#958)

**Comment by egenomics** [comment]
* How to use sarek when library was done using UMIs. Starting at different steps (a) UMIs already present in the fastq header, but not in sequence, b) original bcls, etc
* How to provide different parameters for certain tools

**Comment by GeertvanGeest** [comment]
As far as I know, `--intervals` would need to be either a 3 column bed, or a 5 column bed with estimated seconds in the score column. Anything else will/can result in failures (at least with gatk). Would be nice to make this more explicit.

**Comment by FriederikeHanssen** [comment]
Superseded by #1704
