### ISSUE TITLE
Support for PureCN for estimating purity/ploidy

### ISSUE THREAD

**Issue by lbeltrame** [nf-core/sarek#956]
### Description of feature

As the subject says, [PureCN](https://github.com/lima1/PureCN) is a software for calling copy number and variants after estimating tumor purity and ploidy. In our experience it performs better than ASCAT with low-purity(< 40%) samples.

A typical PureCN analysis involves creating a panel of normals (PoN) which is then used as a reference to estimate purity/ploidy and from there CNV and SNV.  Currently there are no modules in nf-core to use PureCN (however it's in bioconda), so these would need to be done first.

I'm posting this to enquire whether there is interest, as if so, we are considering implementing this support ourselves.

cc @LMannarino @aldosr @rikizad

**Comment by maxulysse** [comment]
thanks a lot for the suggestion, adding this in the list: https://github.com/nf-core/sarek/issues/95

**Comment by peterkilfeather** [comment]
Would be very keen to have support for PureCN

**Comment by FriederikeHanssen** [comment]
@lbeltrame is working on it :) @maxulysse btw might be another interesting candidate for nf-core/createpanelref

**Comment by lbeltrame** [comment]
Yes, more or less. Don't hold your breath, though. ;)
