### ISSUE TITLE
Canfam4 genome

### ISSUE THREAD

**Issue by KeyTals** [nf-core/sarek#958]
Hello,

Would it possible to add references and annotations for Canfam4 to perform somatic analysis? I can see canfan3.1 is already there but its very old now.

Thank you,
Keyur

**Comment by maxulysse** [comment]
Hi @KeyTals,

I would love to be able to add more genomes to sarek, but for now we depend on [AWS Igenomes](https://registry.opendata.aws/aws-igenomes/), and no CanFam4 there, and I'm afraid it won't happen anytime soon.
We're thinking of swtiching to [refgenie](http://refgenie.databio.org/en/latest/) at some point.

In the meantime, I'm afraid the only option is to use `--genome null --igenomes_ignore` and use `--fasta` and other reference params to specify the needed files.
I'm referencing your issue in #955 as I feel more documentation on how to do that would be quite useful for any users.
