### ISSUE TITLE
Info needed for --max_cpus

### ISSUE THREAD

**Issue by TonyKess** [nf-core/sarek#961]
### Description of feature

I was wondering if there could be more information provided on max-cpus and max-memory? Right now I am trying to figure out whether I need to scale these depending on the number of samples in the sample sheet, or whether nextflow will handle allocations of memory and cpus to not pass processes for samples that can't be run yet?

Thanks!

**Comment by maxulysse** [comment]
The documentation for that is here: https://nf-co.re/usage/configuration#max-resources
They do act as ceiling value and will not raise the minimum but just ensure the max doesn't go over this treshold
