### ISSUE TITLE
Can you add the trimming step?

### ISSUE THREAD

**Issue by JiahuaQu** [nf-core/sarek#974]
### Description of feature

Hi, thank you for bulding this great pipeline. I have a small queation: why there isn't the trimming step before mapping? Is it necessary for general WGS or WES analysis? Can you add that step in your pipeline? Thank you.

**Comment by FriederikeHanssen** [comment]
Hi! Fastp can be used for trimming. If you add the parameter `--trim_fastq` the tool will be run with `--detect_adapter_for_pe` . Does that work for you?

**Comment by JiahuaQu** [comment]
> 

Yes. thank you for the immediate answer.

**Comment by FriederikeHanssen** [comment]
Sure :) I will close the issue then.
