### ISSUE TITLE
Singularity related-problems

### ISSUE THREAD

**Issue by JaumeBagueCompanys** [nf-core/sarek#986]
### Description of the bug

I am using the pipeline sarek in my local PC for much time but now I find an error. I cannot run any sample neither any basic test.
My error happens when the pipeline is beginning. I am sure that is for singularity, but I try to install an updated version and reinstall my older version but the problem is not solved.

Please, can somebody helps me? 
 

### Command used and terminal output

```console
nextflow run nf-core/sarek -r 3.1.2 -profile test,singularity
or
nextflow run ./workflow/main.nf -profile test,singularity

My output is:
Error executing process > 'NFCORE_SAREK:SAREK:PREPARE_INTERVALS:GATK4_INTERVALLISTTOBED (genome)'

Caused by:
  Process `NFCORE_SAREK:SAREK:PREPARE_INTERVALS:GATK4_INTERVALLISTTOBED (genome)` terminated with an error exit status (255)

Command executed:

  gatk --java-options "-Xmx6g" IntervalListToBed \
      --INPUT genome.interval_list \
      --OUTPUT genome.bed \
      --TMP_DIR . \
  
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SAREK:SAREK:PREPARE_INTERVALS:GATK4_INTERVALLISTTOBED":
      gatk4: $(echo $(gatk --version 2>&1) | sed 's/^.*(GATK) v//; s/ .*$//')
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: failed to find loop device: could not attach image file to loop device: no loop devices available

Work dir:
  /home/jaume/Escritorio/nf-core-sarek-3.1.2/work/4a/55152df9acac9853ec372b4d6a7b12

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

### System information

I am using: 
Nextflow version 22.10.7 build 5853 
nf-core v. 2.7.2
Singularity version 3.5.3 (I try 3.11 but the problem persist and I re-install this version)
java version 11.0.18
OS: Ubuntu 2020

**Comment by JaumeBagueCompanys** [comment]
I tryed to reinstal all ubuntu system, but the problem was not fix.

**Comment by FriederikeHanssen** [comment]
Hi! Sorry for  the late reply: can you try the suggestions made here: https://nfcore.slack.com/archives/CE6SDBX2A/p1683316623327939?

**Comment by FriederikeHanssen** [comment]
Was this resolved?

**Comment by FriederikeHanssen** [comment]
ok great :)
