### ISSUE TITLE
ControlFREEC: Error in plot.window(...) : need finite 'ylim' values

### ISSUE THREAD

**Issue by hyjforesight** [nf-core/sarek#993]
### Description of the bug

Hello nf-core SAREK team,
I met controlfreec errors when I was running SAREK offline.
Here is the command I run:
```linux
nextflow run /home/hyjforesight/nf-core-sarek-3.1.2/workflow sarek --input /home/hyjforesight/Sarek_design_copy.csv --outdir /mnt/d/WES/ --genome GATK.GRCh38 -profile docker --tools freebayes,mutect2,strelka,manta,tiddit,cnvkit,controlfreec,snpeff,vep
```
Error message:
```linux
[nf-core/sarek] Pipeline completed with errors-
Error executing process > 'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_TUMOR_ONLY_ALL:BAM_VARIANT_CALLING_TUMOR_ONLY_CONTROLFREEC:MAKEGRAPH (C1033)'

Caused by:
  Process `NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_TUMOR_ONLY_ALL:BAM_VARIANT_CALLING_TUMOR_ONLY_CONTROLFREEC:MAKEGRAPH (C1033)` terminated with an error exit status (1)

Command executed:

  cat $(which makeGraph.R) | R --slave --args 2 C1033.tumor.mpileup.gz_ratio.txt C1033.tumor.mpileup.gz_BAF.txt
  
  mv *_BAF.txt.png C1033_BAF.png
  mv *_ratio.txt.log2.png C1033_ratio.log2.png
  mv *_ratio.txt.png C1033_ratio.png
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_TUMOR_ONLY_ALL:BAM_VARIANT_CALLING_TUMOR_ONLY_CONTROLFREEC:MAKEGRAPH":
      controlfreec: $(echo $(freec -version 2>&1) | sed 's/^.*Control-FREEC  //; s/:.*$//' | sed -e "s/Control-FREEC v//g" )
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error in plot.window(...) : need finite 'ylim' values
  Calls: plot -> plot.default -> localWindow -> plot.window
  In addition: There were 17 warnings (use warnings() to see them)
  Execution halted

Work dir:
  /home/hyjforesight/work/73/248c092693a8d9612f76e8fb25e3d7

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```
Could you please help me with this issue? Thank you in advance!

### Command used and terminal output

```console
$ nextflow run /home/hyjforesight/nf-core-sarek-3.1.2/workflow sarek --input /home/hyjforesight/Sarek_design_copy.csv --outdir /mnt/d/WES/ --genome GATK.GRCh38 -profile docker --tools freebayes,mutect2,strelka,manta,tiddit,cnvkit,controlfreec,snpeff,vep
```

### Relevant files

[](url)
[nextflow (1).log](https://github.com/nf-core/sarek/files/11218304/nextflow.1.log)

### System information

Nextflow version: 22.10.6.5843
Hardware: Desktop
Executor: local
Container engine: Docker
OS: Win11 22H2, WSL2, Ubuntu 22.04
Version of nf-core/sarek: 3.1.2

**Comment by hyjforesight** [comment]
Here are the responses from Thomas Danhorn and Friederike Hanssen

Thomas Danhorn
  [11 小时前](https://nfcore.slack.com/archives/CGFUX04HZ/p1681323141714949?thread_ts=1681224366.028039&cid=CGFUX04HZ)
Short of not running ControlFREEC, I don't know.  Any ideas 
[@Maxime Garcia](https://nfcore.slack.com/team/UE6D8290F)
 or 
[@Friederike Hanssen](https://nfcore.slack.com/team/UPC8CHDKQ)
? （已编辑） 


Friederike Hanssen
:nf-core:  [9 小时前](https://nfcore.slack.com/archives/CGFUX04HZ/p1681328852765219?thread_ts=1681224366.028039&cid=CGFUX04HZ)
hm seems to be something weird with makegraph visualisation. I didn’t find anything on their github repo for it. YOu could edit the error stragtey for the process to get the calls and then do your own visualization by putting the following into a custom.config and adding it with -c to your command
process {
    withName: MAKEGRAPH {
     errorStrategy = 'ignore' 
   }
}


Friederike Hanssen
:nf-core:  [9 小时前](https://nfcore.slack.com/archives/CGFUX04HZ/p1681328908426489?thread_ts=1681224366.028039&cid=CGFUX04HZ)
There appears to be a new makeGraph script: https://github.com/BoevaLab/FREEC/blob/master/scripts/makeGraph2.0.R you could take the output as generated by the pipeline and try running this on einstead
[makeGraph2.0.R](https://github.com/BoevaLab/FREEC/blob/master/scripts/makeGraph2.0.R)
#!/usr/bin/env Rscript

# One way to run this script is:
# cat makeGraph.R | R --slave --args [*_ratio.txt](https://app.slack.com/client/TE6CZUZPH/CGFUX04HZ/thread/*_ratio.txt) [[*_BAF.txt](https://app.slack.com/client/TE6CZUZPH/CGFUX04HZ/thread/*_BAF.txt)]
# Ploidy value will be inferred from the ratio file
显示更多
<https://github.com/[BoevaLab/FREEC](https://github.com/BoevaLab/FREEC)|BoevaLab/FREEC>BoevaLab/FREEC | 添加人 [GitHub](https://nfcore.slack.com/services/B0200EH4VEC)

**Comment by nschcolnicov** [comment]
Hi @hyjforesight, I encountered the same issue as you, in my case, the reason for it was that the ratio table being used by the makeGraph.R script contained values that, after applying the log2, would become NaN values. Neither the makeGraph.R nor the makeGraph2.0.R script are prepared to handle these values, so this triggers the "need finite 'ylim' values" when attempting to plot them.
To fix it I did the following:
Downloaded the makeGraph2.0.R script into the bin folder

**Comment by nschcolnicov** [comment]
Hi @hyjforesight , I encountered the same issue as you, in my case, the reason for it was that the ratio table being used by the makeGraph.R script contained values that, after applying the log2, would become NaN values. Neither the makeGraph.R nor the makeGraph2.0.R script are prepared to handle these values, so this triggers the "need finite 'ylim' values" when attempting to plot them.
To fix it you can do the following:
1. Clone the sarek repo, checkout into master, and create a bin folder. Or checkout into dev that already has a bin folder. It works on both branches.
2. Download the makeGraph2.0.R script from my branch: https://raw.githubusercontent.com/nschcolnicov/FREEC/Need_finite_ylim_values_fix/scripts/makeGraph2.0.R and place it in the bin folder.
3. Update the makegraph main file so that it uses the updated script instead of the other one, you can find it in: 
sarek/modules/nf-core/controlfreec/makegraph/main.nf
You must change the line 28: "cat \$(which makeGraph.R) | R --slave --args ${args} ${ratio} ${baf}" to "makeGraph2.5.R ${args} ${ratio} ${baf}"

Let me know if you have any questions or if you fixed the issue some other way!

**Comment by FriederikeHanssen** [comment]
We just updated the bioconda recipe with the Controlfreec release 11.6b that contains makegraph 2. Once it is available on biocontainers you can also use the container directly and in case we'll update the process for the next release
